# app/seed_data/meta_doctypes/data.py
from __future__ import annotations
from typing import List, Dict, Any

# Each entry here describes one Doctype meta + its fields + links.
# name      → Doctype.name (must match RBAC DocType name ideally)
# label     → display label
# module    → logical module
# table_name→ underlying SQL table name
# fields    → DocField specs
# links     → DocLink specs (parent_doctype is inferred)

DOCTYPE_META_SPECS: List[Dict[str, Any]] = [
    # ─────────────────────────────
    # ORGANIZATION
    # ─────────────────────────────
    {
        "name": "City",
        "label": "City",
        "module": "Organization",
        "table_name": "cities",
        "icon": "map-pin",
        "is_child": False,
        "is_single": False,
        "is_tree": False,
        "is_submittable": False,
        "track_changes": True,
        "track_seen": False,
        "track_views": True,
        "quick_entry": False,
        "description": "Cities used for company and address master data.",
        "fields": [
            {
                "fieldname": "name",
                "label": "City Name",
                "fieldtype": "Data",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": True,
                "idx": 10,
                "description": None,
                "options": None,
                "default": None,
            },
            {
                "fieldname": "region",
                "label": "Region",
                "fieldtype": "Data",
                "reqd": False,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 20,
                "description": None,
                "options": None,
                "default": None,
            },
        ],
        "links": [
            {
                "link_doctype": "Company",
                "link_fieldname": "city_id",
                "group_label": "Companies",
            }
        ],
    },
    {
        "name": "Company",
        "label": "Company",
        "module": "Organization",
        "table_name": "companies",
        "icon": "building-2",
        "is_child": False,
        "is_single": False,
        "is_tree": False,
        "is_submittable": False,
        "track_changes": True,
        "track_seen": False,
        "track_views": True,
        "quick_entry": False,
        "description": "Legal entity that owns branches and accounting records.",
        "fields": [
            {
                "fieldname": "name",
                "label": "Company Name",
                "fieldtype": "Data",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": True,
                "idx": 10,
                "description": None,
                "options": None,
                "default": None,
            },
            {
                "fieldname": "prefix",
                "label": "Code / Prefix",
                "fieldtype": "Data",
                "reqd": False,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 20,
                "description": "Short unique prefix used in document numbers.",
                "options": None,
                "default": None,
            },
            {
                "fieldname": "contact_email",
                "label": "Email",
                "fieldtype": "Data",
                "reqd": False,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 30,
                "description": None,
                "options": None,
                "default": None,
            },
            {
                "fieldname": "contact_phone",
                "label": "Phone",
                "fieldtype": "Data",
                "reqd": False,
                "read_only": False,
                "hidden": False,
                "in_list_view": False,
                "in_filter": False,
                "in_quick_entry": False,
                "idx": 40,
                "description": None,
                "options": None,
                "default": None,
            },
            {
                "fieldname": "city_id",
                "label": "City",
                "fieldtype": "Link",
                "reqd": False,
                "read_only": False,
                "hidden": False,
                "in_list_view": False,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 50,
                "description": None,
                "options": "City",  # link target doctype
                "default": None,
            },
            {
                "fieldname": "status",
                "label": "Status",
                "fieldtype": "Select",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 60,
                "description": None,
                "options": "Active\nDisabled",
                "default": "Active",
            },
        ],
        "links": [
            {
                "link_doctype": "Branch",
                "link_fieldname": "company_id",
                "group_label": "Branches",
            },
            {
                "link_doctype": "Department",
                "link_fieldname": "company_id",
                "group_label": "Departments",
            },
            {
                "link_doctype": "Fiscal Year",
                "link_fieldname": "company_id",
                "group_label": "Fiscal Years",
            },
            {
                "link_doctype": "Account",
                "link_fieldname": "company_id",
                "group_label": "Chart of Accounts",
            },
        ],
    },
    {
        "name": "Branch",
        "label": "Branch",
        "module": "Organization",
        "table_name": "branches",
        "icon": "building",
        "is_child": False,
        "is_single": False,
        "is_tree": False,
        "is_submittable": False,
        "track_changes": True,
        "track_seen": False,
        "track_views": True,
        "quick_entry": False,
        "description": "Physical or logical branch of a company.",
        "fields": [
            {
                "fieldname": "company_id",
                "label": "Company",
                "fieldtype": "Link",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": True,
                "idx": 10,
                "description": None,
                "options": "Company",
                "default": None,
            },
            {
                "fieldname": "name",
                "label": "Branch Name",
                "fieldtype": "Data",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": True,
                "idx": 20,
                "description": None,
                "options": None,
                "default": None,
            },
            {
                "fieldname": "code",
                "label": "Branch Code",
                "fieldtype": "Data",
                "reqd": False,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": False,
                "in_quick_entry": False,
                "idx": 30,
                "description": None,
                "options": None,
                "default": None,
            },
            {
                "fieldname": "is_hq",
                "label": "Is Head Office",
                "fieldtype": "Check",
                "reqd": False,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 40,
                "description": None,
                "options": None,
                "default": "0",
            },
        ],
        "links": [
            {
                "link_doctype": "Cost Center",
                "link_fieldname": "branch_id",
                "group_label": "Cost Centers",
            },
            {
                "link_doctype": "Journal Entry",
                "link_fieldname": "branch_id",
                "group_label": "Journal Entries",
            },
            {
                "link_doctype": "General Ledger Entry",
                "link_fieldname": "branch_id",
                "group_label": "GL Entries",
            },
        ],
    },
    {
        "name": "Department",
        "label": "Department",
        "module": "Organization",
        "table_name": "departments",
        "icon": "users",
        "is_child": False,
        "is_single": False,
        "is_tree": False,
        "is_submittable": False,
        "track_changes": True,
        "track_seen": False,
        "track_views": True,
        "quick_entry": False,
        "description": "Company departments used in HR and approvals.",
        "fields": [
            {
                "fieldname": "company_id",
                "label": "Company",
                "fieldtype": "Link",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 10,
                "description": None,
                "options": "Company",
                "default": None,
            },
            {
                "fieldname": "name",
                "label": "Department Name",
                "fieldtype": "Data",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": True,
                "idx": 20,
                "description": None,
                "options": None,
                "default": None,
            },
            {
                "fieldname": "code",
                "label": "Code",
                "fieldtype": "Data",
                "reqd": False,
                "read_only": False,
                "hidden": False,
                "in_list_view": False,
                "in_filter": False,
                "in_quick_entry": False,
                "idx": 30,
                "description": None,
                "options": None,
                "default": None,
            },
            {
                "fieldname": "status",
                "label": "Status",
                "fieldtype": "Select",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 40,
                "description": None,
                "options": "Active\nDisabled",
                "default": "Active",
            },
        ],
        "links": [],
    },

    # ─────────────────────────────
    # ACCOUNTS / FINANCE
    # ─────────────────────────────
    {
        "name": "Fiscal Year",
        "label": "Fiscal Year",
        "module": "Accounts",
        "table_name": "fiscal_years",
        "icon": "calendar",
        "is_child": False,
        "is_single": False,
        "is_tree": False,
        "is_submittable": False,
        "track_changes": True,
        "track_seen": False,
        "track_views": True,
        "quick_entry": False,
        "description": "Time period for financial reporting.",
        "fields": [
            {
                "fieldname": "company_id",
                "label": "Company",
                "fieldtype": "Link",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 10,
                "description": None,
                "options": "Company",
                "default": None,
            },
            {
                "fieldname": "name",
                "label": "Fiscal Year Name",
                "fieldtype": "Data",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": False,
                "in_quick_entry": True,
                "idx": 20,
                "description": "e.g. FY 2025 or 2024-2025",
                "options": None,
                "default": None,
            },
            {
                "fieldname": "start_date",
                "label": "Start Date",
                "fieldtype": "Date",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": False,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 30,
                "description": None,
                "options": None,
                "default": None,
            },
            {
                "fieldname": "end_date",
                "label": "End Date",
                "fieldtype": "Date",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": False,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 40,
                "description": None,
                "options": None,
                "default": None,
            },
            # ✅ NEW: Short Fiscal Year
            {
                "fieldname": "is_short_year",
                "label": "Short Fiscal Year",
                "fieldtype": "Check",
                "reqd": False,
                "read_only": False,
                "hidden": False,
                "in_list_view": False,
                "in_filter": False,
                "in_quick_entry": False,
                "idx": 45,
                "description": "Tick if this is a short fiscal year (less than 12 months).",
                "options": None,
                "default": "0",
            },
            {
                "fieldname": "status",
                "label": "Status",
                "fieldtype": "Select",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 50,
                "description": None,
                "options": "Open\nClosed",
                "default": "Open",
            },
        ],
        "links": [
            {
                "link_doctype": "Journal Entry",
                "link_fieldname": "fiscal_year_id",
                "group_label": "Journal Entries",
            },
            {
                "link_doctype": "General Ledger Entry",
                "link_fieldname": "fiscal_year_id",
                "group_label": "GL Entries",
            },
        ],
    },

    {
        "name": "Period Closing Voucher",
        "label": "Period Closing Voucher",
        "module": "Accounts",
        "table_name": "period_closing_vouchers",
        "icon": "lock",
        "is_child": False,
        "is_single": False,
        "is_tree": False,
        "is_submittable": True,
        "track_changes": True,
        "track_seen": False,
        "track_views": True,
        "quick_entry": False,
        "description": "Document to close a fiscal year and transfer P/L to retained earnings.",
        "fields": [
            {
                "fieldname": "company_id",
                "label": "Company",
                "fieldtype": "Link",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 10,
                "description": None,
                "options": "Company",
                "default": None,
            },
            {
                "fieldname": "closing_fiscal_year_id",
                "label": "Closing Fiscal Year",
                "fieldtype": "Link",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 20,
                "description": None,
                "options": "Fiscal Year",
                "default": None,
            },
            {
                "fieldname": "code",
                "label": "Voucher Code",
                "fieldtype": "Data",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": False,
                "in_quick_entry": False,
                "idx": 30,
                "description": None,
                "options": None,
                "default": None,
            },
            {
                "fieldname": "posting_date",
                "label": "Posting Date",
                "fieldtype": "Date",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": False,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 40,
                "description": None,
                "options": None,
                "default": None,
            },
            {
                "fieldname": "doc_status",
                "label": "Status",
                "fieldtype": "Select",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 50,
                "description": None,
                "options": "Draft\nSubmitted\nCancelled",
                "default": "Draft",
            },
            {
                "fieldname": "total_profit_loss",
                "label": "Total Profit/Loss",
                "fieldtype": "Currency",
                "reqd": False,
                "read_only": True,
                "hidden": False,
                "in_list_view": False,
                "in_filter": False,
                "in_quick_entry": False,
                "idx": 60,
                "description": None,
                "options": None,
                "default": None,
            },
        ],
        "links": [
            {
                "link_doctype": "Journal Entry",
                "link_fieldname": "generated_journal_entry_id",
                "group_label": "Closing Journal Entry",
            },
        ],
    },
    {
        "name": "Cost Center",
        "label": "Cost Center",
        "module": "Accounts",
        "table_name": "cost_centers",
        "icon": "split-square-horizontal",
        "is_child": False,
        "is_single": False,
        "is_tree": False,
        "is_submittable": False,
        "track_changes": True,
        "track_seen": False,
        "track_views": True,
        "quick_entry": False,
        "description": "Logical cost center for allocation of income and expenses.",
        "fields": [
            {
                "fieldname": "company_id",
                "label": "Company",
                "fieldtype": "Link",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 10,
                "description": None,
                "options": "Company",
                "default": None,
            },
            {
                "fieldname": "branch_id",
                "label": "Branch",
                "fieldtype": "Link",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 20,
                "description": None,
                "options": "Branch",
                "default": None,
            },
            {
                "fieldname": "name",
                "label": "Cost Center Name",
                "fieldtype": "Data",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": True,
                "idx": 30,
                "description": None,
                "options": None,
                "default": None,
            },
            {
                "fieldname": "enabled",
                "label": "Enabled",
                "fieldtype": "Check",
                "reqd": False,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 40,
                "description": None,
                "options": None,
                "default": "1",
            },
        ],
        "links": [],
    },
    {
        "name": "Account",
        "label": "Account",
        "module": "Accounts",
        "table_name": "accounts",
        "icon": "tree-structure",
        "is_child": False,
        "is_single": False,
        "is_tree": True,  # COA tree
        "is_submittable": False,
        "track_changes": True,
        "track_seen": False,
        "track_views": True,
        "quick_entry": False,
        "description": "Chart of Accounts node (group or leaf).",
        "fields": [
            {
                "fieldname": "company_id",
                "label": "Company",
                "fieldtype": "Link",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 10,
                "description": None,
                "options": "Company",
                "default": None,
            },
            {
                "fieldname": "code",
                "label": "Account Code",
                "fieldtype": "Data",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": True,
                "idx": 20,
                "description": None,
                "options": None,
                "default": None,
            },
            {
                "fieldname": "name",
                "label": "Account Name",
                "fieldtype": "Data",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": True,
                "idx": 30,
                "description": None,
                "options": None,
                "default": None,
            },
            {
                "fieldname": "parent_account_id",
                "label": "Parent Account",
                "fieldtype": "Link",
                "reqd": False,
                "read_only": False,
                "hidden": False,
                "in_list_view": False,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 40,
                "description": None,
                "options": "Account",
                "default": None,
            },
            {
                "fieldname": "account_type",
                "label": "Account Type",
                "fieldtype": "Select",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": False,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 50,
                "description": None,
                "options": "Asset\nLiability\nEquity\nIncome\nExpense",
                "default": None,
            },
            {
                "fieldname": "report_type",
                "label": "Report Type",
                "fieldtype": "Select",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": False,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 60,
                "description": None,
                "options": "Balance Sheet\nProfit & Loss",
                "default": None,
            },
            {
                "fieldname": "is_group",
                "label": "Is Group",
                "fieldtype": "Check",
                "reqd": False,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 70,
                "description": None,
                "options": None,
                "default": "0",
            },
            {
                "fieldname": "enabled",
                "label": "Enabled",
                "fieldtype": "Check",
                "reqd": False,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 80,
                "description": None,
                "options": None,
                "default": "1",
            },
        ],
        "links": [
            {
                "link_doctype": "General Ledger Entry",
                "link_fieldname": "account_id",
                "group_label": "GL Entries",
            },
        ],
    },
    {
        "name": "Account Balance",
        "label": "Account Balance",
        "module": "Accounts",
        "table_name": "account_balances",
        "icon": "circle-dollar-sign",
        "is_child": False,
        "is_single": False,
        "is_tree": False,
        "is_submittable": False,
        "track_changes": False,
        "track_seen": False,
        "track_views": False,
        "quick_entry": False,
        "description": "Cached totals for each account.",
        "fields": [
            {
                "fieldname": "account_id",
                "label": "Account",
                "fieldtype": "Link",
                "reqd": True,
                "read_only": True,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 10,
                "description": None,
                "options": "Account",
                "default": None,
            },
            {
                "fieldname": "total_debit",
                "label": "Total Debit",
                "fieldtype": "Currency",
                "reqd": False,
                "read_only": True,
                "hidden": False,
                "in_list_view": False,
                "in_filter": False,
                "in_quick_entry": False,
                "idx": 20,
                "description": None,
                "options": None,
                "default": None,
            },
            {
                "fieldname": "total_credit",
                "label": "Total Credit",
                "fieldtype": "Currency",
                "reqd": False,
                "read_only": True,
                "hidden": False,
                "in_list_view": False,
                "in_filter": False,
                "in_quick_entry": False,
                "idx": 30,
                "description": None,
                "options": None,
                "default": None,
            },
            {
                "fieldname": "current_balance",
                "label": "Current Balance",
                "fieldtype": "Currency",
                "reqd": False,
                "read_only": True,
                "hidden": False,
                "in_list_view": True,
                "in_filter": False,
                "in_quick_entry": False,
                "idx": 40,
                "description": None,
                "options": None,
                "default": None,
            },
        ],
        "links": [],
    },
    {
        "name": "Party Account Balance",
        "label": "Party Account Balance",
        "module": "Accounts",
        "table_name": "party_account_balances",
        "icon": "users-round",
        "is_child": False,
        "is_single": False,
        "is_tree": False,
        "is_submittable": False,
        "track_changes": False,
        "track_seen": False,
        "track_views": False,
        "quick_entry": False,
        "description": "Per-party balance for AR/AP (customer, supplier, etc.).",
        "fields": [
            {
                "fieldname": "account_id",
                "label": "Account",
                "fieldtype": "Link",
                "reqd": True,
                "read_only": True,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 10,
                "description": None,
                "options": "Account",
                "default": None,
            },
            {
                "fieldname": "party_id",
                "label": "Party ID",
                "fieldtype": "Int",
                "reqd": True,
                "read_only": True,
                "hidden": False,
                "in_list_view": True,
                "in_filter": False,
                "in_quick_entry": False,
                "idx": 20,
                "description": "ID of the party in Party / Customer / Supplier table.",
                "options": None,
                "default": None,
            },
            {
                "fieldname": "party_type",
                "label": "Party Type",
                "fieldtype": "Select",
                "reqd": True,
                "read_only": True,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 30,
                "description": None,
                "options": "Customer\nSupplier\nEmployee\nShareholder\nOther",
                "default": None,
            },
            {
                "fieldname": "current_balance",
                "label": "Current Balance",
                "fieldtype": "Currency",
                "reqd": False,
                "read_only": True,
                "hidden": False,
                "in_list_view": True,
                "in_filter": False,
                "in_quick_entry": False,
                "idx": 40,
                "description": None,
                "options": None,
                "default": None,
            },
        ],
        "links": [],
    },
    {
        "name": "Journal Entry",
        "label": "Journal Entry",
        "module": "Accounts",
        "table_name": "journal_entries",
        "icon": "notebook-pen",
        "is_child": False,
        "is_single": False,
        "is_tree": False,
        "is_submittable": True,
        "track_changes": True,
        "track_seen": False,
        "track_views": True,
        "quick_entry": False,
        "description": "General ledger journal entry that posts debits and credits.",
        "fields": [
            {
                "fieldname": "company_id",
                "label": "Company",
                "fieldtype": "Link",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 10,
                "description": None,
                "options": "Company",
                "default": None,
            },
            {
                "fieldname": "branch_id",
                "label": "Branch",
                "fieldtype": "Link",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 20,
                "description": None,
                "options": "Branch",
                "default": None,
            },
            {
                "fieldname": "fiscal_year_id",
                "label": "Fiscal Year",
                "fieldtype": "Link",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": False,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 30,
                "description": None,
                "options": "Fiscal Year",
                "default": None,
            },
            {
                "fieldname": "code",
                "label": "Journal Entry Code",
                "fieldtype": "Data",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": False,
                "in_quick_entry": False,
                "idx": 40,
                "description": None,
                "options": None,
                "default": None,
            },
            {
                "fieldname": "posting_date",
                "label": "Posting Date",
                "fieldtype": "Date",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 50,
                "description": None,
                "options": None,
                "default": None,
            },
            {
                "fieldname": "doc_status",
                "label": "Status",
                "fieldtype": "Select",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 60,
                "description": None,
                "options": "Draft\nSubmitted\nCancelled",
                "default": "Draft",
            },
            {
                "fieldname": "entry_type",
                "label": "Entry Type",
                "fieldtype": "Select",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": False,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 70,
                "description": None,
                "options": "General\nOpening\nAdjustment\nAuto\nAuto Reversal\nClosing",
                "default": "General",
            },
            {
                "fieldname": "total_debit",
                "label": "Total Debit",
                "fieldtype": "Currency",
                "reqd": False,
                "read_only": True,
                "hidden": False,
                "in_list_view": False,
                "in_filter": False,
                "in_quick_entry": False,
                "idx": 80,
                "description": None,
                "options": None,
                "default": None,
            },
            {
                "fieldname": "total_credit",
                "label": "Total Credit",
                "fieldtype": "Currency",
                "reqd": False,
                "read_only": True,
                "hidden": False,
                "in_list_view": False,
                "in_filter": False,
                "in_quick_entry": False,
                "idx": 90,
                "description": None,
                "options": None,
                "default": None,
            },
        ],
        "links": [
            {
                "link_doctype": "Journal Entry Item",
                "link_fieldname": "journal_entry_id",
                "group_label": "Items",
            },
            {
                "link_doctype": "General Ledger Entry",
                "link_fieldname": "journal_entry_id",
                "group_label": "GL Entries",
            },
        ],
    },
    {
        "name": "Journal Entry Item",
        "label": "Journal Entry Item",
        "module": "Accounts",
        "table_name": "journal_entry_items",
        "icon": "list",
        "is_child": True,
        "is_single": False,
        "is_tree": False,
        "is_submittable": False,
        "track_changes": True,
        "track_seen": False,
        "track_views": False,
        "quick_entry": False,
        "description": "Line items inside a Journal Entry.",
        "fields": [
            {
                "fieldname": "journal_entry_id",
                "label": "Journal Entry",
                "fieldtype": "Link",
                "reqd": True,
                "read_only": True,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 10,
                "description": None,
                "options": "Journal Entry",
                "default": None,
            },
            {
                "fieldname": "account_id",
                "label": "Account",
                "fieldtype": "Link",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": True,
                "idx": 20,
                "description": None,
                "options": "Account",
                "default": None,
            },
            {
                "fieldname": "cost_center_id",
                "label": "Cost Center",
                "fieldtype": "Link",
                "reqd": False,
                "read_only": False,
                "hidden": False,
                "in_list_view": False,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 30,
                "description": None,
                "options": "Cost Center",
                "default": None,
            },
            {
                "fieldname": "debit",
                "label": "Debit",
                "fieldtype": "Currency",
                "reqd": False,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": False,
                "in_quick_entry": False,
                "idx": 40,
                "description": None,
                "options": None,
                "default": None,
            },
            {
                "fieldname": "credit",
                "label": "Credit",
                "fieldtype": "Currency",
                "reqd": False,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": False,
                "in_quick_entry": False,
                "idx": 50,
                "description": None,
                "options": None,
                "default": None,
            },
        ],
        "links": [],
    },
    {
        "name": "General Ledger Entry",
        "label": "General Ledger Entry",
        "module": "Accounts",
        "table_name": "general_ledger_entries",
        "icon": "rows-3",
        "is_child": False,
        "is_single": False,
        "is_tree": False,
        "is_submittable": False,
        "track_changes": True,
        "track_seen": False,
        "track_views": True,
        "quick_entry": False,
        "description": "Final GL line produced from journal entries.",
        "fields": [
            {
                "fieldname": "company_id",
                "label": "Company",
                "fieldtype": "Link",
                "reqd": True,
                "read_only": True,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 10,
                "description": None,
                "options": "Company",
                "default": None,
            },
            {
                "fieldname": "branch_id",
                "label": "Branch",
                "fieldtype": "Link",
                "reqd": True,
                "read_only": True,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 20,
                "description": None,
                "options": "Branch",
                "default": None,
            },
            {
                "fieldname": "account_id",
                "label": "Account",
                "fieldtype": "Link",
                "reqd": True,
                "read_only": True,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 30,
                "description": None,
                "options": "Account",
                "default": None,
            },
            {
                "fieldname": "posting_date",
                "label": "Posting Date",
                "fieldtype": "Date",
                "reqd": True,
                "read_only": True,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 40,
                "description": None,
                "options": None,
                "default": None,
            },
            {
                "fieldname": "debit",
                "label": "Debit",
                "fieldtype": "Currency",
                "reqd": False,
                "read_only": True,
                "hidden": False,
                "in_list_view": False,
                "in_filter": False,
                "in_quick_entry": False,
                "idx": 50,
                "description": None,
                "options": None,
                "default": None,
            },
            {
                "fieldname": "credit",
                "label": "Credit",
                "fieldtype": "Currency",
                "reqd": False,
                "read_only": True,
                "hidden": False,
                "in_list_view": False,
                "in_filter": False,
                "in_quick_entry": False,
                "idx": 60,
                "description": None,
                "options": None,
                "default": None,
            },
        ],
        "links": [],
    },

    # GL RULES
    {
        "name": "GL Entry Template",
        "label": "GL Entry Template",
        "module": "Accounts",
        "table_name": "gl_entry_templates",
        "icon": "wand-2",
        "is_child": False,
        "is_single": False,
        "is_tree": False,
        "is_submittable": False,
        "track_changes": True,
        "track_seen": False,
        "track_views": True,
        "quick_entry": False,
        "description": "Accounting rule template for auto GL postings.",
        "fields": [
            {
                "fieldname": "company_id",
                "label": "Company",
                "fieldtype": "Link",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 10,
                "description": None,
                "options": "Company",
                "default": None,
            },
            {
                "fieldname": "source_doctype_id",
                "label": "Source Document Type",
                "fieldtype": "Link",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 20,
                "description": None,
                "options": "DocumentType",
                "default": None,
            },
            {
                "fieldname": "code",
                "label": "Template Code",
                "fieldtype": "Data",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 30,
                "description": None,
                "options": None,
                "default": None,
            },
            {
                "fieldname": "label",
                "label": "Template Label",
                "fieldtype": "Data",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": False,
                "in_quick_entry": False,
                "idx": 40,
                "description": None,
                "options": None,
                "default": None,
            },
            {
                "fieldname": "is_primary",
                "label": "Primary",
                "fieldtype": "Check",
                "reqd": False,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 50,
                "description": None,
                "options": None,
                "default": "0",
            },
            {
                "fieldname": "is_active",
                "label": "Active",
                "fieldtype": "Check",
                "reqd": False,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 60,
                "description": None,
                "options": None,
                "default": "1",
            },
        ],
        "links": [
            {
                "link_doctype": "GL Template Item",
                "link_fieldname": "template_id",
                "group_label": "Rules",
            }
        ],
    },
    {
        "name": "GL Template Item",
        "label": "GL Template Item",
        "module": "Accounts",
        "table_name": "gl_template_items",
        "icon": "list-checks",
        "is_child": True,
        "is_single": False,
        "is_tree": False,
        "is_submittable": False,
        "track_changes": True,
        "track_seen": False,
        "track_views": False,
        "quick_entry": False,
        "description": "Single debit/credit rule in a GL entry template.",
        "fields": [
            {
                "fieldname": "template_id",
                "label": "Template",
                "fieldtype": "Link",
                "reqd": True,
                "read_only": True,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 10,
                "description": None,
                "options": "GL Entry Template",
                "default": None,
            },
            {
                "fieldname": "sequence",
                "label": "Sequence",
                "fieldtype": "Int",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": False,
                "in_quick_entry": False,
                "idx": 20,
                "description": None,
                "options": None,
                "default": None,
            },
            {
                "fieldname": "effect",
                "label": "Effect",
                "fieldtype": "Select",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": True,
                "in_quick_entry": False,
                "idx": 30,
                "description": None,
                "options": "Debit\nCredit",
                "default": "Debit",
            },
            {
                "fieldname": "amount_source",
                "label": "Amount Source",
                "fieldtype": "Data",
                "reqd": True,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": False,
                "in_quick_entry": False,
                "idx": 40,
                "description": "Key used to extract amount from source document payload.",
                "options": None,
                "default": None,
            },
            {
                "fieldname": "requires_dynamic_account",
                "label": "Dynamic Account",
                "fieldtype": "Check",
                "reqd": False,
                "read_only": False,
                "hidden": False,
                "in_list_view": True,
                "in_filter": False,
                "in_quick_entry": False,
                "idx": 50,
                "description": None,
                "options": None,
                "default": "0",
            },
        ],
        "links": [],
    },
]
