"""added docype-meta models like like DocField and DocListView and DocLink

Revision ID: 017451f2b2d4
Revises: dd03ade3a566
Create Date: 2025-12-10 14:08:03.337066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017451f2b2d4'
down_revision = 'dd03ade3a566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doclinks',
    sa.Column('parent_doctype', sa.String(length=140), nullable=False),
    sa.Column('link_doctype', sa.String(length=140), nullable=False),
    sa.Column('link_fieldname', sa.String(length=140), nullable=True),
    sa.Column('group_label', sa.String(length=140), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doclinks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doclinks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_doclinks_link_doctype'), ['link_doctype'], unique=False)
        batch_op.create_index(batch_op.f('ix_doclinks_parent_doctype'), ['parent_doctype'], unique=False)
        batch_op.create_index(batch_op.f('ix_doclinks_updated_at'), ['updated_at'], unique=False)

    op.create_table('doctypes',
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('label', sa.String(length=140), nullable=False),
    sa.Column('module', sa.String(length=140), nullable=False),
    sa.Column('table_name', sa.String(length=140), nullable=False),
    sa.Column('icon', sa.String(length=140), nullable=True),
    sa.Column('is_child', sa.Boolean(), nullable=False),
    sa.Column('is_single', sa.Boolean(), nullable=False),
    sa.Column('is_tree', sa.Boolean(), nullable=False),
    sa.Column('is_submittable', sa.Boolean(), nullable=False),
    sa.Column('track_changes', sa.Boolean(), nullable=False),
    sa.Column('track_seen', sa.Boolean(), nullable=False),
    sa.Column('track_views', sa.Boolean(), nullable=False),
    sa.Column('quick_entry', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctypes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctypes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctypes_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctypes_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_doctypes_updated_at'), ['updated_at'], unique=False)

    op.create_table('docfields',
    sa.Column('doctype_id', sa.BigInteger(), nullable=False),
    sa.Column('fieldname', sa.String(length=140), nullable=False),
    sa.Column('label', sa.String(length=140), nullable=True),
    sa.Column('fieldtype', sa.String(length=50), nullable=False),
    sa.Column('options', sa.String(length=255), nullable=True),
    sa.Column('default', sa.Text(), nullable=True),
    sa.Column('reqd', sa.Boolean(), nullable=False),
    sa.Column('read_only', sa.Boolean(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('in_list_view', sa.Boolean(), nullable=False),
    sa.Column('in_filter', sa.Boolean(), nullable=False),
    sa.Column('in_quick_entry', sa.Boolean(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctype_id'], ['doctypes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('docfields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_docfields_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_docfields_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_docfields_doctype_id'), ['doctype_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_docfields_updated_at'), ['updated_at'], unique=False)

    op.create_table('doclist_views',
    sa.Column('doctype_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('role_name', sa.String(length=140), nullable=True),
    sa.Column('columns_json', sa.Text(), nullable=True),
    sa.Column('filters_json', sa.Text(), nullable=True),
    sa.Column('sort_by', sa.String(length=140), nullable=True),
    sa.Column('sort_order', sa.String(length=4), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctype_id'], ['doctypes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doclist_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doclist_views_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_doclist_views_doctype_id'), ['doctype_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doclist_views_role_name'), ['role_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_doclist_views_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_doclist_views_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doclist_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doclist_views_user_id'))
        batch_op.drop_index(batch_op.f('ix_doclist_views_updated_at'))
        batch_op.drop_index(batch_op.f('ix_doclist_views_role_name'))
        batch_op.drop_index(batch_op.f('ix_doclist_views_doctype_id'))
        batch_op.drop_index(batch_op.f('ix_doclist_views_created_at'))

    op.drop_table('doclist_views')
    with op.batch_alter_table('docfields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_docfields_updated_at'))
        batch_op.drop_index(batch_op.f('ix_docfields_doctype_id'))
        batch_op.drop_index(batch_op.f('ix_docfields_created_at'))
        batch_op.drop_index(batch_op.f('ix_docfields_company_id'))

    op.drop_table('docfields')
    with op.batch_alter_table('doctypes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctypes_updated_at'))
        batch_op.drop_index(batch_op.f('ix_doctypes_name'))
        batch_op.drop_index(batch_op.f('ix_doctypes_module'))
        batch_op.drop_index(batch_op.f('ix_doctypes_created_at'))

    op.drop_table('doctypes')
    with op.batch_alter_table('doclinks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doclinks_updated_at'))
        batch_op.drop_index(batch_op.f('ix_doclinks_parent_doctype'))
        batch_op.drop_index(batch_op.f('ix_doclinks_link_doctype'))
        batch_op.drop_index(batch_op.f('ix_doclinks_created_at'))

    op.drop_table('doclinks')
    # ### end Alembic commands ###
