"""Add img_key to companies and branches

Revision ID: 03d717565cf9
Revises: d431914a495f
Create Date: 2025-09-02 10:20:32.404272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d717565cf9'
down_revision = 'd431914a495f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_key', sa.String(length=512), nullable=True, comment='Object-storage key/path for the encrypted image'))
        batch_op.create_index(batch_op.f('ix_branches_img_key'), ['img_key'], unique=False)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_key', sa.String(length=512), nullable=True, comment='Object-storage key/path for the encrypted image'))
        batch_op.create_index(batch_op.f('ix_companies_img_key'), ['img_key'], unique=False)

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('is_allowed', sa.Boolean(), nullable=False, server_default=sa.sql.true()))
        batch_op.drop_constraint(batch_op.f('uq_role_permission'), type_='unique')
        batch_op.create_index('ix_role_permissions_company_id', ['company_id'], unique=False)
        batch_op.create_index('ix_role_permissions_role_company', ['role_id', 'company_id'], unique=False)
        batch_op.create_unique_constraint('uq_role_permission_company', ['role_id', 'permission_id', 'company_id'])
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_role_permission_company', type_='unique')
        batch_op.drop_index('ix_role_permissions_role_company')
        batch_op.drop_index('ix_role_permissions_company_id')
        batch_op.create_unique_constraint(batch_op.f('uq_role_permission'), ['role_id', 'permission_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('is_allowed')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_img_key'))
        batch_op.drop_column('img_key')

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branches_img_key'))
        batch_op.drop_column('img_key')

    # ### end Alembic commands ###
