"""Add receipt_id to PurchaseInvoice for GRNI clearance

Revision ID: 05853031cd0f
Revises: c2c29db3baed
Create Date: 2025-10-09 09:40:07.446554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05853031cd0f'
down_revision = 'c2c29db3baed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_id', sa.BigInteger(), nullable=True, comment='The Purchase Receipt this invoice is generated from (clears GRNI).'))
        batch_op.alter_column('payable_account_id',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_comment='The Accounts Payable (Liability) account used for the Credit posting.')
        batch_op.create_index('ix_pin_receipt_id', ['receipt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_invoices_receipt_id'), ['receipt_id'], unique=False)
        batch_op.create_foreign_key(None, 'purchase_receipts', ['receipt_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_purchase_invoices_receipt_id'))
        batch_op.drop_index('ix_pin_receipt_id')
        batch_op.alter_column('payable_account_id',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_comment='The Accounts Payable (Liability) account used for the Credit posting.')
        batch_op.drop_column('receipt_id')

    # ### end Alembic commands ###
