"""chnages studetn enrooment

Revision ID: 128144b616a2
Revises: a16597e314b1
Create Date: 2026-01-29 22:56:19.113546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128144b616a2'
down_revision = 'a16597e314b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edu_promotion_jobs',
    sa.Column('from_program_id', sa.BigInteger(), nullable=False),
    sa.Column('from_academic_year_id', sa.BigInteger(), nullable=False),
    sa.Column('from_academic_term_id', sa.BigInteger(), nullable=False),
    sa.Column('to_program_id', sa.BigInteger(), nullable=False),
    sa.Column('to_academic_year_id', sa.BigInteger(), nullable=False),
    sa.Column('to_academic_term_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=True, comment='If set, tool run is scoped to this branch.'),
    sa.Column('status', sa.Enum('DRAFT', 'RUNNING', 'COMPLETED', 'FAILED', 'PARTIAL', name='edu_promotion_job_status_enum'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_found', sa.Integer(), nullable=False),
    sa.Column('total_success', sa.Integer(), nullable=False),
    sa.Column('total_failed', sa.Integer(), nullable=False),
    sa.Column('total_skipped', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('total_failed >= 0', name='ck_pjob_failed_nonneg'),
    sa.CheckConstraint('total_found >= 0', name='ck_pjob_found_nonneg'),
    sa.CheckConstraint('total_skipped >= 0', name='ck_pjob_skipped_nonneg'),
    sa.CheckConstraint('total_success >= 0', name='ck_pjob_success_nonneg'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_academic_term_id'], ['edu_academic_terms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['from_academic_year_id'], ['edu_academic_years.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['from_program_id'], ['edu_programs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_academic_term_id'], ['edu_academic_terms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_academic_year_id'], ['edu_academic_years.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_program_id'], ['edu_programs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('edu_promotion_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edu_promotion_jobs_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index('ix_edu_promotion_jobs_company_branch', ['company_id', 'branch_id'], unique=False)
        batch_op.create_index('ix_edu_promotion_jobs_company_id', ['company_id'], unique=False)
        batch_op.create_index('ix_edu_promotion_jobs_company_status', ['company_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_promotion_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_promotion_jobs_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_promotion_jobs_from_academic_term_id'), ['from_academic_term_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_promotion_jobs_from_academic_year_id'), ['from_academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_promotion_jobs_from_program_id'), ['from_program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_promotion_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_promotion_jobs_to_academic_term_id'), ['to_academic_term_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_promotion_jobs_to_academic_year_id'), ['to_academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_promotion_jobs_to_program_id'), ['to_program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_promotion_jobs_updated_at'), ['updated_at'], unique=False)

    op.create_table('edu_promotion_job_items',
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('from_program_enrollment_id', sa.BigInteger(), nullable=True),
    sa.Column('to_program_enrollment_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'SKIPPED', 'FAILED', name='edu_promotion_item_status_enum'), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_program_enrollment_id'], ['edu_program_enrollments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['edu_promotion_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_program_enrollment_id'], ['edu_program_enrollments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'student_id', name='uq_pjobitem_job_student')
    )
    with op.batch_alter_table('edu_promotion_job_items', schema=None) as batch_op:
        batch_op.create_index('ix_edu_promotion_job_items_company_id', ['company_id'], unique=False)
        batch_op.create_index('ix_edu_promotion_job_items_company_job', ['company_id', 'job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_promotion_job_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_promotion_job_items_from_program_enrollment_id'), ['from_program_enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_promotion_job_items_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_promotion_job_items_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_promotion_job_items_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_promotion_job_items_to_program_enrollment_id'), ['to_program_enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_promotion_job_items_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('edu_course_enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrollment_code', sa.String(length=100), nullable=False, comment='Human-readable reference for this course enrollment record.'))
        batch_op.alter_column('program_enrollment_id',
               existing_type=sa.BIGINT(),
               comment='If set, this course enrollment belongs to that ProgramEnrollment.',
               existing_comment='Link to program enrollment when this course belongs to that program.',
               existing_nullable=True)
        batch_op.alter_column('academic_year_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('branch_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.drop_index('ix_edu_course_enrollments_status')
        batch_op.drop_index('ix_edu_course_enrollments_student_course')
        batch_op.drop_constraint('uq_course_enrollment_per_year_term', type_='unique')
        batch_op.create_index('ix_edu_course_enrollments_company_branch_year_term', ['company_id', 'branch_id', 'academic_year_id', 'academic_term_id'], unique=False)
        batch_op.create_index('ix_edu_course_enrollments_company_status', ['company_id', 'enrollment_status'], unique=False)
        batch_op.create_index('ix_edu_course_enrollments_company_student', ['company_id', 'student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_course_enrollments_enrollment_code'), ['enrollment_code'], unique=False)
        batch_op.create_index('ix_edu_course_enrollments_program_enrollment', ['company_id', 'program_enrollment_id'], unique=False)
        batch_op.create_unique_constraint('uq_ce_company_branch_student_course_year_term', ['company_id', 'branch_id', 'student_id', 'course_id', 'academic_year_id', 'academic_term_id'])
        batch_op.create_unique_constraint('uq_course_enrollment_code_per_company', ['company_id', 'enrollment_code'])
        batch_op.drop_constraint('edu_course_enrollments_academic_year_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('edu_course_enrollments_branch_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'edu_academic_years', ['academic_year_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('edu_program_enrollments', schema=None) as batch_op:
        batch_op.alter_column('academic_year_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('branch_id',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_comment='Campus/branch where the student attends this program.')

    with op.batch_alter_table('workspace_page_links', schema=None) as batch_op:
        batch_op.create_index('ix_wslink_order', ['order_index'], unique=False)
        batch_op.create_index('ix_wslink_page', ['page_id'], unique=False)
        batch_op.create_index('ix_wslink_section', ['section_id'], unique=False)
        batch_op.create_unique_constraint('uq_ws_page_link', ['section_id', 'page_id', 'target_route'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_page_links', schema=None) as batch_op:
        batch_op.drop_constraint('uq_ws_page_link', type_='unique')
        batch_op.drop_index('ix_wslink_section')
        batch_op.drop_index('ix_wslink_page')
        batch_op.drop_index('ix_wslink_order')

    with op.batch_alter_table('edu_program_enrollments', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_comment='Campus/branch where the student attends this program.')
        batch_op.alter_column('academic_year_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    with op.batch_alter_table('edu_course_enrollments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('edu_course_enrollments_branch_id_fkey', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('edu_course_enrollments_academic_year_id_fkey', 'edu_academic_years', ['academic_year_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_constraint('uq_course_enrollment_code_per_company', type_='unique')
        batch_op.drop_constraint('uq_ce_company_branch_student_course_year_term', type_='unique')
        batch_op.drop_index('ix_edu_course_enrollments_program_enrollment')
        batch_op.drop_index(batch_op.f('ix_edu_course_enrollments_enrollment_code'))
        batch_op.drop_index('ix_edu_course_enrollments_company_student')
        batch_op.drop_index('ix_edu_course_enrollments_company_status')
        batch_op.drop_index('ix_edu_course_enrollments_company_branch_year_term')
        batch_op.create_unique_constraint('uq_course_enrollment_per_year_term', ['student_id', 'course_id', 'academic_year_id', 'academic_term_id'])
        batch_op.create_index('ix_edu_course_enrollments_student_course', ['student_id', 'course_id'], unique=False)
        batch_op.create_index('ix_edu_course_enrollments_status', ['enrollment_status'], unique=False)
        batch_op.alter_column('branch_id',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('academic_year_id',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('program_enrollment_id',
               existing_type=sa.BIGINT(),
               comment='Link to program enrollment when this course belongs to that program.',
               existing_comment='If set, this course enrollment belongs to that ProgramEnrollment.',
               existing_nullable=True)
        batch_op.drop_column('enrollment_code')

    with op.batch_alter_table('edu_promotion_job_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edu_promotion_job_items_updated_at'))
        batch_op.drop_index(batch_op.f('ix_edu_promotion_job_items_to_program_enrollment_id'))
        batch_op.drop_index(batch_op.f('ix_edu_promotion_job_items_student_id'))
        batch_op.drop_index(batch_op.f('ix_edu_promotion_job_items_status'))
        batch_op.drop_index(batch_op.f('ix_edu_promotion_job_items_job_id'))
        batch_op.drop_index(batch_op.f('ix_edu_promotion_job_items_from_program_enrollment_id'))
        batch_op.drop_index(batch_op.f('ix_edu_promotion_job_items_created_at'))
        batch_op.drop_index('ix_edu_promotion_job_items_company_job')
        batch_op.drop_index('ix_edu_promotion_job_items_company_id')

    op.drop_table('edu_promotion_job_items')
    with op.batch_alter_table('edu_promotion_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edu_promotion_jobs_updated_at'))
        batch_op.drop_index(batch_op.f('ix_edu_promotion_jobs_to_program_id'))
        batch_op.drop_index(batch_op.f('ix_edu_promotion_jobs_to_academic_year_id'))
        batch_op.drop_index(batch_op.f('ix_edu_promotion_jobs_to_academic_term_id'))
        batch_op.drop_index(batch_op.f('ix_edu_promotion_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_edu_promotion_jobs_from_program_id'))
        batch_op.drop_index(batch_op.f('ix_edu_promotion_jobs_from_academic_year_id'))
        batch_op.drop_index(batch_op.f('ix_edu_promotion_jobs_from_academic_term_id'))
        batch_op.drop_index(batch_op.f('ix_edu_promotion_jobs_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_edu_promotion_jobs_created_at'))
        batch_op.drop_index('ix_edu_promotion_jobs_company_status')
        batch_op.drop_index('ix_edu_promotion_jobs_company_id')
        batch_op.drop_index('ix_edu_promotion_jobs_company_branch')
        batch_op.drop_index(batch_op.f('ix_edu_promotion_jobs_branch_id'))

    op.drop_table('edu_promotion_jobs')
    # ### end Alembic commands ###
