"""Update warehouse models and add new models

Revision ID: 3257089fb5fa
Revises: 92bc4d9cecfb
Create Date: 2025-09-08 15:12:07.221252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3257089fb5fa'
down_revision = '92bc4d9cecfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bins', schema=None) as batch_op:
        batch_op.alter_column('actual_qty',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               comment=None,
               existing_comment='Total physical stock',
               existing_nullable=False)
        batch_op.alter_column('reserved_qty',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               comment=None,
               existing_comment='Reserved for sales orders',
               existing_nullable=False)
        batch_op.alter_column('ordered_qty',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               comment=None,
               existing_comment='Quantity on purchase orders',
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('bins_company_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('bins_warehouse_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('bins_item_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'warehouses', ['warehouse_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'items', ['item_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('purchase_quotation_items', schema=None) as batch_op:
        batch_op.alter_column('uom_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_group', sa.Boolean(), nullable=False))
        batch_op.alter_column('branch_id',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_warehouse_parent'))
        batch_op.drop_constraint(batch_op.f('uq_warehouse_branch_name'), type_='unique')
        batch_op.create_index(batch_op.f('ix_warehouses_is_group'), ['is_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouses_status'), ['status'], unique=False)
        batch_op.create_index('ix_wh_company_branch', ['company_id', 'branch_id'], unique=False)
        batch_op.create_index('ix_wh_group_active', ['company_id', 'is_group', 'status'], unique=False)
        batch_op.create_index('ix_wh_parent', ['parent_warehouse_id'], unique=False)
        batch_op.create_unique_constraint('uq_wh_company_branch_name', ['company_id', 'branch_id', 'name'])
        batch_op.drop_constraint(batch_op.f('warehouses_branch_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('warehouses_parent_warehouse_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('warehouses_company_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'warehouses', ['parent_warehouse_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('warehouses_company_id_fkey'), 'companies', ['company_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('warehouses_parent_warehouse_id_fkey'), 'warehouses', ['parent_warehouse_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('warehouses_branch_id_fkey'), 'branches', ['branch_id'], ['id'])
        batch_op.drop_constraint('uq_wh_company_branch_name', type_='unique')
        batch_op.drop_index('ix_wh_parent')
        batch_op.drop_index('ix_wh_group_active')
        batch_op.drop_index('ix_wh_company_branch')
        batch_op.drop_index(batch_op.f('ix_warehouses_status'))
        batch_op.drop_index(batch_op.f('ix_warehouses_is_group'))
        batch_op.create_unique_constraint(batch_op.f('uq_warehouse_branch_name'), ['branch_id', 'name'])
        batch_op.create_index(batch_op.f('ix_warehouse_parent'), ['parent_warehouse_id'], unique=False)
        batch_op.alter_column('branch_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.drop_column('is_group')

    with op.batch_alter_table('purchase_quotation_items', schema=None) as batch_op:
        batch_op.alter_column('uom_id',
               existing_type=sa.BIGINT(),
               nullable=False)

    with op.batch_alter_table('bins', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('bins_item_id_fkey'), 'items', ['item_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('bins_warehouse_id_fkey'), 'warehouses', ['warehouse_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('bins_company_id_fkey'), 'companies', ['company_id'], ['id'])
        batch_op.alter_column('ordered_qty',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               comment='Quantity on purchase orders',
               existing_nullable=False)
        batch_op.alter_column('reserved_qty',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               comment='Reserved for sales orders',
               existing_nullable=False)
        batch_op.alter_column('actual_qty',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               comment='Total physical stock',
               existing_nullable=False)

    # ### end Alembic commands ###
