"""fees + sales invoice fee fields + party student

Revision ID: 4af3664738d4
Revises: e22c666e3f00
Create Date: 2025-12-17 19:01:11.874012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4af3664738d4'
down_revision = 'e22c666e3f00'
branch_labels = None
depends_on = None

# ✅ Safe reuse for downgrade (prevents "type docstatusenum already exists" during downgrade)
docstatusenum = postgresql.ENUM(
    'DRAFT', 'SUBMITTED', 'CANCELLED', 'UNPAID', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'RETURNED',
    name='docstatusenum',
    create_type=False,
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edu_fee_structures',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('program_id', sa.BigInteger(), nullable=False),
    sa.Column('student_category_id', sa.BigInteger(), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False, comment='1,2,3... increment when fees change.'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('selling_price_list_id', sa.BigInteger(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('version_no >= 1', name='ck_fee_structure_version_min_1'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['edu_programs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['selling_price_list_id'], ['price_lists.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_category_id'], ['student_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'program_id', 'student_category_id', 'branch_id', 'version_no', name='uq_fee_structure_context_version')
    )
    with op.batch_alter_table('edu_fee_structures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edu_fee_structures_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_structures_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_structures_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_structures_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_structures_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_structures_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_structures_selling_price_list_id'), ['selling_price_list_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_structures_student_category_id'), ['student_category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_structures_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_structures_version_no'), ['version_no'], unique=False)
        batch_op.create_index('ix_fee_structures_company_program', ['company_id', 'program_id'], unique=False)
        batch_op.create_index('ix_fee_structures_company_program_enabled', ['company_id', 'program_id', 'is_enabled'], unique=False)

    op.create_table('edu_fee_categories',
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_fee_category_company_name')
    )
    with op.batch_alter_table('edu_fee_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edu_fee_categories_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_categories_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_categories_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_categories_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_categories_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_categories_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_fee_categories_company_enabled', ['company_id', 'is_enabled'], unique=False)

    op.create_table('edu_fee_schedules',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fee_structure_id', sa.BigInteger(), nullable=False),
    sa.Column('student_group_id', sa.BigInteger(), nullable=False),
    sa.Column('academic_year_id', sa.BigInteger(), nullable=True),
    sa.Column('academic_term_id', sa.BigInteger(), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('posting_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='UI helper; service can refresh from components.'),
    sa.Column('total_students', sa.Integer(), nullable=False),
    sa.Column('total_invoices', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'INVOICE_PENDING', 'INVOICE_CREATED', 'CANCELLED', name='fee_schedule_status_enum'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('total_amount >= 0', name='ck_fee_schedule_total_amount_nonneg'),
    sa.CheckConstraint('total_invoices >= 0', name='ck_fee_schedule_total_invoices_nonneg'),
    sa.CheckConstraint('total_students >= 0', name='ck_fee_schedule_total_students_nonneg'),
    sa.ForeignKeyConstraint(['academic_term_id'], ['edu_academic_terms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['edu_academic_years.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['edu_fee_structures.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_group_id'], ['edu_student_groups.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fee_structure_id', 'student_group_id', 'due_date', name='uq_fee_schedule_one_per_due_date')
    )
    with op.batch_alter_table('edu_fee_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edu_fee_schedules_academic_term_id'), ['academic_term_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_schedules_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_schedules_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_schedules_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_schedules_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_schedules_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_schedules_fee_structure_id'), ['fee_structure_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_schedules_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_schedules_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_schedules_posting_date'), ['posting_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_schedules_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_schedules_student_group_id'), ['student_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_schedules_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_fee_schedules_company_due', ['company_id', 'due_date'], unique=False)
        batch_op.create_index('ix_fee_schedules_company_enabled', ['company_id', 'is_enabled'], unique=False)
        batch_op.create_index('ix_fee_schedules_company_group_due', ['company_id', 'student_group_id', 'due_date'], unique=False)
        batch_op.create_index('ix_fee_schedules_company_status', ['company_id', 'status'], unique=False)

    op.create_table('edu_fee_schedule_components',
    sa.Column('fee_schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('fee_category_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('(sequence_no IS NULL) OR (sequence_no >= 0)', name='ck_fee_sched_comp_seq_nonneg'),
    sa.CheckConstraint('amount >= 0', name='ck_fee_sched_comp_amount_nonneg'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fee_category_id'], ['edu_fee_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fee_schedule_id'], ['edu_fee_schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fee_schedule_id', 'fee_category_id', name='uq_fee_schedule_one_row_per_category')
    )
    with op.batch_alter_table('edu_fee_schedule_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edu_fee_schedule_components_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_schedule_components_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_schedule_components_fee_category_id'), ['fee_category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_schedule_components_fee_schedule_id'), ['fee_schedule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_schedule_components_is_optional'), ['is_optional'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_schedule_components_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_schedule_components_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_fee_schedule_components_schedule_seq', ['fee_schedule_id', 'sequence_no'], unique=False)

    op.create_table('edu_fee_structure_components',
    sa.Column('fee_structure_id', sa.BigInteger(), nullable=False),
    sa.Column('fee_category_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('(sequence_no IS NULL) OR (sequence_no >= 0)', name='ck_fee_struct_comp_seq_nonneg'),
    sa.CheckConstraint('amount >= 0', name='ck_fee_struct_comp_amount_nonneg'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fee_category_id'], ['edu_fee_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['edu_fee_structures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fee_structure_id', 'fee_category_id', name='uq_fee_structure_one_row_per_category')
    )
    with op.batch_alter_table('edu_fee_structure_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edu_fee_structure_components_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_structure_components_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_structure_components_fee_category_id'), ['fee_category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_structure_components_fee_structure_id'), ['fee_structure_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_structure_components_is_optional'), ['is_optional'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_structure_components_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_fee_structure_components_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_fee_structure_components_structure_seq', ['fee_structure_id', 'sequence_no'], unique=False)

    op.create_table('edu_student_fee_adjustments',
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('program_id', sa.BigInteger(), nullable=False),
    sa.Column('fee_category_id', sa.BigInteger(), nullable=False),
    sa.Column('adjustment_type', sa.Enum('DISCOUNT', 'SCHOLARSHIP', 'WAIVER', 'OVERRIDE', 'OTHER', name='student_fee_adjustment_type_enum'), nullable=False, comment='Why this adjustment exists (Scholarship/Waiver/Discount/Override).'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('override_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_upto', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('(discount_amount IS NULL) OR (discount_amount >= 0)', name='ck_sfa_disc_amt_nonneg'),
    sa.CheckConstraint('(discount_percent IS NULL) OR (discount_percent >= 0 AND discount_percent <= 100)', name='ck_sfa_disc_pct_0_100'),
    sa.CheckConstraint('(override_amount IS NULL) OR (override_amount >= 0)', name='ck_sfa_override_amt_nonneg'),
    sa.CheckConstraint('(valid_upto IS NULL) OR (valid_from IS NULL) OR (valid_upto >= valid_from)', name='ck_sfa_valid_range'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fee_category_id'], ['edu_fee_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['program_id'], ['edu_programs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'student_id', 'program_id', 'fee_category_id', name='uq_student_fee_adjustment_once')
    )
    with op.batch_alter_table('edu_student_fee_adjustments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edu_student_fee_adjustments_adjustment_type'), ['adjustment_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_student_fee_adjustments_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_student_fee_adjustments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_student_fee_adjustments_fee_category_id'), ['fee_category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_student_fee_adjustments_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_student_fee_adjustments_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_student_fee_adjustments_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_student_fee_adjustments_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_sfa_company_enabled', ['company_id', 'is_enabled'], unique=False)
        batch_op.create_index('ix_sfa_company_type', ['company_id', 'adjustment_type'], unique=False)
        batch_op.create_index('ix_sfa_lookup', ['company_id', 'student_id', 'program_id', 'fee_category_id'], unique=False)

    # ✅✅✅ FIX: DROP FK/COLUMN FROM sales_invoice_items BEFORE dropping sales_delivery_note_items
    with op.batch_alter_table('sales_invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee_category_id', sa.BigInteger(), nullable=True, comment='Filled when this line came from Fee Schedule/Structure.'))
        batch_op.add_column(sa.Column('company_id', sa.BigInteger(), nullable=False))
        batch_op.drop_index('ix_sales_invoice_items_delivery_note_item_id')
        batch_op.drop_index('ix_sii_income_account')
        batch_op.create_index(batch_op.f('ix_sales_invoice_items_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoice_items_fee_category_id'), ['fee_category_id'], unique=False)
        batch_op.create_index('ix_sii_company_invoice', ['company_id', 'invoice_id'], unique=False)
        batch_op.create_index('ix_sii_fee_category', ['fee_category_id'], unique=False)

        # this one is the blocker for DROP TABLE sales_delivery_note_items
        batch_op.drop_constraint('sales_invoice_items_delivery_note_item_id_fkey', type_='foreignkey')

        batch_op.drop_constraint('sales_invoice_items_uom_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('sales_invoice_items_cost_center_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('sales_invoice_items_return_against_item_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('sales_invoice_items_income_account_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('sales_invoice_items_warehouse_id_fkey', type_='foreignkey')

        batch_op.create_foreign_key(None, 'sales_invoice_items', ['return_against_item_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'units_of_measure', ['uom_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'warehouses', ['warehouse_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'edu_fee_categories', ['fee_category_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'accounts', ['income_account_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'cost_centers', ['cost_center_id'], ['id'], ondelete='SET NULL')

        batch_op.drop_column('delivery_note_item_id')

    # Now safe to drop delivery note tables
    with op.batch_alter_table('sales_delivery_note_items', schema=None) as batch_op:
        batch_op.drop_index('ix_sales_delivery_note_items_created_at')
        batch_op.drop_index('ix_sales_delivery_note_items_delivery_note_id')
        batch_op.drop_index('ix_sales_delivery_note_items_item_id')
        batch_op.drop_index('ix_sales_delivery_note_items_return_against_item_id')
        batch_op.drop_index('ix_sales_delivery_note_items_uom_id')
        batch_op.drop_index('ix_sales_delivery_note_items_updated_at')
        batch_op.drop_index('ix_sales_delivery_note_items_warehouse_id')
        batch_op.drop_index('ix_sdni_item')
        batch_op.drop_index('ix_sdni_return_against')
        batch_op.drop_index('ix_sdni_warehouse')

    op.drop_table('sales_delivery_note_items')

    with op.batch_alter_table('sales_delivery_notes', schema=None) as batch_op:
        batch_op.drop_index('ix_sales_delivery_notes_branch_id')
        batch_op.drop_index('ix_sales_delivery_notes_code')
        batch_op.drop_index('ix_sales_delivery_notes_company_id')
        batch_op.drop_index('ix_sales_delivery_notes_created_at')
        batch_op.drop_index('ix_sales_delivery_notes_created_by_id')
        batch_op.drop_index('ix_sales_delivery_notes_customer_id')
        batch_op.drop_index('ix_sales_delivery_notes_doc_status')
        batch_op.drop_index('ix_sales_delivery_notes_is_return')
        batch_op.drop_index('ix_sales_delivery_notes_posting_date')
        batch_op.drop_index('ix_sales_delivery_notes_return_against_id')
        batch_op.drop_index('ix_sales_delivery_notes_updated_at')
        batch_op.drop_index('ix_sdn_company_branch_status')
        batch_op.drop_index('ix_sdn_company_customer')
        batch_op.drop_index('ix_sdn_company_posting_date')
        batch_op.drop_index('ix_sdn_is_return')

    op.drop_table('sales_delivery_notes')

    # (rest of your upgrade remains exactly the same)
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_id', sa.BigInteger(), nullable=True, comment='Optional default warehouse for this invoice; item rows may inherit via service layer.'))
        batch_op.add_column(sa.Column('is_fee_invoice', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('student_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('program_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('program_enrollment_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('fee_schedule_id', sa.BigInteger(), nullable=True))
        batch_op.alter_column('update_stock',
               existing_type=sa.BOOLEAN(),
               comment='If true, service layer will affect stock/GL accordingly.',
               existing_nullable=False)
        batch_op.drop_index('ix_sin_cash_bank_account')
        batch_op.drop_index('ix_sin_company_update_stock')
        batch_op.drop_index('ix_sin_is_return')
        batch_op.drop_index('ix_sin_mode_of_payment')
        batch_op.drop_index('ix_sin_vat_account')
        batch_op.drop_constraint('uq_sin_branch_code', type_='unique')
        batch_op.create_index(batch_op.f('ix_sales_invoices_fee_schedule_id'), ['fee_schedule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_is_fee_invoice'), ['is_fee_invoice'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_program_enrollment_id'), ['program_enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_warehouse_id'), ['warehouse_id'], unique=False)
        batch_op.create_index('ix_sin_company_due_date', ['company_id', 'due_date'], unique=False)
        batch_op.create_index('ix_sin_company_fee_schedule', ['company_id', 'fee_schedule_id'], unique=False)
        batch_op.create_index('ix_sin_company_program', ['company_id', 'program_id', 'posting_date'], unique=False)
        batch_op.create_index('ix_sin_company_student', ['company_id', 'student_id', 'posting_date'], unique=False)
        batch_op.create_unique_constraint('uq_sin_company_branch_code', ['company_id', 'branch_id', 'code'])
        batch_op.create_unique_constraint('uq_sin_fee_schedule_student_once', ['company_id', 'fee_schedule_id', 'student_id'])
        batch_op.drop_constraint('sales_invoices_return_against_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('sales_invoices_vat_account_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('sales_invoices_created_by_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('sales_invoices_mode_of_payment_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('sales_invoices_customer_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('sales_invoices_debit_to_account_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('sales_invoices_cash_bank_account_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('sales_invoices_company_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('sales_invoices_branch_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'edu_programs', ['program_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'warehouses', ['warehouse_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'parties', ['customer_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'accounts', ['vat_account_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'edu_fee_schedules', ['fee_schedule_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'accounts', ['cash_bank_account_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'modes_of_payment', ['mode_of_payment_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'edu_program_enrollments', ['program_enrollment_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'sales_invoices', ['return_against_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'accounts', ['debit_to_account_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('sales_quotation_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.BigInteger(), nullable=False))
        batch_op.create_index(batch_op.f('ix_sales_quotation_items_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_sqi_company_quotation', ['company_id', 'quotation_id'], unique=False)
        batch_op.drop_constraint('sales_quotation_items_uom_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'units_of_measure', ['uom_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('sales_quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selling_price_list_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('student_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('program_id', sa.BigInteger(), nullable=True))
        batch_op.drop_constraint('uq_sq_branch_code', type_='unique')
        batch_op.create_index(batch_op.f('ix_sales_quotations_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_quotations_selling_price_list_id'), ['selling_price_list_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_quotations_student_id'), ['student_id'], unique=False)
        batch_op.create_index('ix_sq_company_student', ['company_id', 'student_id'], unique=False)
        batch_op.create_unique_constraint('uq_sq_company_branch_code', ['company_id', 'branch_id', 'code'])
        batch_op.drop_constraint('sales_quotations_branch_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('sales_quotations_created_by_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('sales_quotations_company_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('sales_quotations_customer_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'edu_programs', ['program_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'parties', ['customer_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'price_lists', ['selling_price_list_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # ✅ Ensure docstatusenum exists (safe)
    bind = op.get_bind()
    docstatusenum.create(bind, checkfirst=True)

    with op.batch_alter_table('sales_quotations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('sales_quotations_customer_id_fkey', 'parties', ['customer_id'], ['id'])
        batch_op.create_foreign_key('sales_quotations_company_id_fkey', 'companies', ['company_id'], ['id'])
        batch_op.create_foreign_key('sales_quotations_created_by_id_fkey', 'users', ['created_by_id'], ['id'])
        batch_op.create_foreign_key('sales_quotations_branch_id_fkey', 'branches', ['branch_id'], ['id'])
        batch_op.drop_constraint('uq_sq_company_branch_code', type_='unique')
        batch_op.drop_index('ix_sq_company_student')
        batch_op.drop_index(batch_op.f('ix_sales_quotations_student_id'))
        batch_op.drop_index(batch_op.f('ix_sales_quotations_selling_price_list_id'))
        batch_op.drop_index(batch_op.f('ix_sales_quotations_program_id'))
        batch_op.create_unique_constraint('uq_sq_branch_code', ['company_id', 'branch_id', 'code'])
        batch_op.drop_column('program_id')
        batch_op.drop_column('student_id')
        batch_op.drop_column('selling_price_list_id')

    with op.batch_alter_table('sales_quotation_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('sales_quotation_items_uom_id_fkey', 'units_of_measure', ['uom_id'], ['id'])
        batch_op.drop_index('ix_sqi_company_quotation')
        batch_op.drop_index(batch_op.f('ix_sales_quotation_items_company_id'))
        batch_op.drop_column('company_id')

    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('sales_invoices_branch_id_fkey', 'branches', ['branch_id'], ['id'])
        batch_op.create_foreign_key('sales_invoices_company_id_fkey', 'companies', ['company_id'], ['id'])
        batch_op.create_foreign_key('sales_invoices_cash_bank_account_id_fkey', 'accounts', ['cash_bank_account_id'], ['id'])
        batch_op.create_foreign_key('sales_invoices_debit_to_account_id_fkey', 'accounts', ['debit_to_account_id'], ['id'])
        batch_op.create_foreign_key('sales_invoices_customer_id_fkey', 'parties', ['customer_id'], ['id'])
        batch_op.create_foreign_key('sales_invoices_mode_of_payment_id_fkey', 'modes_of_payment', ['mode_of_payment_id'], ['id'])
        batch_op.create_foreign_key('sales_invoices_created_by_id_fkey', 'users', ['created_by_id'], ['id'])
        batch_op.create_foreign_key('sales_invoices_vat_account_id_fkey', 'accounts', ['vat_account_id'], ['id'])
        batch_op.create_foreign_key('sales_invoices_return_against_id_fkey', 'sales_invoices', ['return_against_id'], ['id'])
        batch_op.drop_constraint('uq_sin_fee_schedule_student_once', type_='unique')
        batch_op.drop_constraint('uq_sin_company_branch_code', type_='unique')
        batch_op.drop_index('ix_sin_company_student')
        batch_op.drop_index('ix_sin_company_program')
        batch_op.drop_index('ix_sin_company_fee_schedule')
        batch_op.drop_index('ix_sin_company_due_date')
        batch_op.drop_index(batch_op.f('ix_sales_invoices_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_sales_invoices_student_id'))
        batch_op.drop_index(batch_op.f('ix_sales_invoices_program_id'))
        batch_op.drop_index(batch_op.f('ix_sales_invoices_program_enrollment_id'))
        batch_op.drop_index(batch_op.f('ix_sales_invoices_is_fee_invoice'))
        batch_op.drop_index(batch_op.f('ix_sales_invoices_fee_schedule_id'))
        batch_op.create_unique_constraint('uq_sin_branch_code', ['company_id', 'branch_id', 'code'])
        batch_op.create_index('ix_sin_vat_account', ['vat_account_id'], unique=False)
        batch_op.create_index('ix_sin_mode_of_payment', ['mode_of_payment_id'], unique=False)
        batch_op.create_index('ix_sin_is_return', ['is_return'], unique=False)
        batch_op.create_index('ix_sin_company_update_stock', ['company_id', 'update_stock'], unique=False)
        batch_op.create_index('ix_sin_cash_bank_account', ['cash_bank_account_id'], unique=False)
        batch_op.alter_column('update_stock',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='If true, service layer will affect stock/GL accordingly.',
               existing_nullable=False)
        batch_op.drop_column('fee_schedule_id')
        batch_op.drop_column('program_enrollment_id')
        batch_op.drop_column('program_id')
        batch_op.drop_column('student_id')
        batch_op.drop_column('is_fee_invoice')
        batch_op.drop_column('warehouse_id')

    with op.batch_alter_table('sales_invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_note_item_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('sales_invoice_items_warehouse_id_fkey', 'warehouses', ['warehouse_id'], ['id'])
        batch_op.create_foreign_key('sales_invoice_items_income_account_id_fkey', 'accounts', ['income_account_id'], ['id'])
        batch_op.create_foreign_key('sales_invoice_items_return_against_item_id_fkey', 'sales_invoice_items', ['return_against_item_id'], ['id'])
        batch_op.create_foreign_key('sales_invoice_items_cost_center_id_fkey', 'cost_centers', ['cost_center_id'], ['id'])
        batch_op.create_foreign_key('sales_invoice_items_uom_id_fkey', 'units_of_measure', ['uom_id'], ['id'])
        batch_op.create_foreign_key('sales_invoice_items_delivery_note_item_id_fkey', 'sales_delivery_note_items', ['delivery_note_item_id'], ['id'])
        batch_op.drop_index('ix_sii_fee_category')
        batch_op.drop_index('ix_sii_company_invoice')
        batch_op.drop_index(batch_op.f('ix_sales_invoice_items_fee_category_id'))
        batch_op.drop_index(batch_op.f('ix_sales_invoice_items_company_id'))
        batch_op.create_index('ix_sii_income_account', ['income_account_id'], unique=False)
        batch_op.create_index('ix_sales_invoice_items_delivery_note_item_id', ['delivery_note_item_id'], unique=False)
        batch_op.drop_column('company_id')
        batch_op.drop_column('fee_category_id')

    op.create_table('sales_delivery_notes',
    sa.Column('company_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('branch_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('posting_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('doc_status', docstatusenum, autoincrement=False, nullable=False),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('sales_delivery_notes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('return_against_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('is_return', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='sales_delivery_notes_branch_id_fkey'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='sales_delivery_notes_company_id_fkey'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='sales_delivery_notes_created_by_id_fkey'),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], name='sales_delivery_notes_customer_id_fkey'),
    sa.ForeignKeyConstraint(['return_against_id'], ['sales_delivery_notes.id'], name='sales_delivery_notes_return_against_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sales_delivery_notes_pkey'),
    sa.UniqueConstraint('company_id', 'branch_id', 'code', name='uq_sdn_branch_code'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('sales_delivery_notes', schema=None) as batch_op:
        batch_op.create_index('ix_sdn_is_return', ['is_return'], unique=False)
        batch_op.create_index('ix_sdn_company_posting_date', ['company_id', 'posting_date'], unique=False)
        batch_op.create_index('ix_sdn_company_customer', ['company_id', 'customer_id'], unique=False)
        batch_op.create_index('ix_sdn_company_branch_status', ['company_id', 'branch_id', 'doc_status'], unique=False)
        batch_op.create_index('ix_sales_delivery_notes_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('ix_sales_delivery_notes_return_against_id', ['return_against_id'], unique=False)
        batch_op.create_index('ix_sales_delivery_notes_posting_date', ['posting_date'], unique=False)
        batch_op.create_index('ix_sales_delivery_notes_is_return', ['is_return'], unique=False)
        batch_op.create_index('ix_sales_delivery_notes_doc_status', ['doc_status'], unique=False)
        batch_op.create_index('ix_sales_delivery_notes_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('ix_sales_delivery_notes_created_by_id', ['created_by_id'], unique=False)
        batch_op.create_index('ix_sales_delivery_notes_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_sales_delivery_notes_company_id', ['company_id'], unique=False)
        batch_op.create_index('ix_sales_delivery_notes_code', ['code'], unique=False)
        batch_op.create_index('ix_sales_delivery_notes_branch_id', ['branch_id'], unique=False)

    op.create_table('sales_delivery_note_items',
    sa.Column('delivery_note_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('uom_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('delivered_qty', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=14, scale=4), sa.Computed('\nCASE\n    WHEN (unit_price IS NULL) THEN NULL::numeric\n    ELSE (delivered_qty * unit_price)\nEND', persisted=True), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('return_against_item_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('warehouse_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.CheckConstraint('delivered_qty > 0::numeric', name='ck_sdni_delivered_pos'),
    sa.ForeignKeyConstraint(['delivery_note_id'], ['sales_delivery_notes.id'], name='sales_delivery_note_items_delivery_note_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='sales_delivery_note_items_item_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['return_against_item_id'], ['sales_delivery_note_items.id'], name='sales_delivery_note_items_return_against_item_id_fkey'),
    sa.ForeignKeyConstraint(['uom_id'], ['units_of_measure.id'], name='sales_delivery_note_items_uom_id_fkey'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name='sales_delivery_note_items_warehouse_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sales_delivery_note_items_pkey')
    )
    with op.batch_alter_table('sales_delivery_note_items', schema=None) as batch_op:
        batch_op.create_index('ix_sdni_warehouse', ['warehouse_id'], unique=False)
        batch_op.create_index('ix_sdni_return_against', ['return_against_item_id'], unique=False)
        batch_op.create_index('ix_sdni_item', ['item_id'], unique=False)
        batch_op.create_index('ix_sales_delivery_note_items_warehouse_id', ['warehouse_id'], unique=False)
        batch_op.create_index('ix_sales_delivery_note_items_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('ix_sales_delivery_note_items_uom_id', ['uom_id'], unique=False)
        batch_op.create_index('ix_sales_delivery_note_items_return_against_item_id', ['return_against_item_id'], unique=False)
        batch_op.create_index('ix_sales_delivery_note_items_item_id', ['item_id'], unique=False)
        batch_op.create_index('ix_sales_delivery_note_items_delivery_note_id', ['delivery_note_id'], unique=False)
        batch_op.create_index('ix_sales_delivery_note_items_created_at', ['created_at'], unique=False)




    with op.batch_alter_table('edu_student_fee_adjustments', schema=None) as batch_op:
        batch_op.drop_index('ix_sfa_lookup')
        batch_op.drop_index('ix_sfa_company_type')
        batch_op.drop_index('ix_sfa_company_enabled')
        batch_op.drop_index(batch_op.f('ix_edu_student_fee_adjustments_updated_at'))
        batch_op.drop_index(batch_op.f('ix_edu_student_fee_adjustments_student_id'))
        batch_op.drop_index(batch_op.f('ix_edu_student_fee_adjustments_program_id'))
        batch_op.drop_index(batch_op.f('ix_edu_student_fee_adjustments_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_edu_student_fee_adjustments_fee_category_id'))
        batch_op.drop_index(batch_op.f('ix_edu_student_fee_adjustments_created_at'))
        batch_op.drop_index(batch_op.f('ix_edu_student_fee_adjustments_company_id'))
        batch_op.drop_index(batch_op.f('ix_edu_student_fee_adjustments_adjustment_type'))

    op.drop_table('edu_student_fee_adjustments')
    with op.batch_alter_table('edu_fee_structure_components', schema=None) as batch_op:
        batch_op.drop_index('ix_fee_structure_components_structure_seq')
        batch_op.drop_index(batch_op.f('ix_edu_fee_structure_components_updated_at'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_structure_components_item_id'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_structure_components_is_optional'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_structure_components_fee_structure_id'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_structure_components_fee_category_id'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_structure_components_created_at'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_structure_components_company_id'))

    op.drop_table('edu_fee_structure_components')
    with op.batch_alter_table('edu_fee_schedule_components', schema=None) as batch_op:
        batch_op.drop_index('ix_fee_schedule_components_schedule_seq')
        batch_op.drop_index(batch_op.f('ix_edu_fee_schedule_components_updated_at'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_schedule_components_item_id'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_schedule_components_is_optional'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_schedule_components_fee_schedule_id'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_schedule_components_fee_category_id'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_schedule_components_created_at'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_schedule_components_company_id'))

    op.drop_table('edu_fee_schedule_components')
    with op.batch_alter_table('edu_fee_schedules', schema=None) as batch_op:
        batch_op.drop_index('ix_fee_schedules_company_status')
        batch_op.drop_index('ix_fee_schedules_company_group_due')
        batch_op.drop_index('ix_fee_schedules_company_enabled')
        batch_op.drop_index('ix_fee_schedules_company_due')
        batch_op.drop_index(batch_op.f('ix_edu_fee_schedules_updated_at'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_schedules_student_group_id'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_schedules_status'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_schedules_posting_date'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_schedules_name'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_schedules_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_schedules_fee_structure_id'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_schedules_due_date'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_schedules_created_at'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_schedules_company_id'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_schedules_branch_id'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_schedules_academic_year_id'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_schedules_academic_term_id'))

    op.drop_table('edu_fee_schedules')
    with op.batch_alter_table('edu_fee_categories', schema=None) as batch_op:
        batch_op.drop_index('ix_fee_categories_company_enabled')
        batch_op.drop_index(batch_op.f('ix_edu_fee_categories_updated_at'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_categories_name'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_categories_item_id'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_categories_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_categories_created_at'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_categories_company_id'))

    op.drop_table('edu_fee_categories')
    with op.batch_alter_table('edu_fee_structures', schema=None) as batch_op:
        batch_op.drop_index('ix_fee_structures_company_program_enabled')
        batch_op.drop_index('ix_fee_structures_company_program')
        batch_op.drop_index(batch_op.f('ix_edu_fee_structures_version_no'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_structures_updated_at'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_structures_student_category_id'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_structures_selling_price_list_id'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_structures_program_id'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_structures_name'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_structures_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_structures_created_at'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_structures_company_id'))
        batch_op.drop_index(batch_op.f('ix_edu_fee_structures_branch_id'))

    op.drop_table('edu_fee_structures')
    # ### end Alembic commands ###
