"""updated stock enrty model

Revision ID: 6d7a32bcc68c
Revises: eecfae56fb5f
Create Date: 2025-11-22 17:27:53.186154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d7a32bcc68c'
down_revision = 'eecfae56fb5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difference_account_id', sa.BigInteger(), nullable=True))
        batch_op.create_index(batch_op.f('ix_stock_entries_difference_account_id'), ['difference_account_id'], unique=False)
        batch_op.create_foreign_key(None, 'accounts', ['difference_account_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_stock_entries_difference_account_id'))
        batch_op.drop_column('difference_account_id')

    # ### end Alembic commands ###
