"""updated price list

Revision ID: 700487976a9e
Revises: 886473d6b16f
Create Date: 2025-10-31 22:18:33.625952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '700487976a9e'
down_revision = '886473d6b16f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_not_uom_dependent', sa.Boolean(), nullable=False, comment='ERP-style: if true, use same price irrespective of txn UOM; convert for display.'))
        batch_op.create_index(batch_op.f('ix_price_lists_price_not_uom_dependent'), ['price_not_uom_dependent'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_lists_price_not_uom_dependent'))
        batch_op.drop_column('price_not_uom_dependent')

    # ### end Alembic commands ###
