"""updated buying model

Revision ID: 73c65bc4dff3
Revises: 462680a847fa
Create Date: 2025-11-12 14:15:15.188189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '73c65bc4dff3'
down_revision = '462680a847fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_id', sa.BigInteger(), nullable=True))
        batch_op.alter_column('returned_qty',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               comment='Total quantity returned against this standard Invoice Item (via linked returns).',
               existing_comment='Total quantity returned against this standard Invoice Item (via linked Debit Notes).',
               existing_nullable=False)
        batch_op.create_index('ix_pii_warehouse', ['warehouse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_invoice_items_warehouse_id'), ['warehouse_id'], unique=False)
        batch_op.create_foreign_key(None, 'warehouses', ['warehouse_id'], ['id'])

    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.alter_column('payable_account_id',
               existing_type=sa.BIGINT(),
               comment='Accounts Payable (Credit) account.',
               existing_comment='The Accounts Payable (Liability) account used for the Credit posting.',
               existing_nullable=True)
        batch_op.alter_column('posting_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment="System-determined date for stock/accounting (like ERPNext 'Date')",
               existing_nullable=False)
        batch_op.drop_index('ix_purchase_invoices_dated')
        batch_op.drop_index('ix_purchase_invoices_is_debit_note')
        batch_op.create_index('ix_pin_warehouse', ['warehouse_id'], unique=False)
        batch_op.drop_column('is_debit_note')
        batch_op.drop_column('dated')

    with op.batch_alter_table('purchase_receipt_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_id', sa.BigInteger(), nullable=True))
        batch_op.create_index('ix_pri_warehouse', ['warehouse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_receipt_items_warehouse_id'), ['warehouse_id'], unique=False)
        batch_op.create_foreign_key(None, 'warehouses', ['warehouse_id'], ['id'])

    with op.batch_alter_table('purchase_receipts', schema=None) as batch_op:
        batch_op.alter_column('warehouse_id',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('posting_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment="System-determined date for stock/accounting (like ERPNext 'Date')",
               existing_nullable=False)
        batch_op.drop_index('ix_purchase_receipts_dated')
        batch_op.drop_column('dated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment="User-selected date for display (like ERPNext 'Dated' field)"))
        batch_op.create_index('ix_purchase_receipts_dated', ['dated'], unique=False)
        batch_op.alter_column('posting_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment="System-determined date for stock/accounting (like ERPNext 'Date')",
               existing_nullable=False)
        batch_op.alter_column('warehouse_id',
               existing_type=sa.BIGINT(),
               nullable=False)

    with op.batch_alter_table('purchase_receipt_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_purchase_receipt_items_warehouse_id'))
        batch_op.drop_index('ix_pri_warehouse')
        batch_op.drop_column('warehouse_id')

    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment="User-selected date for display (like ERPNext 'Dated' field)"))
        batch_op.add_column(sa.Column('is_debit_note', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_index('ix_pin_warehouse')
        batch_op.create_index('ix_purchase_invoices_is_debit_note', ['is_debit_note'], unique=False)
        batch_op.create_index('ix_purchase_invoices_dated', ['dated'], unique=False)
        batch_op.alter_column('posting_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment="System-determined date for stock/accounting (like ERPNext 'Date')",
               existing_nullable=False)
        batch_op.alter_column('payable_account_id',
               existing_type=sa.BIGINT(),
               comment='The Accounts Payable (Liability) account used for the Credit posting.',
               existing_comment='Accounts Payable (Credit) account.',
               existing_nullable=True)

    with op.batch_alter_table('purchase_invoice_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_purchase_invoice_items_warehouse_id'))
        batch_op.drop_index('ix_pii_warehouse')
        batch_op.alter_column('returned_qty',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               comment='Total quantity returned against this standard Invoice Item (via linked Debit Notes).',
               existing_comment='Total quantity returned against this standard Invoice Item (via linked returns).',
               existing_nullable=False)
        batch_op.drop_column('warehouse_id')

    # ### end Alembic commands ###
