"""add payment and expense models

Revision ID: 76821fd05507
Revises: aae8d2da24c1
Create Date: 2025-10-17 11:02:09.923135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76821fd05507'
down_revision = 'aae8d2da24c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # First, check if we need to add new values to existing enums
    # Add SHAREHOLDER and OTHER to partytypeenum if they don't exist
    op.execute("""
    DO $$ 
    BEGIN 
        -- Check if SHAREHOLDER exists in partytypeenum
        IF NOT EXISTS (
            SELECT 1 FROM pg_enum 
            WHERE enumlabel = 'SHAREHOLDER' 
            AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'partytypeenum')
        ) THEN
            ALTER TYPE partytypeenum ADD VALUE 'SHAREHOLDER';
        END IF;
        
        -- Check if OTHER exists in partytypeenum  
        IF NOT EXISTS (
            SELECT 1 FROM pg_enum 
            WHERE enumlabel = 'OTHER' 
            AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'partytypeenum')
        ) THEN
            ALTER TYPE partytypeenum ADD VALUE 'OTHER';
        END IF;
    END $$;
    """)

    # Create expense_types table (safe - no complex dependencies)
    op.create_table('expense_types',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Expense type name (e.g., Travel, Office Supplies)'),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('default_account_id', sa.BigInteger(), nullable=True, comment='Default expense account for this type'),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("name <> ''", name='ck_expense_type_name_non_empty'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_expense_type_company_name')
    )

    # Add foreign key to accounts separately only if accounts table exists
    conn = op.get_bind()
    accounts_exists = conn.execute(sa.text("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = 'accounts'
        );
    """)).scalar()

    if accounts_exists:
        op.create_foreign_key('fk_expense_types_default_account_id', 'expense_types', 'accounts', ['default_account_id'], ['id'])

    with op.batch_alter_table('expense_types', schema=None) as batch_op:
        batch_op.create_index('ix_expense_type_active', ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_types_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_types_created_at'), ['created_at'], unique=False)
        if accounts_exists:
            batch_op.create_index(batch_op.f('ix_expense_types_default_account_id'), ['default_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_types_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_types_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_types_updated_at'), ['updated_at'], unique=False)

    # Create expenses table - use String for doc_status to avoid enum creation issues
    op.create_table('expenses',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False, comment='Unique document code (e.g., EXP-2025-00001)'),
    sa.Column('doc_status', sa.String(length=50), nullable=False),
    sa.Column('posting_date', sa.Date(), nullable=False, comment='The date the expense was incurred'),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('cost_center_id', sa.BigInteger(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('journal_entry_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_amount >= 0', name='ck_expense_amount_non_negative'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'branch_id', 'code', name='uq_expense_branch_code')
    )

    # Add optional foreign keys separately
    cost_centers_exists = conn.execute(sa.text("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = 'cost_centers'
        );
    """)).scalar()

    journal_entries_exists = conn.execute(sa.text("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = 'journal_entries'
        );
    """)).scalar()

    if cost_centers_exists:
        op.create_foreign_key('fk_expenses_cost_center_id', 'expenses', 'cost_centers', ['cost_center_id'], ['id'])

    if journal_entries_exists:
        op.create_foreign_key('fk_expenses_journal_entry_id', 'expenses', 'journal_entries', ['journal_entry_id'], ['id'])

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index('ix_expense_company_branch_status', ['company_id', 'branch_id', 'doc_status'], unique=False)
        batch_op.create_index('ix_expense_company_posting', ['company_id', 'posting_date'], unique=False)
        batch_op.create_index('ix_expense_date', ['posting_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_company_id'), ['company_id'], unique=False)
        if cost_centers_exists:
            batch_op.create_index(batch_op.f('ix_expenses_cost_center_id'), ['cost_center_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_doc_status'), ['doc_status'], unique=False)
        if journal_entries_exists:
            batch_op.create_index(batch_op.f('ix_expenses_journal_entry_id'), ['journal_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_posting_date'), ['posting_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_updated_at'), ['updated_at'], unique=False)

    # Create payment_entries table - with safe foreign key handling
    op.create_table('payment_entries',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False, comment='Unique document code (e.g., PE-2025-00001)'),
    sa.Column('doc_status', sa.String(length=50), nullable=False),
    sa.Column('payment_type', sa.String(length=20), nullable=False, comment='Indicates if this is a payment, receipt, or internal transfer'),
    sa.Column('posting_date', sa.Date(), nullable=False, comment='The date the transaction will be posted to the ledger'),
    sa.Column('mode_of_payment_id', sa.BigInteger(), nullable=True),
    sa.Column('party_type', sa.String(length=20), nullable=True),
    sa.Column('party_id', sa.BigInteger(), nullable=True, comment='The specific customer, supplier, etc.'),
    sa.Column('paid_from_account_id', sa.BigInteger(), nullable=False, comment="Company's Bank/Cash account (Source)"),
    sa.Column('paid_to_account_id', sa.BigInteger(), nullable=False, comment="Party's ledger or Target Bank/Cash account"),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=18, scale=6), nullable=False, comment='Sum of allocated amounts from child table'),
    sa.Column('unallocated_amount', sa.Numeric(precision=18, scale=6), nullable=False, comment='Difference between paid and allocated amounts'),
    sa.Column('reference_no', sa.String(length=100), nullable=True, comment='E.g., Check number, bank transaction ID'),
    sa.Column('reference_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('journal_entry_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(payment_type != 'INTERNAL_TRANSFER') OR (paid_from_account_id != paid_to_account_id)", name='ck_payment_internal_transfer_accounts'),
    sa.CheckConstraint('paid_amount >= 0', name='ck_payment_paid_amount_non_negative'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['paid_from_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['paid_to_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_payment_entry_company_code')
    )

    # Add optional foreign keys separately
    modes_of_payment_exists = conn.execute(sa.text("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = 'modes_of_payment'
        );
    """)).scalar()

    if modes_of_payment_exists:
        op.create_foreign_key('fk_payment_entries_mode_of_payment_id', 'payment_entries', 'modes_of_payment', ['mode_of_payment_id'], ['id'])

    if journal_entries_exists:
        op.create_foreign_key('fk_payment_entries_journal_entry_id', 'payment_entries', 'journal_entries', ['journal_entry_id'], ['id'])

    with op.batch_alter_table('payment_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_entries_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_entries_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_entries_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_entries_doc_status'), ['doc_status'], unique=False)
        if journal_entries_exists:
            batch_op.create_index(batch_op.f('ix_payment_entries_journal_entry_id'), ['journal_entry_id'], unique=False)
        if modes_of_payment_exists:
            batch_op.create_index(batch_op.f('ix_payment_entries_mode_of_payment_id'), ['mode_of_payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_entries_paid_from_account_id'), ['paid_from_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_entries_paid_to_account_id'), ['paid_to_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_entries_party_id'), ['party_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_entries_party_type'), ['party_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_entries_payment_type'), ['payment_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_entries_posting_date'), ['posting_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_entries_reference_date'), ['reference_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_entries_reference_no'), ['reference_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_entries_unallocated_amount'), ['unallocated_amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_entries_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_payment_entry_company_posting', ['company_id', 'posting_date'], unique=False)
        batch_op.create_index('ix_payment_entry_paid_from', ['paid_from_account_id'], unique=False)
        batch_op.create_index('ix_payment_entry_party', ['party_type', 'party_id'], unique=False)
        batch_op.create_index('ix_payment_entry_type_date', ['payment_type', 'posting_date'], unique=False)

    # Create expense_items table
    op.create_table('expense_items',
    sa.Column('expense_id', sa.BigInteger(), nullable=False),
    sa.Column('expense_type_id', sa.BigInteger(), nullable=True),
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='Expense account (e.g., Travel Expenses, Office Supplies)'),
    sa.Column('paid_from_account_id', sa.BigInteger(), nullable=False, comment='Cash/Bank account from which expense is paid'),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=False, comment='Amount for this expense line'),
    sa.Column('cost_center_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_expense_item_amount_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paid_from_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Add optional foreign keys
    if cost_centers_exists:
        op.create_foreign_key('fk_expense_items_cost_center_id', 'expense_items', 'cost_centers', ['cost_center_id'], ['id'])

    op.create_foreign_key('fk_expense_items_expense_type_id', 'expense_items', 'expense_types', ['expense_type_id'], ['id'])

    with op.batch_alter_table('expense_items', schema=None) as batch_op:
        batch_op.create_index('idx_expense_item_accounts', ['account_id', 'paid_from_account_id'], unique=False)
        batch_op.create_index('idx_expense_item_expense', ['expense_id'], unique=False)
        batch_op.create_index('idx_expense_item_type', ['expense_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_items_account_id'), ['account_id'], unique=False)
        if cost_centers_exists:
            batch_op.create_index(batch_op.f('ix_expense_items_cost_center_id'), ['cost_center_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_items_expense_id'), ['expense_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_items_expense_type_id'), ['expense_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_items_paid_from_account_id'), ['paid_from_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_items_updated_at'), ['updated_at'], unique=False)

    # Create payment_items table
    op.create_table('payment_items',
    sa.Column('payment_id', sa.BigInteger(), nullable=False),
    sa.Column('source_doctype_id', sa.BigInteger(), nullable=True),
    sa.Column('source_doc_id', sa.BigInteger(), nullable=True, comment='PK of referenced doc (fast integer lookup)'),
    sa.Column('allocated_amount', sa.Numeric(precision=18, scale=6), nullable=False, comment='Amount applied to this reference'),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('allocated_amount >= 0', name='ck_payment_item_amount_non_negative'),
    sa.ForeignKeyConstraint(['payment_id'], ['payment_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # Add optional foreign key
    document_types_exists = conn.execute(sa.text("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = 'document_types'
        );
    """)).scalar()

    if document_types_exists:
        op.create_foreign_key('fk_payment_items_source_doctype_id', 'payment_items', 'document_types', ['source_doctype_id'], ['id'])

    with op.batch_alter_table('payment_items', schema=None) as batch_op:
        batch_op.create_index('idx_payment_item_source', ['source_doctype_id', 'source_doc_id'], unique=False)
        batch_op.create_index('ix_payment_item_payment', ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_items_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_items_source_doc_id'), ['source_doc_id'], unique=False)
        if document_types_exists:
            batch_op.create_index(batch_op.f('ix_payment_items_source_doctype_id'), ['source_doctype_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_items_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_items_updated_at'))
        try:
            batch_op.drop_index(batch_op.f('ix_payment_items_source_doctype_id'))
        except:
            pass
        batch_op.drop_index(batch_op.f('ix_payment_items_source_doc_id'))
        batch_op.drop_index(batch_op.f('ix_payment_items_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payment_items_created_at'))
        batch_op.drop_index('ix_payment_item_payment')
        batch_op.drop_index('idx_payment_item_source')

    op.drop_table('payment_items')
    with op.batch_alter_table('expense_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_items_updated_at'))
        batch_op.drop_index(batch_op.f('ix_expense_items_paid_from_account_id'))
        batch_op.drop_index(batch_op.f('ix_expense_items_expense_type_id'))
        batch_op.drop_index(batch_op.f('ix_expense_items_expense_id'))
        batch_op.drop_index(batch_op.f('ix_expense_items_created_at'))
        try:
            batch_op.drop_index(batch_op.f('ix_expense_items_cost_center_id'))
        except:
            pass
        batch_op.drop_index(batch_op.f('ix_expense_items_account_id'))
        batch_op.drop_index('idx_expense_item_type')
        batch_op.drop_index('idx_expense_item_expense')
        batch_op.drop_index('idx_expense_item_accounts')

    op.drop_table('expense_items')
    with op.batch_alter_table('payment_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_payment_entry_type_date')
        batch_op.drop_index('ix_payment_entry_party')
        batch_op.drop_index('ix_payment_entry_paid_from')
        batch_op.drop_index('ix_payment_entry_company_posting')
        batch_op.drop_index(batch_op.f('ix_payment_entries_updated_at'))
        batch_op.drop_index(batch_op.f('ix_payment_entries_unallocated_amount'))
        batch_op.drop_index(batch_op.f('ix_payment_entries_reference_no'))
        batch_op.drop_index(batch_op.f('ix_payment_entries_reference_date'))
        batch_op.drop_index(batch_op.f('ix_payment_entries_posting_date'))
        batch_op.drop_index(batch_op.f('ix_payment_entries_payment_type'))
        batch_op.drop_index(batch_op.f('ix_payment_entries_party_type'))
        batch_op.drop_index(batch_op.f('ix_payment_entries_party_id'))
        batch_op.drop_index(batch_op.f('ix_payment_entries_paid_to_account_id'))
        batch_op.drop_index(batch_op.f('ix_payment_entries_paid_from_account_id'))
        try:
            batch_op.drop_index(batch_op.f('ix_payment_entries_mode_of_payment_id'))
        except:
            pass
        try:
            batch_op.drop_index(batch_op.f('ix_payment_entries_journal_entry_id'))
        except:
            pass
        batch_op.drop_index(batch_op.f('ix_payment_entries_doc_status'))
        batch_op.drop_index(batch_op.f('ix_payment_entries_created_at'))
        batch_op.drop_index(batch_op.f('ix_payment_entries_company_id'))
        batch_op.drop_index(batch_op.f('ix_payment_entries_code'))
        batch_op.drop_index(batch_op.f('ix_payment_entries_branch_id'))

    op.drop_table('payment_entries')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_updated_at'))
        batch_op.drop_index(batch_op.f('ix_expenses_posting_date'))
        try:
            batch_op.drop_index(batch_op.f('ix_expenses_journal_entry_id'))
        except:
            pass
        batch_op.drop_index(batch_op.f('ix_expenses_doc_status'))
        batch_op.drop_index(batch_op.f('ix_expenses_created_at'))
        try:
            batch_op.drop_index(batch_op.f('ix_expenses_cost_center_id'))
        except:
            pass
        batch_op.drop_index(batch_op.f('ix_expenses_company_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_code'))
        batch_op.drop_index(batch_op.f('ix_expenses_branch_id'))
        batch_op.drop_index('ix_expense_date')
        batch_op.drop_index('ix_expense_company_posting')
        batch_op.drop_index('ix_expense_company_branch_status')

    op.drop_table('expenses')
    with op.batch_alter_table('expense_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_types_updated_at'))
        batch_op.drop_index(batch_op.f('ix_expense_types_name'))
        batch_op.drop_index(batch_op.f('ix_expense_types_is_active'))
        try:
            batch_op.drop_index(batch_op.f('ix_expense_types_default_account_id'))
        except:
            pass
        batch_op.drop_index(batch_op.f('ix_expense_types_created_at'))
        batch_op.drop_index(batch_op.f('ix_expense_types_company_id'))
        batch_op.drop_index('ix_expense_type_active')

    op.drop_table('expense_types')

    # Note: We don't remove the enum values in downgrade as it's complex in PostgreSQL
    # ### end Alembic commands ###