"""fingerPrint

Revision ID: a16597e314b1
Revises: fb06d3fc466b
Create Date: 2026-01-13 11:44:31.112498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a16597e314b1'
down_revision = 'fb06d3fc466b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_settings',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('default_receivable_account_id', sa.BigInteger(), nullable=True),
    sa.Column('default_payable_account_id', sa.BigInteger(), nullable=True),
    sa.Column('allow_negative_stock', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['default_payable_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['default_receivable_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', name='uq_accounting_settings_company')
    )
    with op.batch_alter_table('accounting_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounting_settings_company_id'), ['company_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_accounting_settings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounting_settings_updated_at'), ['updated_at'], unique=False)

    op.create_table('employee_fingerprint_templates',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('finger_index', sa.Enum('UNKNOWN', 'RIGHT_THUMB', 'RIGHT_INDEX', 'RIGHT_MIDDLE', 'RIGHT_RING', 'RIGHT_LITTLE', 'LEFT_THUMB', 'LEFT_INDEX', 'LEFT_MIDDLE', 'LEFT_RING', 'LEFT_LITTLE', name='finger_index_enum'), nullable=False),
    sa.Column('template', sa.LargeBinary(), nullable=False),
    sa.Column('template_format', sa.String(length=64), nullable=False, comment='Format label for templates (e.g. DP U.are.U vX)'),
    sa.Column('device_name', sa.String(length=120), nullable=True),
    sa.Column('device_serial', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='fingerprint_template_status_enum'), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'finger_index', name='uq_emp_fingerprint_finger')
    )
    with op.batch_alter_table('employee_fingerprint_templates', schema=None) as batch_op:
        batch_op.create_index('ix_emp_fingerprint_company_emp', ['company_id', 'employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_fingerprint_templates_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_fingerprint_templates_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_fingerprint_templates_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_fingerprint_templates_finger_index'), ['finger_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_fingerprint_templates_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_fingerprint_templates_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('sales_invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_note_item_id', sa.BigInteger(), nullable=True, comment='Links invoice item to delivery note item (for stock reconciliation).'))
        batch_op.create_index(batch_op.f('ix_sales_invoice_items_delivery_note_item_id'), ['delivery_note_item_id'], unique=False)
        batch_op.create_foreign_key(None, 'sales_delivery_note_items', ['delivery_note_item_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_invoice_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sales_invoice_items_delivery_note_item_id'))
        batch_op.drop_column('delivery_note_item_id')

    with op.batch_alter_table('employee_fingerprint_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_fingerprint_templates_updated_at'))
        batch_op.drop_index(batch_op.f('ix_employee_fingerprint_templates_status'))
        batch_op.drop_index(batch_op.f('ix_employee_fingerprint_templates_finger_index'))
        batch_op.drop_index(batch_op.f('ix_employee_fingerprint_templates_employee_id'))
        batch_op.drop_index(batch_op.f('ix_employee_fingerprint_templates_created_at'))
        batch_op.drop_index(batch_op.f('ix_employee_fingerprint_templates_company_id'))
        batch_op.drop_index('ix_emp_fingerprint_company_emp')

    op.drop_table('employee_fingerprint_templates')
    with op.batch_alter_table('accounting_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounting_settings_updated_at'))
        batch_op.drop_index(batch_op.f('ix_accounting_settings_created_at'))
        batch_op.drop_index(batch_op.f('ix_accounting_settings_company_id'))

    op.drop_table('accounting_settings')
    # ### end Alembic commands ###
