"""Fix Asset.supplier FK to parties

Revision ID: a21713620c43
Revises: af32afafcf28
Create Date: 2025-10-22 10:12:57.186194

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a21713620c43'
down_revision = 'af32afafcf28'
branch_labels = None
depends_on = None


def enum_exists(enum_name):
    """Check if an enum type already exists in the database"""
    conn = op.get_bind()
    result = conn.execute(
        sa.text("SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = :enum_name)"),
        {'enum_name': enum_name}
    ).scalar()
    return result


def create_docstatus_enum():
    """Safely create docstatusenum if it doesn't exist"""
    if not enum_exists('docstatusenum'):
        op.execute("""
            CREATE TYPE docstatusenum AS ENUM (
                'DRAFT', 'SUBMITTED', 'CANCELLED', 'UNPAID', 
                'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'RETURNED'
            )
        """)


def create_accountuserole_enum():
    """Safely create accountuseroleenum if it doesn't exist"""
    if not enum_exists('accountuseroleenum'):
        op.execute("""
            CREATE TYPE accountuseroleenum AS ENUM (
                'CASH_IN', 'CASH_OUT', 'TRANSFER_SOURCE', 
                'TRANSFER_TARGET', 'EXPENSE'
            )
        """)


def create_depreciationmethod_enum():
    """Safely create depreciationmethodenum if it doesn't exist"""
    if not enum_exists('depreciationmethodenum'):
        op.execute("""
            CREATE TYPE depreciationmethodenum AS ENUM (
                'STRAIGHT_LINE', 'DOUBLE_DECLINING_BALANCE', 
                'WRITTEN_DOWN_VALUE', 'MANUAL'
            )
        """)


def create_assetstatus_enum():
    """Safely create assetstatusenum if it doesn't exist"""
    if not enum_exists('assetstatusenum'):
        op.execute("""
            CREATE TYPE assetstatusenum AS ENUM (
                'DRAFT', 'SUBMITTED', 'PARTIALLY_DEPRECIATED', 
                'FULLY_DEPRECIATED', 'SCRAPPED', 'SOLD', 
                'CAPITALIZED', 'ISSUED'
            )
        """)


def table_exists(table_name):
    """Check if a table exists"""
    conn = op.get_bind()
    result = conn.execute(
        sa.text("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = :table_name
            )
        """),
        {'table_name': table_name}
    ).scalar()
    return result


def upgrade():
    # Create enum types safely first
    create_docstatus_enum()
    create_accountuserole_enum()
    create_depreciationmethod_enum()
    create_assetstatus_enum()

    # ### commands auto generated by Alembic - please adjust! ###

    # Create asset_movements table - USE TEXT INSTEAD OF ENUM TO AVOID AUTO-CREATION
    if not table_exists('asset_movements'):
        op.create_table('asset_movements',
            sa.Column('company_id', sa.BigInteger(), nullable=False),
            sa.Column('name', sa.String(length=255), nullable=False),
            sa.Column('doc_status', sa.String(length=50), nullable=False),  # Changed to String
            sa.Column('posting_date', sa.Date(), nullable=False),
            sa.Column('purpose', sa.String(length=255), nullable=False, comment='Issue/Receipt/Transfer'),
            sa.Column('id', sa.BigInteger(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('company_id', 'name', name='uq_asset_movement_company_name')
        )
        with op.batch_alter_table('asset_movements', schema=None) as batch_op:
            batch_op.create_index('ix_am_posting_date', ['posting_date'], unique=False)
            batch_op.create_index(batch_op.f('ix_asset_movements_company_id'), ['company_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_asset_movements_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_asset_movements_doc_status'), ['doc_status'], unique=False)
            batch_op.create_index(batch_op.f('ix_asset_movements_name'), ['name'], unique=False)
            batch_op.create_index(batch_op.f('ix_asset_movements_posting_date'), ['posting_date'], unique=False)
            batch_op.create_index(batch_op.f('ix_asset_movements_purpose'), ['purpose'], unique=False)
            batch_op.create_index(batch_op.f('ix_asset_movements_updated_at'), ['updated_at'], unique=False)

    # Create finance_books table
    if not table_exists('finance_books'):
        op.create_table('finance_books',
            sa.Column('company_id', sa.BigInteger(), nullable=False),
            sa.Column('name', sa.String(length=255), nullable=False),
            sa.Column('id', sa.BigInteger(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('company_id', 'name', name='uq_finance_book_company_name')
        )
        with op.batch_alter_table('finance_books', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_finance_books_company_id'), ['company_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_finance_books_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_finance_books_name'), ['name'], unique=False)
            batch_op.create_index(batch_op.f('ix_finance_books_updated_at'), ['updated_at'], unique=False)

    # Create account_access_policies table - USE TEXT INSTEAD OF ENUM
    if not table_exists('account_access_policies'):
        op.create_table('account_access_policies',
            sa.Column('mode_of_payment_id', sa.BigInteger(), nullable=False),
            sa.Column('company_id', sa.BigInteger(), nullable=False),
            sa.Column('role', sa.String(length=50), nullable=False),  # Changed to String
            sa.Column('user_id', sa.BigInteger(), nullable=True),
            sa.Column('department_id', sa.BigInteger(), nullable=True),
            sa.Column('branch_id', sa.BigInteger(), nullable=True),
            sa.Column('account_id', sa.BigInteger(), nullable=False),
            sa.Column('enabled', sa.Boolean(), nullable=False),
            sa.Column('id', sa.BigInteger(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.CheckConstraint('(CASE WHEN user_id IS NULL THEN 0 ELSE 1 END) + (CASE WHEN department_id IS NULL THEN 0 ELSE 1 END) + (CASE WHEN branch_id IS NULL THEN 0 ELSE 1 END) <= 1', name='ck_aap_one_scope'),
            sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
            sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
            sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
            sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
            sa.ForeignKeyConstraint(['mode_of_payment_id'], ['modes_of_payment.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('account_access_policies', schema=None) as batch_op:
            batch_op.create_index('ix_aap_probe', ['company_id', 'mode_of_payment_id', 'role', 'enabled'], unique=False)
            batch_op.create_index(batch_op.f('ix_account_access_policies_account_id'), ['account_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_account_access_policies_branch_id'), ['branch_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_account_access_policies_company_id'), ['company_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_account_access_policies_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_account_access_policies_department_id'), ['department_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_account_access_policies_enabled'), ['enabled'], unique=False)
            batch_op.create_index(batch_op.f('ix_account_access_policies_mode_of_payment_id'), ['mode_of_payment_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_account_access_policies_role'), ['role'], unique=False)
            batch_op.create_index(batch_op.f('ix_account_access_policies_updated_at'), ['updated_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_account_access_policies_user_id'), ['user_id'], unique=False)
            batch_op.create_index('uq_aap_unique_policy_enabled', ['mode_of_payment_id', 'company_id', 'role', 'user_id', 'department_id', 'branch_id', 'account_id'], unique=True, postgresql_where=sa.text('enabled = true'))

    # Create mode_of_payment_accounts table
    if not table_exists('mode_of_payment_accounts'):
        op.create_table('mode_of_payment_accounts',
            sa.Column('mode_of_payment_id', sa.BigInteger(), nullable=False),
            sa.Column('account_id', sa.BigInteger(), nullable=False),
            sa.Column('is_default', sa.Boolean(), nullable=False),
            sa.Column('enabled', sa.Boolean(), nullable=False),
            sa.Column('id', sa.BigInteger(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
            sa.ForeignKeyConstraint(['mode_of_payment_id'], ['modes_of_payment.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('mode_of_payment_id', 'account_id', name='uq_mopa_mop_account')
        )
        with op.batch_alter_table('mode_of_payment_accounts', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_mode_of_payment_accounts_account_id'), ['account_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_mode_of_payment_accounts_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_mode_of_payment_accounts_enabled'), ['enabled'], unique=False)
            batch_op.create_index(batch_op.f('ix_mode_of_payment_accounts_is_default'), ['is_default'], unique=False)
            batch_op.create_index(batch_op.f('ix_mode_of_payment_accounts_mode_of_payment_id'), ['mode_of_payment_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_mode_of_payment_accounts_updated_at'), ['updated_at'], unique=False)
            batch_op.create_index('ix_mopa_enabled_probe', ['mode_of_payment_id', 'enabled'], unique=False)
            batch_op.create_index('uq_mopa_default_per_mop', ['mode_of_payment_id'], unique=True, postgresql_where=sa.text('is_default = true AND enabled = true'))

    # Create asset_finance_books table - USE TEXT INSTEAD OF ENUM
    if not table_exists('asset_finance_books'):
        op.create_table('asset_finance_books',
            sa.Column('asset_id', sa.BigInteger(), nullable=False),
            sa.Column('finance_book_id', sa.BigInteger(), nullable=False),
            sa.Column('depreciation_method', sa.String(length=50), nullable=False),  # Changed to String
            sa.Column('total_number_of_depreciations', sa.Integer(), nullable=False),
            sa.Column('frequency_of_depreciation', sa.Integer(), nullable=False, comment='Months between depreciations'),
            sa.Column('depreciation_posting_date', sa.Date(), nullable=True),
            sa.Column('expected_value_after_useful_life', sa.Numeric(precision=15, scale=4), nullable=False),
            sa.Column('value_after_depreciation', sa.Numeric(precision=15, scale=4), nullable=False),
            sa.Column('rate_of_depreciation', sa.Numeric(precision=8, scale=4), nullable=False),
            sa.Column('id', sa.BigInteger(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.CheckConstraint('expected_value_after_useful_life >= 0', name='ck_afb_salvage_nonneg'),
            sa.CheckConstraint('frequency_of_depreciation > 0', name='ck_afb_freq_pos'),
            sa.CheckConstraint('rate_of_depreciation >= 0', name='ck_afb_rate_nonneg'),
            sa.CheckConstraint('total_number_of_depreciations > 0', name='ck_afb_total_pos'),
            sa.CheckConstraint('value_after_depreciation >= 0', name='ck_afb_vad_nonneg'),
            sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['finance_book_id'], ['finance_books.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('asset_id', 'finance_book_id', name='uq_afb_asset_book')
        )
        with op.batch_alter_table('asset_finance_books', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_asset_finance_books_asset_id'), ['asset_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_asset_finance_books_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_asset_finance_books_depreciation_posting_date'), ['depreciation_posting_date'], unique=False)
            batch_op.create_index(batch_op.f('ix_asset_finance_books_finance_book_id'), ['finance_book_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_asset_finance_books_updated_at'), ['updated_at'], unique=False)

    # Create asset_movement_items table
    if not table_exists('asset_movement_items'):
        op.create_table('asset_movement_items',
            sa.Column('asset_movement_id', sa.BigInteger(), nullable=False),
            sa.Column('asset_id', sa.BigInteger(), nullable=False),
            sa.Column('from_location', sa.String(length=255), nullable=True),
            sa.Column('to_location', sa.String(length=255), nullable=True),
            sa.Column('from_employee', sa.BigInteger(), nullable=True),
            sa.Column('to_employee', sa.BigInteger(), nullable=True),
            sa.Column('id', sa.BigInteger(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
            sa.ForeignKeyConstraint(['asset_movement_id'], ['asset_movements.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['from_employee'], ['employees.id'], ),
            sa.ForeignKeyConstraint(['to_employee'], ['employees.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('asset_movement_items', schema=None) as batch_op:
            batch_op.create_index('ix_ami_asset', ['asset_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_asset_movement_items_asset_id'), ['asset_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_asset_movement_items_asset_movement_id'), ['asset_movement_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_asset_movement_items_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_asset_movement_items_updated_at'), ['updated_at'], unique=False)

    # Drop account_selection_rules table if it exists
    if table_exists('account_selection_rules'):
        with op.batch_alter_table('account_selection_rules', schema=None) as batch_op:
            batch_op.drop_index('ix_account_selection_rules_account_id')
            batch_op.drop_index('ix_account_selection_rules_branch_id')
            batch_op.drop_index('ix_account_selection_rules_company_id')
            batch_op.drop_index('ix_account_selection_rules_created_at')
            batch_op.drop_index('ix_account_selection_rules_department_id')
            batch_op.drop_index('ix_account_selection_rules_mode_of_payment_id')
            batch_op.drop_index('ix_account_selection_rules_parent_account_id')
            batch_op.drop_index('ix_account_selection_rules_role')
            batch_op.drop_index('ix_account_selection_rules_rule_type')
            batch_op.drop_index('ix_account_selection_rules_updated_at')
            batch_op.drop_index('ix_account_selection_rules_user_id')
            batch_op.drop_index('uq_accrule_allow_account', postgresql_where="((rule_type = 'ALLOW'::accountruletypeenum) AND (account_id IS NOT NULL))")
            batch_op.drop_index('uq_accrule_allow_parent', postgresql_where="((rule_type = 'ALLOW'::accountruletypeenum) AND (parent_account_id IS NOT NULL))")
            batch_op.drop_index('uq_accrule_default_mop', postgresql_where="((rule_type = 'DEFAULT'::accountruletypeenum) AND (mode_of_payment_id IS NOT NULL))")
            batch_op.drop_index('uq_accrule_default_nomop', postgresql_where="((rule_type = 'DEFAULT'::accountruletypeenum) AND (mode_of_payment_id IS NULL))")

        op.drop_table('account_selection_rules')

    # Modify asset_categories table
    if table_exists('asset_categories'):
        with op.batch_alter_table('asset_categories', schema=None) as batch_op:
            batch_op.add_column(sa.Column('asset_category_name', sa.String(length=255), nullable=False))
            batch_op.add_column(sa.Column('fixed_asset_account', sa.BigInteger(), nullable=False))
            batch_op.add_column(sa.Column('accumulated_depreciation_account', sa.BigInteger(), nullable=False))
            batch_op.add_column(sa.Column('depreciation_expense_account', sa.BigInteger(), nullable=False))
            batch_op.add_column(sa.Column('capital_work_in_progress_account', sa.BigInteger(), nullable=True))
            batch_op.add_column(sa.Column('enable_cwip_accounting', sa.Boolean(), nullable=False))

            # Convert to String instead of Enum to avoid auto-creation
            batch_op.alter_column('depreciation_method',
                   existing_type=sa.VARCHAR(length=50),
                   type_=sa.String(length=50),
                   existing_comment='e.g., Straight Line, Double Declining Balance.',
                   existing_nullable=False)

            batch_op.drop_index('ix_asset_categories_accumulated_depreciation_account_id')
            batch_op.drop_index('ix_asset_categories_code')
            batch_op.drop_index('ix_asset_categories_depreciation_expense_account_id')
            batch_op.drop_index('ix_asset_categories_fixed_asset_account_id')
            batch_op.drop_index('ix_asset_categories_name')
            batch_op.drop_constraint('uq_asset_category_company_code', type_='unique')
            batch_op.drop_constraint('uq_asset_category_company_name', type_='unique')
            batch_op.create_unique_constraint('uq_asset_category_company_name', ['company_id', 'asset_category_name'])
            batch_op.create_index(batch_op.f('ix_asset_categories_accumulated_depreciation_account'), ['accumulated_depreciation_account'], unique=False)
            batch_op.create_index(batch_op.f('ix_asset_categories_asset_category_name'), ['asset_category_name'], unique=False)
            batch_op.create_index(batch_op.f('ix_asset_categories_capital_work_in_progress_account'), ['capital_work_in_progress_account'], unique=False)
            batch_op.create_index(batch_op.f('ix_asset_categories_depreciation_expense_account'), ['depreciation_expense_account'], unique=False)
            batch_op.create_index(batch_op.f('ix_asset_categories_fixed_asset_account'), ['fixed_asset_account'], unique=False)

            # Drop foreign key constraints if they exist
            batch_op.drop_constraint('asset_categories_depreciation_expense_account_id_fkey', type_='foreignkey')
            batch_op.drop_constraint('asset_categories_fixed_asset_account_id_fkey', type_='foreignkey')
            batch_op.drop_constraint('asset_categories_accumulated_depreciation_account_id_fkey', type_='foreignkey')

            batch_op.create_foreign_key(None, 'accounts', ['accumulated_depreciation_account'], ['id'])
            batch_op.create_foreign_key(None, 'accounts', ['fixed_asset_account'], ['id'])
            batch_op.create_foreign_key(None, 'accounts', ['capital_work_in_progress_account'], ['id'])
            batch_op.create_foreign_key(None, 'accounts', ['depreciation_expense_account'], ['id'])

            batch_op.drop_column('is_active')
            batch_op.drop_column('name')
            batch_op.drop_column('accumulated_depreciation_account_id')
            batch_op.drop_column('depreciation_expense_account_id')
            batch_op.drop_column('fixed_asset_account_id')
            batch_op.drop_column('code')

    # Modify asset_depreciation_entries table
    if table_exists('asset_depreciation_entries'):
        with op.batch_alter_table('asset_depreciation_entries', schema=None) as batch_op:
            batch_op.add_column(sa.Column('finance_book_id', sa.BigInteger(), nullable=False))
            batch_op.add_column(sa.Column('schedule_date', sa.Date(), nullable=False))
            batch_op.add_column(sa.Column('accumulated_depreciation_amount', sa.Numeric(precision=15, scale=4), nullable=False))

            batch_op.alter_column('journal_entry_id',
                   existing_type=sa.BIGINT(),
                   existing_comment='The link to the actual GL Journal Entry created by this record.',
                   existing_nullable=True)

            batch_op.alter_column('depreciation_amount',
                   existing_type=sa.NUMERIC(precision=14, scale=4),
                   type_=sa.Numeric(precision=15, scale=4),
                   existing_nullable=False)

            batch_op.drop_index('ix_asset_depreciation_entries_posting_date')
            batch_op.drop_constraint('uq_ade_asset_posting_date', type_='unique')

            batch_op.create_index('ix_ade_asset_date', ['asset_id', 'schedule_date'], unique=False)
            batch_op.create_index(batch_op.f('ix_asset_depreciation_entries_finance_book_id'), ['finance_book_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_asset_depreciation_entries_schedule_date'), ['schedule_date'], unique=False)
            batch_op.create_unique_constraint('uq_ade_asset_book_date', ['asset_id', 'finance_book_id', 'schedule_date'])

            batch_op.create_foreign_key(None, 'finance_books', ['finance_book_id'], ['id'])

            batch_op.drop_column('remarks')
            batch_op.drop_column('accumulated_depreciation_after')
            batch_op.drop_column('current_value_after')
            batch_op.drop_column('posting_date')

    # Modify assets table - USE TEXT INSTEAD OF ENUM
    if table_exists('assets'):
        with op.batch_alter_table('assets', schema=None) as batch_op:
            batch_op.add_column(sa.Column('asset_name', sa.String(length=255), nullable=False))
            batch_op.add_column(sa.Column('doc_status', sa.String(length=50), nullable=False))  # Changed to String
            batch_op.add_column(sa.Column('asset_status', sa.String(length=50), nullable=False))  # Changed to String
            batch_op.add_column(sa.Column('asset_category', sa.BigInteger(), nullable=False))
            batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
            batch_op.add_column(sa.Column('purchase_receipt', sa.BigInteger(), nullable=True))
            batch_op.add_column(sa.Column('purchase_invoice', sa.BigInteger(), nullable=True))
            batch_op.add_column(sa.Column('supplier', sa.BigInteger(), nullable=True))
            batch_op.add_column(sa.Column('purchase_date', sa.Date(), nullable=True))
            batch_op.add_column(sa.Column('available_for_use_date', sa.Date(), nullable=True))
            batch_op.add_column(sa.Column('opening_accumulated_depreciation', sa.Numeric(precision=15, scale=4), nullable=True))
            batch_op.add_column(sa.Column('calculate_depreciation', sa.Boolean(), nullable=False))
            batch_op.add_column(sa.Column('is_existing_asset', sa.Boolean(), nullable=False))
            batch_op.add_column(sa.Column('value_after_depreciation', sa.Numeric(precision=15, scale=4), nullable=False))
            batch_op.add_column(sa.Column('asset_quantity', sa.Integer(), nullable=False))
            batch_op.add_column(sa.Column('cost_center', sa.BigInteger(), nullable=True))

            batch_op.alter_column('item_id',
                   existing_type=sa.BIGINT(),
                   existing_comment='The Item master from which this asset was purchased.',
                   existing_nullable=True)

            batch_op.alter_column('gross_purchase_amount',
                   existing_type=sa.NUMERIC(precision=14, scale=4),
                   type_=sa.Numeric(precision=15, scale=4),
                   nullable=True,
                   existing_comment='Original cost of the asset.')

            batch_op.alter_column('expected_salvage_value',
                   existing_type=sa.NUMERIC(precision=14, scale=4),
                   type_=sa.Numeric(precision=15, scale=4),
                   nullable=True,
                   existing_comment='Residual value at the end of useful life.')

            batch_op.alter_column('depreciation_start_date',
                   existing_type=sa.DATE(),
                   nullable=True,
                   existing_comment='The date depreciation calculation begins.')

            batch_op.drop_index('ix_asset_status')
            batch_op.drop_index('ix_assets_asset_category_id')
            batch_op.drop_index('ix_assets_code')
            batch_op.drop_index('ix_assets_cost_center_id')
            batch_op.drop_index('ix_assets_purchase_invoice_id')
            batch_op.drop_constraint('uq_asset_company_code', type_='unique')

            batch_op.create_index('ix_asset_category', ['asset_category'], unique=False)
            batch_op.create_index('ix_asset_company_status', ['company_id', 'asset_status'], unique=False)
            batch_op.create_index('ix_asset_purchase_date', ['purchase_date'], unique=False)
            batch_op.create_index(batch_op.f('ix_assets_asset_category'), ['asset_category'], unique=False)
            batch_op.create_index(batch_op.f('ix_assets_asset_name'), ['asset_name'], unique=False)
            batch_op.create_index(batch_op.f('ix_assets_asset_status'), ['asset_status'], unique=False)
            batch_op.create_index(batch_op.f('ix_assets_available_for_use_date'), ['available_for_use_date'], unique=False)
            batch_op.create_index(batch_op.f('ix_assets_calculate_depreciation'), ['calculate_depreciation'], unique=False)
            batch_op.create_index(batch_op.f('ix_assets_cost_center'), ['cost_center'], unique=False)
            batch_op.create_index(batch_op.f('ix_assets_depreciation_start_date'), ['depreciation_start_date'], unique=False)
            batch_op.create_index(batch_op.f('ix_assets_doc_status'), ['doc_status'], unique=False)
            batch_op.create_index(batch_op.f('ix_assets_is_existing_asset'), ['is_existing_asset'], unique=False)
            batch_op.create_index(batch_op.f('ix_assets_purchase_date'), ['purchase_date'], unique=False)
            batch_op.create_index(batch_op.f('ix_assets_purchase_invoice'), ['purchase_invoice'], unique=False)
            batch_op.create_index(batch_op.f('ix_assets_purchase_receipt'), ['purchase_receipt'], unique=False)
            batch_op.create_index(batch_op.f('ix_assets_supplier'), ['supplier'], unique=False)

            batch_op.create_unique_constraint('uq_asset_company_name', ['company_id', 'asset_name'])

            batch_op.drop_constraint('assets_cost_center_id_fkey', type_='foreignkey')
            batch_op.drop_constraint('assets_purchase_invoice_id_fkey', type_='foreignkey')
            batch_op.drop_constraint('assets_asset_category_id_fkey', type_='foreignkey')

            batch_op.create_foreign_key(None, 'purchase_receipts', ['purchase_receipt'], ['id'])
            batch_op.create_foreign_key(None, 'asset_categories', ['asset_category'], ['id'])
            batch_op.create_foreign_key(None, 'cost_centers', ['cost_center'], ['id'])
            batch_op.create_foreign_key(None, 'purchase_invoices', ['purchase_invoice'], ['id'])
            batch_op.create_foreign_key(None, 'parties', ['supplier'], ['id'])

            batch_op.drop_column('accumulated_depreciation')
            batch_op.drop_column('name')
            batch_op.drop_column('asset_category_id')
            batch_op.drop_column('status')
            batch_op.drop_column('code')
            batch_op.drop_column('current_value')
            batch_op.drop_column('purchase_invoice_id')
            batch_op.drop_column('cost_center_id')

    # Modify cost_centers table
    if table_exists('cost_centers'):
        with op.batch_alter_table('cost_centers', schema=None) as batch_op:
            batch_op.drop_index('ix_cost_centers_code')
            batch_op.drop_constraint('uq_cost_center_company_branch_code', type_='unique')
            batch_op.create_unique_constraint('uq_cost_center_company_branch', ['company_id', 'branch_id'])
            batch_op.drop_column('code')

    # Modify expense_types table
    if table_exists('expense_types'):
        with op.batch_alter_table('expense_types', schema=None) as batch_op:
            batch_op.add_column(sa.Column('enabled', sa.Boolean(), nullable=False))
            batch_op.drop_index('ix_expense_type_active')
            batch_op.drop_index('ix_expense_types_is_active')
            batch_op.create_index('ix_expense_type_enabled', ['enabled'], unique=False)
            batch_op.create_index(batch_op.f('ix_expense_types_enabled'), ['enabled'], unique=False)
            batch_op.drop_column('is_active')

    # Modify item_prices table
    if table_exists('item_prices'):
        with op.batch_alter_table('item_prices', schema=None) as batch_op:
            batch_op.add_column(sa.Column('code', sa.String(length=100), nullable=False, comment='An optional external or human-readable code for this specific item price rule.'))
            batch_op.add_column(sa.Column('company_id', sa.BigInteger(), nullable=False))
            batch_op.create_index('ix_item_price_company_code_lookup', ['company_id', 'code'], unique=False)
            batch_op.create_index(batch_op.f('ix_item_prices_code'), ['code'], unique=False)
            batch_op.create_index(batch_op.f('ix_item_prices_company_id'), ['company_id'], unique=False)
            batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'])

    # Modify modes_of_payment table
    if table_exists('modes_of_payment'):
        with op.batch_alter_table('modes_of_payment', schema=None) as batch_op:
            batch_op.add_column(sa.Column('enabled', sa.Boolean(), nullable=False))
            batch_op.alter_column('company_id',
                   existing_type=sa.BIGINT(),
                   nullable=False)
            batch_op.drop_index('idx_mop_branch_id')
            batch_op.drop_index('idx_mop_company_id')
            batch_op.drop_index('idx_mop_default_account')
            batch_op.drop_index('idx_mop_type')
            batch_op.drop_index('ix_modes_of_payment_branch_id')
            batch_op.drop_constraint('uq_mode_of_payment_name_company_branch', type_='unique')
            batch_op.create_index(batch_op.f('ix_modes_of_payment_enabled'), ['enabled'], unique=False)
            batch_op.create_index('ix_mop_company_enabled', ['company_id', 'enabled'], unique=False)
            batch_op.create_index('ix_mop_company_type', ['company_id', 'type'], unique=False)
            batch_op.create_unique_constraint('uq_mop_company_name', ['company_id', 'name'])
            batch_op.drop_constraint('modes_of_payment_branch_id_fkey', type_='foreignkey')
            batch_op.drop_constraint('modes_of_payment_default_account_id_fkey', type_='foreignkey')
            batch_op.drop_column('is_active')
            batch_op.drop_column('default_account_id')
            batch_op.drop_column('branch_id')

    # Modify price_lists table
    if table_exists('price_lists'):
        with op.batch_alter_table('price_lists', schema=None) as batch_op:
            batch_op.drop_column('currency_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Note: The downgrade function is kept as is since it's primarily for rollback
    # and the enum types will be dropped automatically when no longer used

    with op.batch_alter_table('price_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency_code', sa.VARCHAR(length=3), autoincrement=False, nullable=False, comment='ISO currency code (e.g., USD, EUR).'))

    with op.batch_alter_table('modes_of_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('default_account_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('modes_of_payment_default_account_id_fkey', 'accounts', ['default_account_id'], ['id'])
        batch_op.create_foreign_key('modes_of_payment_branch_id_fkey', 'branches', ['branch_id'], ['id'])
        batch_op.drop_constraint('uq_mop_company_name', type_='unique')
        batch_op.drop_index('ix_mop_company_type')
        batch_op.drop_index('ix_mop_company_enabled')
        batch_op.drop_index(batch_op.f('ix_modes_of_payment_enabled'))
        batch_op.create_unique_constraint('uq_mode_of_payment_name_company_branch', ['name', 'company_id', 'branch_id'])
        batch_op.create_index('ix_modes_of_payment_branch_id', ['branch_id'], unique=False)
        batch_op.create_index('idx_mop_type', ['type'], unique=False)
        batch_op.create_index('idx_mop_default_account', ['default_account_id'], unique=False)
        batch_op.create_index('idx_mop_company_id', ['company_id'], unique=False)
        batch_op.create_index('idx_mop_branch_id', ['branch_id'], unique=False)
        batch_op.alter_column('company_id',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.drop_column('enabled')

    with op.batch_alter_table('item_prices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_item_prices_company_id'))
        batch_op.drop_index(batch_op.f('ix_item_prices_code'))
        batch_op.drop_index('ix_item_price_company_code_lookup')
        batch_op.drop_column('company_id')
        batch_op.drop_column('code')

    with op.batch_alter_table('expense_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_expense_types_enabled'))
        batch_op.drop_index('ix_expense_type_enabled')
        batch_op.create_index('ix_expense_types_is_active', ['is_active'], unique=False)
        batch_op.create_index('ix_expense_type_active', ['is_active'], unique=False)
        batch_op.drop_column('enabled')

    with op.batch_alter_table('cost_centers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint('uq_cost_center_company_branch', type_='unique')
        batch_op.create_unique_constraint('uq_cost_center_company_branch_code', ['company_id', 'branch_id', 'code'])
        batch_op.create_index('ix_cost_centers_code', ['code'], unique=False)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_center_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='The department responsible for this asset.'))
        batch_op.add_column(sa.Column('purchase_invoice_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='The source document that acquired this asset.'))
        batch_op.add_column(sa.Column('current_value', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=False, comment='Book value = Gross Purchase - Accumulated Depreciation.'))
        batch_op.add_column(sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='e.g., Draft, Submitted, Capitalized, Fully Depreciated, Sold.'))
        batch_op.add_column(sa.Column('asset_category_id', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('accumulated_depreciation', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('assets_asset_category_id_fkey', 'asset_categories', ['asset_category_id'], ['id'])
        batch_op.create_foreign_key('assets_purchase_invoice_id_fkey', 'purchase_invoices', ['purchase_invoice_id'], ['id'])
        batch_op.create_foreign_key('assets_cost_center_id_fkey', 'cost_centers', ['cost_center_id'], ['id'])
        batch_op.drop_constraint('uq_asset_company_name', type_='unique')
        batch_op.drop_index(batch_op.f('ix_assets_supplier'))
        batch_op.drop_index(batch_op.f('ix_assets_purchase_receipt'))
        batch_op.drop_index(batch_op.f('ix_assets_purchase_invoice'))
        batch_op.drop_index(batch_op.f('ix_assets_purchase_date'))
        batch_op.drop_index(batch_op.f('ix_assets_is_existing_asset'))
        batch_op.drop_index(batch_op.f('ix_assets_doc_status'))
        batch_op.drop_index(batch_op.f('ix_assets_depreciation_start_date'))
        batch_op.drop_index(batch_op.f('ix_assets_cost_center'))
        batch_op.drop_index(batch_op.f('ix_assets_calculate_depreciation'))
        batch_op.drop_index(batch_op.f('ix_assets_available_for_use_date'))
        batch_op.drop_index(batch_op.f('ix_assets_asset_status'))
        batch_op.drop_index(batch_op.f('ix_assets_asset_name'))
        batch_op.drop_index(batch_op.f('ix_assets_asset_category'))
        batch_op.drop_index('ix_asset_purchase_date')
        batch_op.drop_index('ix_asset_company_status')
        batch_op.drop_index('ix_asset_category')
        batch_op.create_unique_constraint('uq_asset_company_code', ['company_id', 'code'])
        batch_op.create_index('ix_assets_purchase_invoice_id', ['purchase_invoice_id'], unique=False)
        batch_op.create_index('ix_assets_cost_center_id', ['cost_center_id'], unique=False)
        batch_op.create_index('ix_assets_code', ['code'], unique=False)
        batch_op.create_index('ix_assets_asset_category_id', ['asset_category_id'], unique=False)
        batch_op.create_index('ix_asset_status', ['status'], unique=False)
        batch_op.alter_column('depreciation_start_date',
               existing_type=sa.DATE(),
               nullable=False,
               comment='The date depreciation calculation begins.')
        batch_op.alter_column('expected_salvage_value',
               existing_type=sa.Numeric(precision=15, scale=4),
               type_=sa.NUMERIC(precision=14, scale=4),
               nullable=False,
               comment='Residual value at the end of useful life.')
        batch_op.alter_column('gross_purchase_amount',
               existing_type=sa.Numeric(precision=15, scale=4),
               type_=sa.NUMERIC(precision=14, scale=4),
               nullable=False,
               comment='Original cost of the asset.')
        batch_op.alter_column('item_id',
               existing_type=sa.BIGINT(),
               comment='The Item master from which this asset was purchased.',
               existing_nullable=True)
        batch_op.drop_column('cost_center')
        batch_op.drop_column('asset_quantity')
        batch_op.drop_column('value_after_depreciation')
        batch_op.drop_column('is_existing_asset')
        batch_op.drop_column('calculate_depreciation')
        batch_op.drop_column('opening_accumulated_depreciation')
        batch_op.drop_column('available_for_use_date')
        batch_op.drop_column('purchase_date')
        batch_op.drop_column('supplier')
        batch_op.drop_column('purchase_invoice')
        batch_op.drop_column('purchase_receipt')
        batch_op.drop_column('location')
        batch_op.drop_column('asset_category')
        batch_op.drop_column('asset_status')
        batch_op.drop_column('doc_status')
        batch_op.drop_column('asset_name')

    with op.batch_alter_table('asset_depreciation_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posting_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('current_value_after', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('accumulated_depreciation_after', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('remarks', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_ade_asset_book_date', type_='unique')
        batch_op.drop_index(batch_op.f('ix_asset_depreciation_entries_schedule_date'))
        batch_op.drop_index(batch_op.f('ix_asset_depreciation_entries_finance_book_id'))
        batch_op.drop_index('ix_ade_asset_date')
        batch_op.create_unique_constraint('uq_ade_asset_posting_date', ['asset_id', 'posting_date'])
        batch_op.create_index('ix_asset_depreciation_entries_posting_date', ['posting_date'], unique=False)
        batch_op.alter_column('depreciation_amount',
               existing_type=sa.Numeric(precision=15, scale=4),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=False)
        batch_op.alter_column('journal_entry_id',
               existing_type=sa.BIGINT(),
               comment='The link to the actual GL Journal Entry created by this record.',
               existing_nullable=True)
        batch_op.drop_column('accumulated_depreciation_amount')
        batch_op.drop_column('schedule_date')
        batch_op.drop_column('finance_book_id')

    with op.batch_alter_table('asset_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('fixed_asset_account_id', sa.BIGINT(), autoincrement=False, nullable=False, comment='The GL account (Asset) to Debit upon acquisition (e.g., 1212 Office Equipment).'))
        batch_op.add_column(sa.Column('depreciation_expense_account_id', sa.BIGINT(), autoincrement=False, nullable=False, comment='The GL account (Expense) to Debit for depreciation (e.g., 5119 Depr. Expense).'))
        batch_op.add_column(sa.Column('accumulated_depreciation_account_id', sa.BIGINT(), autoincrement=False, nullable=False, comment='The GL account (Contra-Asset) to Credit for depreciation (e.g., 1230 Acc. Depr.).'))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('asset_categories_accumulated_depreciation_account_id_fkey', 'accounts', ['accumulated_depreciation_account_id'], ['id'])
        batch_op.create_foreign_key('asset_categories_fixed_asset_account_id_fkey', 'accounts', ['fixed_asset_account_id'], ['id'])
        batch_op.create_foreign_key('asset_categories_depreciation_expense_account_id_fkey', 'accounts', ['depreciation_expense_account_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_asset_categories_fixed_asset_account'))
        batch_op.drop_index(batch_op.f('ix_asset_categories_depreciation_expense_account'))
        batch_op.drop_index(batch_op.f('ix_asset_categories_capital_work_in_progress_account'))
        batch_op.drop_index(batch_op.f('ix_asset_categories_asset_category_name'))
        batch_op.drop_index(batch_op.f('ix_asset_categories_accumulated_depreciation_account'))
        batch_op.drop_constraint('uq_asset_category_company_name', type_='unique')
        batch_op.create_unique_constraint('uq_asset_category_company_name', ['company_id', 'name'])
        batch_op.create_unique_constraint('uq_asset_category_company_code', ['company_id', 'code'])
        batch_op.create_index('ix_asset_categories_name', ['name'], unique=False)
        batch_op.create_index('ix_asset_categories_fixed_asset_account_id', ['fixed_asset_account_id'], unique=False)
        batch_op.create_index('ix_asset_categories_depreciation_expense_account_id', ['depreciation_expense_account_id'], unique=False)
        batch_op.create_index('ix_asset_categories_code', ['code'], unique=False)
        batch_op.create_index('ix_asset_categories_accumulated_depreciation_account_id', ['accumulated_depreciation_account_id'], unique=False)
        batch_op.alter_column('depreciation_method',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=50),
               comment='e.g., Straight Line, Double Declining Balance.',
               existing_nullable=False)
        batch_op.drop_column('enable_cwip_accounting')
        batch_op.drop_column('capital_work_in_progress_account')
        batch_op.drop_column('depreciation_expense_account')
        batch_op.drop_column('accumulated_depreciation_account')
        batch_op.drop_column('fixed_asset_account')
        batch_op.drop_column('asset_category_name')

    op.create_table('account_selection_rules',
    sa.Column('company_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('branch_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('department_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('CASH_IN', 'CASH_OUT', 'TRANSFER_SOURCE', 'TRANSFER_TARGET', 'EXPENSE', name='accountuseroleenum'), autoincrement=False, nullable=False),
    sa.Column('mode_of_payment_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('rule_type', postgresql.ENUM('DEFAULT', 'ALLOW', 'BLOCK', name='accountruletypeenum'), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('parent_account_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('include_children', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("rule_type <> 'DEFAULT'::accountruletypeenum OR account_id IS NOT NULL AND parent_account_id IS NULL AND include_children = false", name='ck_accrule_default_has_account_only'),
    sa.CheckConstraint("rule_type = 'DEFAULT'::accountruletypeenum OR account_id IS NOT NULL OR parent_account_id IS NOT NULL", name='ck_accrule_allowblock_has_target'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='account_selection_rules_account_id_fkey'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='account_selection_rules_branch_id_fkey'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='account_selection_rules_company_id_fkey'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='account_selection_rules_department_id_fkey'),
    sa.ForeignKeyConstraint(['mode_of_payment_id'], ['modes_of_payment.id'], name='account_selection_rules_mode_of_payment_id_fkey'),
    sa.ForeignKeyConstraint(['parent_account_id'], ['accounts.id'], name='account_selection_rules_parent_account_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='account_selection_rules_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='account_selection_rules_pkey')
    )
    with op.batch_alter_table('account_selection_rules', schema=None) as batch_op:
        batch_op.create_index('uq_accrule_default_nomop', ['company_id', 'branch_id', 'department_id', 'user_id', 'role'], unique=True, postgresql_where="((rule_type = 'DEFAULT'::accountruletypeenum) AND (mode_of_payment_id IS NULL))")
        batch_op.create_index('uq_accrule_default_mop', ['company_id', 'branch_id', 'department_id', 'user_id', 'role', 'mode_of_payment_id'], unique=True, postgresql_where="((rule_type = 'DEFAULT'::accountruletypeenum) AND (mode_of_payment_id IS NOT NULL))")
        batch_op.create_index('uq_accrule_allow_parent', ['company_id', 'branch_id', 'department_id', 'user_id', 'role', 'mode_of_payment_id', 'parent_account_id', 'include_children'], unique=True, postgresql_where="((rule_type = 'ALLOW'::accountruletypeenum) AND (parent_account_id IS NOT NULL))")
        batch_op.create_index('uq_accrule_allow_account', ['company_id', 'branch_id', 'department_id', 'user_id', 'role', 'mode_of_payment_id', 'account_id'], unique=True, postgresql_where="((rule_type = 'ALLOW'::accountruletypeenum) AND (account_id IS NOT NULL))")
        batch_op.create_index('ix_account_selection_rules_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_account_selection_rules_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('ix_account_selection_rules_rule_type', ['rule_type'], unique=False)
        batch_op.create_index('ix_account_selection_rules_role', ['role'], unique=False)
        batch_op.create_index('ix_account_selection_rules_parent_account_id', ['parent_account_id'], unique=False)
        batch_op.create_index('ix_account_selection_rules_mode_of_payment_id', ['mode_of_payment_id'], unique=False)
        batch_op.create_index('ix_account_selection_rules_department_id', ['department_id'], unique=False)
        batch_op.create_index('ix_account_selection_rules_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_account_selection_rules_company_id', ['company_id'], unique=False)
        batch_op.create_index('ix_account_selection_rules_branch_id', ['branch_id'], unique=False)
        batch_op.create_index('ix_account_selection_rules_account_id', ['account_id'], unique=False)

    with op.batch_alter_table('asset_movement_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_movement_items_updated_at'))
        batch_op.drop_index(batch_op.f('ix_asset_movement_items_created_at'))
        batch_op.drop_index(batch_op.f('ix_asset_movement_items_asset_movement_id'))
        batch_op.drop_index(batch_op.f('ix_asset_movement_items_asset_id'))
        batch_op.drop_index('ix_ami_asset')

    op.drop_table('asset_movement_items')
    with op.batch_alter_table('asset_finance_books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_finance_books_updated_at'))
        batch_op.drop_index(batch_op.f('ix_asset_finance_books_finance_book_id'))
        batch_op.drop_index(batch_op.f('ix_asset_finance_books_depreciation_posting_date'))
        batch_op.drop_index(batch_op.f('ix_asset_finance_books_created_at'))
        batch_op.drop_index(batch_op.f('ix_asset_finance_books_asset_id'))

    op.drop_table('asset_finance_books')
    with op.batch_alter_table('mode_of_payment_accounts', schema=None) as batch_op:
        batch_op.drop_index('uq_mopa_default_per_mop', postgresql_where=sa.text('is_default = true AND enabled = true'))
        batch_op.drop_index('ix_mopa_enabled_probe')
        batch_op.drop_index(batch_op.f('ix_mode_of_payment_accounts_updated_at'))
        batch_op.drop_index(batch_op.f('ix_mode_of_payment_accounts_mode_of_payment_id'))
        batch_op.drop_index(batch_op.f('ix_mode_of_payment_accounts_is_default'))
        batch_op.drop_index(batch_op.f('ix_mode_of_payment_accounts_enabled'))
        batch_op.drop_index(batch_op.f('ix_mode_of_payment_accounts_created_at'))
        batch_op.drop_index(batch_op.f('ix_mode_of_payment_accounts_account_id'))

    op.drop_table('mode_of_payment_accounts')
    with op.batch_alter_table('account_access_policies', schema=None) as batch_op:
        batch_op.drop_index('uq_aap_unique_policy_enabled', postgresql_where=sa.text('enabled = true'))
        batch_op.drop_index(batch_op.f('ix_account_access_policies_user_id'))
        batch_op.drop_index(batch_op.f('ix_account_access_policies_updated_at'))
        batch_op.drop_index(batch_op.f('ix_account_access_policies_role'))
        batch_op.drop_index(batch_op.f('ix_account_access_policies_mode_of_payment_id'))
        batch_op.drop_index(batch_op.f('ix_account_access_policies_enabled'))
        batch_op.drop_index(batch_op.f('ix_account_access_policies_department_id'))
        batch_op.drop_index(batch_op.f('ix_account_access_policies_created_at'))
        batch_op.drop_index(batch_op.f('ix_account_access_policies_company_id'))
        batch_op.drop_index(batch_op.f('ix_account_access_policies_branch_id'))
        batch_op.drop_index(batch_op.f('ix_account_access_policies_account_id'))
        batch_op.drop_index('ix_aap_probe')

    op.drop_table('account_access_policies')
    with op.batch_alter_table('finance_books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_books_updated_at'))
        batch_op.drop_index(batch_op.f('ix_finance_books_name'))
        batch_op.drop_index(batch_op.f('ix_finance_books_created_at'))
        batch_op.drop_index(batch_op.f('ix_finance_books_company_id'))

    op.drop_table('finance_books')
    with op.batch_alter_table('asset_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_movements_updated_at'))
        batch_op.drop_index(batch_op.f('ix_asset_movements_purpose'))
        batch_op.drop_index(batch_op.f('ix_asset_movements_posting_date'))
        batch_op.drop_index(batch_op.f('ix_asset_movements_name'))
        batch_op.drop_index(batch_op.f('ix_asset_movements_doc_status'))
        batch_op.drop_index(batch_op.f('ix_asset_movements_created_at'))
        batch_op.drop_index(batch_op.f('ix_asset_movements_company_id'))
        batch_op.drop_index('ix_am_posting_date')

    op.drop_table('asset_movements')
    # ### end Alembic commands ###