"""Add only admin to workspace

Revision ID: a37a6aa39905
Revises: c463619439bc
Create Date: 2025-09-28 10:28:49.685221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a37a6aa39905'
down_revision = 'c463619439bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_only', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.create_index('ix_ws_admin_only', ['admin_only'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index('ix_ws_admin_only')
        batch_op.drop_column('admin_only')

    # ### end Alembic commands ###
