"""Added timezone on compny model)

Revision ID: af32afafcf28
Revises: 76821fd05507
Create Date: 2025-10-18 11:24:07.895321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af32afafcf28'
down_revision = '76821fd05507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True, comment="IANA Timezone string (e.g., 'America/New_York') for company operations"))

    # First ensure the enum types exist and have all values
    op.execute("""
    DO $$ 
    BEGIN 
        -- Ensure docstatusenum exists with all values
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'docstatusenum') THEN
            CREATE TYPE docstatusenum AS ENUM ('DRAFT', 'SUBMITTED', 'CANCELLED', 'UNPAID', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'RETURNED');
        ELSE
            -- Add any missing values to existing enum
            IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel = 'UNPAID' AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'docstatusenum')) THEN
                ALTER TYPE docstatusenum ADD VALUE 'UNPAID';
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel = 'PARTIALLY_PAID' AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'docstatusenum')) THEN
                ALTER TYPE docstatusenum ADD VALUE 'PARTIALLY_PAID';
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel = 'PAID' AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'docstatusenum')) THEN
                ALTER TYPE docstatusenum ADD VALUE 'PAID';
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel = 'OVERDUE' AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'docstatusenum')) THEN
                ALTER TYPE docstatusenum ADD VALUE 'OVERDUE';
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel = 'RETURNED' AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'docstatusenum')) THEN
                ALTER TYPE docstatusenum ADD VALUE 'RETURNED';
            END IF;
        END IF;

        -- Ensure paymenttypeenum exists with all values
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'paymenttypeenum') THEN
            CREATE TYPE paymenttypeenum AS ENUM ('PAY', 'RECEIVE', 'INTERNAL_TRANSFER');
        END IF;

        -- Ensure partytypeenum exists with all values including SHAREHOLDER and OTHER
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'partytypeenum') THEN
            CREATE TYPE partytypeenum AS ENUM ('CUSTOMER', 'SUPPLIER', 'EMPLOYEE', 'SHAREHOLDER', 'OTHER');
        ELSE
            -- Add SHAREHOLDER and OTHER if they don't exist
            IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel = 'SHAREHOLDER' AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'partytypeenum')) THEN
                ALTER TYPE partytypeenum ADD VALUE 'SHAREHOLDER';
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel = 'OTHER' AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'partytypeenum')) THEN
                ALTER TYPE partytypeenum ADD VALUE 'OTHER';
            END IF;
        END IF;
    END $$;
    """)

    # Convert expenses.doc_status with explicit casting
    op.execute("""
    ALTER TABLE expenses 
    ALTER COLUMN doc_status TYPE docstatusenum 
    USING CASE 
        WHEN doc_status = 'DRAFT' THEN 'DRAFT'::docstatusenum
        WHEN doc_status = 'SUBMITTED' THEN 'SUBMITTED'::docstatusenum
        WHEN doc_status = 'CANCELLED' THEN 'CANCELLED'::docstatusenum
        WHEN doc_status = 'UNPAID' THEN 'UNPAID'::docstatusenum
        WHEN doc_status = 'PARTIALLY_PAID' THEN 'PARTIALLY_PAID'::docstatusenum
        WHEN doc_status = 'PAID' THEN 'PAID'::docstatusenum
        WHEN doc_status = 'OVERDUE' THEN 'OVERDUE'::docstatusenum
        WHEN doc_status = 'RETURNED' THEN 'RETURNED'::docstatusenum
        ELSE 'DRAFT'::docstatusenum
    END;
    """)

    # Convert payment_entries.doc_status with explicit casting
    op.execute("""
    ALTER TABLE payment_entries 
    ALTER COLUMN doc_status TYPE docstatusenum 
    USING CASE 
        WHEN doc_status = 'DRAFT' THEN 'DRAFT'::docstatusenum
        WHEN doc_status = 'SUBMITTED' THEN 'SUBMITTED'::docstatusenum
        WHEN doc_status = 'CANCELLED' THEN 'CANCELLED'::docstatusenum
        WHEN doc_status = 'UNPAID' THEN 'UNPAID'::docstatusenum
        WHEN doc_status = 'PARTIALLY_PAID' THEN 'PARTIALLY_PAID'::docstatusenum
        WHEN doc_status = 'PAID' THEN 'PAID'::docstatusenum
        WHEN doc_status = 'OVERDUE' THEN 'OVERDUE'::docstatusenum
        WHEN doc_status = 'RETURNED' THEN 'RETURNED'::docstatusenum
        ELSE 'DRAFT'::docstatusenum
    END;
    """)

    # Convert payment_entries.payment_type with explicit casting
    op.execute("""
    ALTER TABLE payment_entries 
    ALTER COLUMN payment_type TYPE paymenttypeenum 
    USING CASE 
        WHEN payment_type = 'PAY' THEN 'PAY'::paymenttypeenum
        WHEN payment_type = 'RECEIVE' THEN 'RECEIVE'::paymenttypeenum
        WHEN payment_type = 'INTERNAL_TRANSFER' THEN 'INTERNAL_TRANSFER'::paymenttypeenum
        ELSE 'PAY'::paymenttypeenum
    END;
    """)

    # Convert payment_entries.party_type with explicit casting
    op.execute("""
    ALTER TABLE payment_entries 
    ALTER COLUMN party_type TYPE partytypeenum 
    USING CASE 
        WHEN party_type = 'CUSTOMER' THEN 'CUSTOMER'::partytypeenum
        WHEN party_type = 'SUPPLIER' THEN 'SUPPLIER'::partytypeenum
        WHEN party_type = 'EMPLOYEE' THEN 'EMPLOYEE'::partytypeenum
        WHEN party_type = 'SHAREHOLDER' THEN 'SHAREHOLDER'::partytypeenum
        WHEN party_type = 'OTHER' THEN 'OTHER'::partytypeenum
        ELSE NULL
    END;
    """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Convert enum columns back to VARCHAR
    op.execute("""
    ALTER TABLE payment_entries 
    ALTER COLUMN party_type TYPE VARCHAR(20) 
    USING party_type::text;
    """)

    op.execute("""
    ALTER TABLE payment_entries 
    ALTER COLUMN payment_type TYPE VARCHAR(20) 
    USING payment_type::text;
    """)

    op.execute("""
    ALTER TABLE payment_entries 
    ALTER COLUMN doc_status TYPE VARCHAR(50) 
    USING doc_status::text;
    """)

    op.execute("""
    ALTER TABLE expenses 
    ALTER COLUMN doc_status TYPE VARCHAR(50) 
    USING doc_status::text;
    """)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    # Note: We don't drop the enum types in downgrade as they might be used by other tables
    # ### end Alembic commands ###