"""add users & hr; alter columns

Revision ID: b18b2791b1ba
Revises: d3251e3ea01e
Create Date: 2025-08-27 13:43:56.796906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18b2791b1ba'
down_revision = 'd3251e3ea01e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_types',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='user_type_status_enum'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('user_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_types_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_types_updated_at'), ['updated_at'], unique=False)

    op.create_table('users',
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='user_status_enum'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_users_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('employees',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('personal_email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('img_key', sa.String(length=512), nullable=True, comment='Object-storage key/path for the encrypted image (e.g., schools/{id}/logo.enc)'),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', name='gender_enum'), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='employee_status_enum'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_employee_code_per_company')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index('ix_employees_company_branch', ['company_id', 'branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_employees_employees_img_key', ['img_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_full_name'), ['full_name'], unique=False)
        batch_op.create_index('ix_employees_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_employees_user_id', ['user_id'], unique=False)

    op.create_table('user_affiliations',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('user_type_id', sa.BigInteger(), nullable=False),
    sa.Column('linked_entity_id', sa.BigInteger(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', 'branch_id', 'user_type_id', 'linked_entity_id', name='uq_user_affiliation_scope')
    )
    with op.batch_alter_table('user_affiliations', schema=None) as batch_op:
        batch_op.create_index('ix_user_aff_entity', ['linked_entity_id'], unique=False)
        batch_op.create_index('ix_user_aff_primary', ['user_id', 'is_primary'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_affiliations_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_affiliations_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_affiliations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_affiliations_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_affiliations_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_affiliations_user_type_id'), ['user_type_id'], unique=False)

    op.create_table('employee_emergency_contacts',
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('relationship_type', sa.Enum('FATHER', 'MOTHER', 'GUARDIAN', 'CHILD', 'OTHER', name='person_relationship_enum'), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee_emergency_contacts', schema=None) as batch_op:
        batch_op.create_index('ix_emp_ec_employee_rel', ['employee_id', 'relationship_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_emergency_contacts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_emergency_contacts_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_emergency_contacts_relationship_type'), ['relationship_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_emergency_contacts_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.BIGINT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.BIGINT(),
               nullable=False)

    with op.batch_alter_table('employee_emergency_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_emergency_contacts_updated_at'))
        batch_op.drop_index(batch_op.f('ix_employee_emergency_contacts_relationship_type'))
        batch_op.drop_index(batch_op.f('ix_employee_emergency_contacts_employee_id'))
        batch_op.drop_index(batch_op.f('ix_employee_emergency_contacts_created_at'))
        batch_op.drop_index('ix_emp_ec_employee_rel')

    op.drop_table('employee_emergency_contacts')
    with op.batch_alter_table('user_affiliations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_affiliations_user_type_id'))
        batch_op.drop_index(batch_op.f('ix_user_affiliations_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_affiliations_updated_at'))
        batch_op.drop_index(batch_op.f('ix_user_affiliations_created_at'))
        batch_op.drop_index(batch_op.f('ix_user_affiliations_company_id'))
        batch_op.drop_index(batch_op.f('ix_user_affiliations_branch_id'))
        batch_op.drop_index('ix_user_aff_primary')
        batch_op.drop_index('ix_user_aff_entity')

    op.drop_table('user_affiliations')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index('ix_employees_user_id')
        batch_op.drop_index(batch_op.f('ix_employees_updated_at'))
        batch_op.drop_index('ix_employees_status')
        batch_op.drop_index(batch_op.f('ix_employees_full_name'))
        batch_op.drop_index('ix_employees_employees_img_key')
        batch_op.drop_index(batch_op.f('ix_employees_created_at'))
        batch_op.drop_index(batch_op.f('ix_employees_company_id'))
        batch_op.drop_index('ix_employees_company_branch')
        batch_op.drop_index(batch_op.f('ix_employees_branch_id'))

    op.drop_table('employees')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_updated_at'))
        batch_op.drop_index('ix_users_status')
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('user_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_types_updated_at'))
        batch_op.drop_index(batch_op.f('ix_user_types_created_at'))

    op.drop_table('user_types')
    # ### end Alembic commands ###
