"""Add date fields to Purchase/Invoice model: post_date for backend logic and ui_select_date for user selection.

Revision ID: c2c29db3baed
Revises: 6a519c15df88
Create Date: 2025-10-09 07:57:43.788895
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c2c29db3baed'
down_revision = '6a519c15df88'
branch_labels = None
depends_on = None


def table_exists(table_name):
    """Check if a table exists in the database"""
    conn = op.get_bind()
    result = conn.execute(sa.text(f"""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = '{table_name}'
        );
    """)).scalar()
    return result


def column_exists(table_name, column_name):
    """Check if a column exists in a table"""
    conn = op.get_bind()
    result = conn.execute(sa.text(f"""
        SELECT EXISTS (
            SELECT FROM information_schema.columns 
            WHERE table_schema = 'public' 
            AND table_name = '{table_name}'
            AND column_name = '{column_name}'
        );
    """)).scalar()
    return result


def index_exists(index_name):
    """Check if an index exists"""
    conn = op.get_bind()
    result = conn.execute(sa.text(f"""
        SELECT EXISTS (
            SELECT FROM pg_indexes 
            WHERE schemaname = 'public' 
            AND indexname = '{index_name}'
        );
    """)).scalar()
    return result


def constraint_exists(constraint_name, table_name):
    """Check if a constraint exists"""
    conn = op.get_bind()
    result = conn.execute(sa.text(f"""
        SELECT EXISTS (
            SELECT FROM information_schema.table_constraints 
            WHERE constraint_schema = 'public' 
            AND table_name = '{table_name}'
            AND constraint_name = '{constraint_name}'
        );
    """)).scalar()
    return result


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Create item_groups table (CRITICAL - this was missing)
    if not table_exists('item_groups'):
        op.create_table('item_groups',
            sa.Column('id', sa.BigInteger(), nullable=False),
            sa.Column('company_id', sa.BigInteger(), nullable=False),
            sa.Column('name', sa.String(length=255), nullable=False),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('is_group', sa.Boolean(), nullable=False),
            sa.Column('parent_id', sa.BigInteger(), nullable=True),
            sa.Column('default_income_account_id', sa.BigInteger(), nullable=True),
            sa.Column('default_expense_account_id', sa.BigInteger(), nullable=True),
            sa.Column('default_inventory_account_id', sa.BigInteger(), nullable=True),
            sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
            sa.ForeignKeyConstraint(['default_expense_account_id'], ['accounts.id'], ),
            sa.ForeignKeyConstraint(['default_income_account_id'], ['accounts.id'], ),
            sa.ForeignKeyConstraint(['default_inventory_account_id'], ['accounts.id'], ),
            sa.ForeignKeyConstraint(['parent_id'], ['item_groups.id'], ),
            sa.PrimaryKeyConstraint('id')
        )

    # 2. Add item_group_id to items table
    if table_exists('items') and not column_exists('items', 'item_group_id'):
        op.add_column('items', sa.Column('item_group_id', sa.BigInteger(), nullable=True))

    if table_exists('items') and table_exists('item_groups') and not constraint_exists('fk_items_item_group_id', 'items'):
        op.create_foreign_key('fk_items_item_group_id', 'items', 'item_groups', ['item_group_id'], ['id'])

    # 3. Add asset_category_id and is_fixed_asset to items table
    if table_exists('items') and not column_exists('items', 'asset_category_id'):
        op.add_column('items', sa.Column('asset_category_id', sa.BigInteger(), nullable=True))

    if table_exists('items') and not column_exists('items', 'is_fixed_asset'):
        op.add_column('items', sa.Column('is_fixed_asset', sa.Boolean(), nullable=True))

    # 4. Add dated fields to purchase invoices and receipts
    if table_exists('purchase_invoices') and not column_exists('purchase_invoices', 'dated'):
        op.add_column('purchase_invoices',
            sa.Column('dated', sa.DateTime(timezone=True), nullable=True)
        )

    if table_exists('purchase_receipts') and not column_exists('purchase_receipts', 'dated'):
        op.add_column('purchase_receipts',
            sa.Column('dated', sa.DateTime(timezone=True), nullable=True)
        )

    # 5. Add returned_qty fields
    if table_exists('purchase_invoice_items') and not column_exists('purchase_invoice_items', 'returned_qty'):
        op.add_column('purchase_invoice_items',
            sa.Column('returned_qty', sa.Numeric(precision=12, scale=3),
                     server_default=sa.text('0'), nullable=False)
        )

    if table_exists('purchase_receipt_items') and not column_exists('purchase_receipt_items', 'returned_qty'):
        op.add_column('purchase_receipt_items',
            sa.Column('returned_qty', sa.Numeric(precision=12, scale=3),
                     server_default=sa.text('0'), nullable=False)
        )

    # 6. Create simple indexes (ONLY for tables that exist)
    if table_exists('purchase_invoices') and not index_exists('ix_purchase_invoices_dated'):
        op.create_index('ix_purchase_invoices_dated', 'purchase_invoices', ['dated'], unique=False)

    if table_exists('purchase_receipts') and not index_exists('ix_purchase_receipts_dated'):
        op.create_index('ix_purchase_receipts_dated', 'purchase_receipts', ['dated'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop indexes if they exist
    if index_exists('ix_purchase_receipts_dated'):
        op.drop_index('ix_purchase_receipts_dated', table_name='purchase_receipts')

    if index_exists('ix_purchase_invoices_dated'):
        op.drop_index('ix_purchase_invoices_dated', table_name='purchase_invoices')

    # Drop columns if they exist
    if table_exists('purchase_receipt_items') and column_exists('purchase_receipt_items', 'returned_qty'):
        op.drop_column('purchase_receipt_items', 'returned_qty')

    if table_exists('purchase_invoice_items') and column_exists('purchase_invoice_items', 'returned_qty'):
        op.drop_column('purchase_invoice_items', 'returned_qty')

    if table_exists('purchase_receipts') and column_exists('purchase_receipts', 'dated'):
        op.drop_column('purchase_receipts', 'dated')

    if table_exists('purchase_invoices') and column_exists('purchase_invoices', 'dated'):
        op.drop_column('purchase_invoices', 'dated')

    if table_exists('items') and column_exists('items', 'is_fixed_asset'):
        op.drop_column('items', 'is_fixed_asset')

    if table_exists('items') and column_exists('items', 'asset_category_id'):
        op.drop_column('items', 'asset_category_id')

    # Drop foreign key constraint if it exists
    if table_exists('items') and constraint_exists('fk_items_item_group_id', 'items'):
        op.drop_constraint('fk_items_item_group_id', 'items', type_='foreignkey')

    if table_exists('items') and column_exists('items', 'item_group_id'):
        op.drop_column('items', 'item_group_id')

    # Drop table if it exists (be careful with this in production)
    if table_exists('item_groups'):
        op.drop_table('item_groups')

    # ### end Alembic commands ###