"""Add date fields to Purchase/Invoice model: post_date for backend logic and ui_select_date for user selection.

Revision ID: c2c29db3baed
Revises: 6a519c15df88
Create Date: 2025-10-09 07:57:43.788895
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c2c29db3baed'
down_revision = '6a519c15df88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_categories', schema=None) as batch_op:
        batch_op.alter_column(
            'accumulated_depreciation_account_id',
            existing_type=sa.BIGINT(),
            comment='The GL account (Contra-Asset) to Credit for depreciation (e.g., 1230 Acc. Depr.).',
            existing_comment='The GL account (Contra-Asset) to Credit for depreciation.',
            existing_nullable=False,
        )
        batch_op.alter_column(
            'depreciation_expense_account_id',
            existing_type=sa.BIGINT(),
            comment='The GL account (Expense) to Debit for depreciation (e.g., 5119 Depr. Expense).',
            existing_comment='The GL account (Expense) to Debit for depreciation.',
            existing_nullable=False,
        )
        batch_op.alter_column(
            'depreciation_method',
            existing_type=sa.VARCHAR(length=50),
            comment='e.g., Straight Line, Double Declining Balance.',
            existing_nullable=False,
        )

    with op.batch_alter_table('asset_depreciation_entries', schema=None) as batch_op:
        batch_op.alter_column(
            'journal_entry_id',
            existing_type=sa.BIGINT(),
            comment='The link to the actual GL Journal Entry created by this record.',
            existing_nullable=True,
        )

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column(
            'purchase_invoice_id',
            existing_type=sa.BIGINT(),
            comment='The source document that acquired this asset.',
            existing_nullable=True,
        )
        batch_op.alter_column(
            'item_id',
            existing_type=sa.BIGINT(),
            comment='The Item master from which this asset was purchased.',
            existing_nullable=True,
        )
        batch_op.alter_column(
            'cost_center_id',
            existing_type=sa.BIGINT(),
            comment='The department responsible for this asset.',
            existing_nullable=True,
        )
        batch_op.alter_column(
            'gross_purchase_amount',
            existing_type=sa.NUMERIC(precision=14, scale=4),
            comment='Original cost of the asset.',
            existing_nullable=False,
        )
        batch_op.alter_column(
            'expected_salvage_value',
            existing_type=sa.NUMERIC(precision=14, scale=4),
            comment='Residual value at the end of useful life.',
            existing_nullable=False,
        )
        batch_op.alter_column(
            'depreciation_start_date',
            existing_type=sa.DATE(),
            comment='The date depreciation calculation begins.',
            existing_nullable=False,
        )
        batch_op.alter_column(
            'current_value',
            existing_type=sa.NUMERIC(precision=14, scale=4),
            comment='Book value = Gross Purchase - Accumulated Depreciation.',
            existing_nullable=False,
        )
        batch_op.alter_column(
            'status',
            existing_type=sa.VARCHAR(length=50),
            comment='e.g., Draft, Submitted, Capitalized, Fully Depreciated, Sold.',
            existing_nullable=False,
        )

    # ---------- SAFE BACKFILL: general_ledger_entries.fiscal_year_id ----------
    conn = op.get_bind()

    # Backfill by matching company + posting_date to fiscal_years range
    conn.execute(sa.text("""
        UPDATE general_ledger_entries gl
        SET fiscal_year_id = fy.id
        FROM fiscal_years fy
        WHERE gl.fiscal_year_id IS NULL
          AND fy.company_id = gl.company_id
          AND (gl.posting_date)::date BETWEEN fy.start_date AND fy.end_date
    """))

    # Verify no NULLs remain
    remaining_fy_nulls = conn.execute(sa.text(
        "SELECT COUNT(*) FROM general_ledger_entries WHERE fiscal_year_id IS NULL"
    )).scalar()
    if remaining_fy_nulls and remaining_fy_nulls > 0:
        sample = conn.execute(sa.text("""
            SELECT id, company_id, (posting_date)::date AS posting_date
            FROM general_ledger_entries
            WHERE fiscal_year_id IS NULL
            ORDER BY posting_date
            LIMIT 10
        """)).fetchall()
        raise RuntimeError(
            "Cannot set NOT NULL on general_ledger_entries.fiscal_year_id: "
            f"{remaining_fy_nulls} rows still NULL. "
            f"Seed missing fiscal years. Sample rows: {sample}"
        )

    with op.batch_alter_table('general_ledger_entries', schema=None) as batch_op:
        batch_op.alter_column(
            'fiscal_year_id',
            existing_type=sa.BIGINT(),
            nullable=False,
        )

    with op.batch_alter_table('item_groups', schema=None) as batch_op:
        batch_op.alter_column(
            'is_group',
            existing_type=sa.BOOLEAN(),
            comment='True if this is a parent node, False if it holds items.',
            existing_comment='True if parent node.',
            existing_nullable=False,
        )
        batch_op.alter_column(
            'default_expense_account_id',
            existing_type=sa.BIGINT(),
            comment='Default account for expense/COGS when buying/selling items in this group.',
            existing_nullable=True,
        )
        batch_op.alter_column(
            'default_income_account_id',
            existing_type=sa.BIGINT(),
            comment='Default Income/Sales account.',
            existing_nullable=True,
        )
        batch_op.alter_column(
            'default_inventory_account_id',
            existing_type=sa.BIGINT(),
            comment='Default Inventory Asset (Stocks in Hand) account.',
            existing_nullable=True,
        )

    with op.batch_alter_table('item_prices', schema=None) as batch_op:
        batch_op.create_index(
            'ix_item_price_branch_null',
            ['price_list_id', 'item_id', 'uom_id', 'valid_from', 'valid_upto'],
            unique=False,
            postgresql_where=sa.text('branch_id IS NULL'),
        )
        batch_op.create_index(
            'ix_item_price_branch_some',
            ['price_list_id', 'item_id', 'uom_id', 'branch_id', 'valid_from', 'valid_upto'],
            unique=False,
            postgresql_where=sa.text('branch_id IS NOT NULL'),
        )
        batch_op.create_index(
            'ix_item_price_lookup_full',
            ['price_list_id', 'item_id', 'uom_id', 'branch_id', 'valid_from', 'valid_upto'],
            unique=False,
            postgresql_include=['rate'],
        )

    # ---------- SAFE BACKFILL: items.item_group_id ----------
    # Assign NULL item_group_id to an existing group in the same company (prefer leaf: is_group = false)
    conn.execute(sa.text("""
        WITH picks AS (
            SELECT ig.company_id,
                   ig.id,
                   ROW_NUMBER() OVER (
                       PARTITION BY ig.company_id
                       ORDER BY CASE WHEN ig.is_group THEN 1 ELSE 0 END, ig.id
                   ) AS rn
            FROM item_groups ig
        )
        UPDATE items i
        SET item_group_id = p.id
        FROM picks p
        WHERE i.item_group_id IS NULL
          AND p.company_id = i.company_id
          AND p.rn = 1
    """))

    remaining_item_group_nulls = conn.execute(sa.text(
        "SELECT COUNT(*) FROM items WHERE item_group_id IS NULL"
    )).scalar()
    if remaining_item_group_nulls and remaining_item_group_nulls > 0:
        missing_companies = conn.execute(sa.text("""
            SELECT DISTINCT company_id
            FROM items
            WHERE item_group_id IS NULL
            ORDER BY company_id
        """)).fetchall()
        raise RuntimeError(
            "Cannot set NOT NULL on items.item_group_id: "
            f"{remaining_item_group_nulls} rows still NULL. "
            f"Seed at least one item group for companies: {missing_companies}"
        )

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column(
            'item_group_id',
            existing_type=sa.BIGINT(),
            nullable=False,
            existing_comment='Mandatory link for inheriting accounting and inventory rules.',
        )

    with op.batch_alter_table('period_closing_vouchers', schema=None) as batch_op:
        batch_op.alter_column(
            'closing_fiscal_year_id',
            existing_type=sa.BIGINT(),
            comment='The Fiscal Year being closed.',
            existing_nullable=False,
        )
        batch_op.alter_column(
            'closing_account_head_id',
            existing_type=sa.BIGINT(),
            comment='The Equity account (Retained Earnings) to book P&L.',
            existing_nullable=False,
        )
        batch_op.alter_column(
            'generated_journal_entry_id',
            existing_type=sa.BIGINT(),
            comment='The final Journal Entry for the closing process.',
            existing_nullable=True,
        )
        batch_op.alter_column(
            'submitted_by_id',
            existing_type=sa.BIGINT(),
            comment='The User who submitted the voucher (required for SUBMITTED status).',
            existing_nullable=True,
        )
        batch_op.alter_column(
            'code',
            existing_type=sa.VARCHAR(length=100),
            comment='Unique document identifier.',
            existing_nullable=False,
        )
        batch_op.alter_column(
            'posting_date',
            existing_type=postgresql.TIMESTAMP(timezone=True),
            comment='The effective date of the closing entry.',
            existing_nullable=False,
        )
        batch_op.alter_column(
            'auto_prepared',
            existing_type=sa.BOOLEAN(),
            comment='True if system created this document as a DRAFT for human review.',
            existing_nullable=False,
        )
        batch_op.alter_column(
            'total_profit_loss',
            existing_type=sa.NUMERIC(precision=14, scale=4),
            comment='Calculated Net P/L for the year.',
            existing_nullable=False,
        )
        batch_op.create_index(batch_op.f('ix_period_closing_vouchers_updated_at'), ['updated_at'], unique=False)

    # ---------- SAFE ADD: purchase_invoice_items.returned_qty (NOT NULL) ----------
    with op.batch_alter_table('purchase_invoice_items', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'returned_qty',
                sa.Numeric(precision=12, scale=3),
                server_default=sa.text('0'),
                nullable=False,
                comment='Total quantity returned against this standard Invoice Item (via linked Debit Notes).',
            )
        )
        batch_op.alter_column('returned_qty', server_default=None)

    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'dated',
                sa.DateTime(timezone=True),
                nullable=True,
                comment="User-selected date for display (like ERPNext 'Dated' field)",
            )
        )
        batch_op.alter_column(
            'payable_account_id',
            existing_type=sa.BIGINT(),
            comment='The Accounts Payable (Liability) account used for the Credit posting.',
            existing_nullable=False,
        )
        batch_op.alter_column(
            'posting_date',
            existing_type=postgresql.TIMESTAMP(timezone=True),
            comment="System-determined date for stock/accounting (like ERPNext 'Date')",
            existing_nullable=False,
        )
        batch_op.create_index(batch_op.f('ix_purchase_invoices_dated'), ['dated'], unique=False)

    # ---------- SAFE ADD: purchase_receipt_items.returned_qty (NOT NULL) ----------
    with op.batch_alter_table('purchase_receipt_items', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'returned_qty',
                sa.Numeric(precision=12, scale=3),
                server_default=sa.text('0'),
                nullable=False,
                comment='Total quantity returned against this item line',
            )
        )
        batch_op.alter_column('returned_qty', server_default=None)

    with op.batch_alter_table('purchase_receipts', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'dated',
                sa.DateTime(timezone=True),
                nullable=True,
                comment="User-selected date for display (like ERPNext 'Dated' field)",
            )
        )
        batch_op.alter_column(
            'posting_date',
            existing_type=postgresql.TIMESTAMP(timezone=True),
            comment="System-determined date for stock/accounting (like ERPNext 'Date')",
            existing_nullable=False,
        )
        batch_op.create_index(batch_op.f('ix_purchase_receipts_dated'), ['dated'], unique=False)

    # ---------- SAFE BACKFILL: stock_ledger_entries.base_uom_id ----------
    conn.execute(sa.text("""
        UPDATE stock_ledger_entries sle
        SET base_uom_id = it.base_uom_id
        FROM items it
        WHERE sle.base_uom_id IS NULL
          AND sle.item_id = it.id
    """))
    remaining_uom_nulls = conn.execute(sa.text(
        "SELECT COUNT(*) FROM stock_ledger_entries WHERE base_uom_id IS NULL"
    )).scalar()
    if remaining_uom_nulls and remaining_uom_nulls > 0:
        raise RuntimeError(
            "Cannot set NOT NULL on stock_ledger_entries.base_uom_id: "
            f"{remaining_uom_nulls} rows still NULL (check orphan SLEs without matching items)."
        )

    with op.batch_alter_table('stock_ledger_entries', schema=None) as batch_op:
        batch_op.alter_column(
            'base_uom_id',
            existing_type=sa.BIGINT(),
            nullable=False,
            existing_comment='Base UOM for the item (stock UOM)',
        )
        batch_op.alter_column(
            'transaction_uom_id',
            existing_type=sa.BIGINT(),
            comment='UOM used in the transaction (for UOM conversion tracking)',
            existing_comment='UOM used in the transaction',
            existing_nullable=True,
        )
        batch_op.alter_column(
            'transaction_quantity',
            existing_type=sa.NUMERIC(precision=18, scale=6),
            comment='Quantity in transaction UOM (before conversion)',
            existing_comment='Quantity in transaction UOM',
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_ledger_entries', schema=None) as batch_op:
        batch_op.alter_column(
            'transaction_quantity',
            existing_type=sa.NUMERIC(precision=18, scale=6),
            comment='Quantity in transaction UOM',
            existing_comment='Quantity in transaction UOM (before conversion)',
            existing_nullable=True,
        )
        batch_op.alter_column(
            'transaction_uom_id',
            existing_type=sa.BIGINT(),
            comment='UOM used in the transaction',
            existing_comment='UOM used in the transaction (for UOM conversion tracking)',
            existing_nullable=True,
        )
        batch_op.alter_column(
            'base_uom_id',
            existing_type=sa.BIGINT(),
            nullable=True,
            existing_comment='Base UOM for the item (stock UOM)',
        )

    with op.batch_alter_table('purchase_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_receipts_dated'))
        batch_op.alter_column(
            'posting_date',
            existing_type=postgresql.TIMESTAMP(timezone=True),
            comment=None,
            existing_comment="System-determined date for stock/accounting (like ERPNext 'Date')",
            existing_nullable=False,
        )
        batch_op.drop_column('dated')

    with op.batch_alter_table('purchase_receipt_items', schema=None) as batch_op:
        batch_op.drop_column('returned_qty')

    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_invoices_dated'))
        batch_op.alter_column(
            'posting_date',
            existing_type=postgresql.TIMESTAMP(timezone=True),
            comment=None,
            existing_comment="System-determined date for stock/accounting (like ERPNext 'Date')",
            existing_nullable=False,
        )
        batch_op.alter_column(
            'payable_account_id',
            existing_type=sa.BIGINT(),
            comment=None,
            existing_comment='The Accounts Payable (Liability) account used for the Credit posting.',
            existing_nullable=False,
        )
        batch_op.drop_column('dated')

    with op.batch_alter_table('purchase_invoice_items', schema=None) as batch_op:
        batch_op.drop_column('returned_qty')

    with op.batch_alter_table('period_closing_vouchers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_period_closing_vouchers_updated_at'))
        batch_op.alter_column(
            'total_profit_loss',
            existing_type=sa.NUMERIC(precision=14, scale=4),
            comment=None,
            existing_comment='Calculated Net P/L for the year.',
            existing_nullable=False,
        )
        batch_op.alter_column(
            'auto_prepared',
            existing_type=sa.BOOLEAN(),
            comment=None,
            existing_comment='True if system created this document as a DRAFT for human review.',
            existing_nullable=False,
        )
        batch_op.alter_column(
            'posting_date',
            existing_type=postgresql.TIMESTAMP(timezone=True),
            comment=None,
            existing_comment='The effective date of the closing entry.',
            existing_nullable=False,
        )
        batch_op.alter_column(
            'code',
            existing_type=sa.VARCHAR(length=100),
            comment=None,
            existing_comment='Unique document identifier.',
            existing_nullable=False,
        )
        batch_op.alter_column(
            'submitted_by_id',
            existing_type=sa.BIGINT(),
            comment=None,
            existing_comment='The User who submitted the voucher (required for SUBMITTED status).',
            existing_nullable=True,
        )
        batch_op.alter_column(
            'generated_journal_entry_id',
            existing_type=sa.BIGINT(),
            comment=None,
            existing_comment='The final Journal Entry for the closing process.',
            existing_nullable=True,
        )
        batch_op.alter_column(
            'closing_account_head_id',
            existing_type=sa.BIGINT(),
            comment=None,
            existing_comment='The Equity account (Retained Earnings) to book P&L.',
            existing_nullable=False,
        )
        batch_op.alter_column(
            'closing_fiscal_year_id',
            existing_type=sa.BIGINT(),
            comment=None,
            existing_comment='The Fiscal Year being closed.',
            existing_nullable=False,
        )

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column(
            'item_group_id',
            existing_type=sa.BIGINT(),
            nullable=True,
            existing_comment='Mandatory link for inheriting accounting and inventory rules.',
        )

    with op.batch_alter_table('item_prices', schema=None) as batch_op:
        batch_op.drop_index('ix_item_price_lookup_full', postgresql_include=['rate'])
        batch_op.drop_index('ix_item_price_branch_some', postgresql_where=sa.text('branch_id IS NOT NULL'))
        batch_op.drop_index('ix_item_price_branch_null', postgresql_where=sa.text('branch_id IS NULL'))

    with op.batch_alter_table('item_groups', schema=None) as batch_op:
        batch_op.alter_column(
            'default_inventory_account_id',
            existing_type=sa.BIGINT(),
            comment=None,
            existing_comment='Default Inventory Asset (Stocks in Hand) account.',
            existing_nullable=True,
        )
        batch_op.alter_column(
            'default_income_account_id',
            existing_type=sa.BIGINT(),
            comment=None,
            existing_comment='Default Income/Sales account.',
            existing_nullable=True,
        )
        batch_op.alter_column(
            'default_expense_account_id',
            existing_type=sa.BIGINT(),
            comment=None,
            existing_comment='Default account for expense/COGS when buying/selling items in this group.',
            existing_nullable=True,
        )
        batch_op.alter_column(
            'is_group',
            existing_type=sa.BOOLEAN(),
            comment='True if parent node.',
            existing_comment='True if this is a parent node, False if it holds items.',
            existing_nullable=False,
        )

    with op.batch_alter_table('general_ledger_entries', schema=None) as batch_op:
        batch_op.alter_column(
            'fiscal_year_id',
            existing_type=sa.BIGINT(),
            nullable=True,
        )

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column(
            'status',
            existing_type=sa.VARCHAR(length=50),
            comment=None,
            existing_comment='e.g., Draft, Submitted, Capitalized, Fully Depreciated, Sold.',
            existing_nullable=False,
        )
        batch_op.alter_column(
            'current_value',
            existing_type=sa.NUMERIC(precision=14, scale=4),
            comment=None,
            existing_comment='Book value = Gross Purchase - Accumulated Depreciation.',
            existing_nullable=False,
        )
        batch_op.alter_column(
            'depreciation_start_date',
            existing_type=sa.DATE(),
            comment=None,
            existing_comment='The date depreciation calculation begins.',
            existing_nullable=False,
        )
        batch_op.alter_column(
            'expected_salvage_value',
            existing_type=sa.NUMERIC(precision=14, scale=4),
            comment=None,
            existing_comment='Residual value at the end of useful life.',
            existing_nullable=False,
        )
        batch_op.alter_column(
            'gross_purchase_amount',
            existing_type=sa.NUMERIC(precision=14, scale=4),
            comment=None,
            existing_comment='Original cost of the asset.',
            existing_nullable=False,
        )
        batch_op.alter_column(
            'cost_center_id',
            existing_type=sa.BIGINT(),
            comment=None,
            existing_comment='The department responsible for this asset.',
            existing_nullable=True,
        )
        batch_op.alter_column(
            'item_id',
            existing_type=sa.BIGINT(),
            comment=None,
            existing_comment='The Item master from which this asset was purchased.',
            existing_nullable=True,
        )
        batch_op.alter_column(
            'purchase_invoice_id',
            existing_type=sa.BIGINT(),
            comment=None,
            existing_comment='The source document that acquired this asset.',
            existing_nullable=True,
        )

    with op.batch_alter_table('asset_depreciation_entries', schema=None) as batch_op:
        batch_op.alter_column(
            'journal_entry_id',
            existing_type=sa.BIGINT(),
            comment=None,
            existing_comment='The link to the actual GL Journal Entry created by this record.',
            existing_nullable=True,
        )

    with op.batch_alter_table('asset_categories', schema=None) as batch_op:
        batch_op.alter_column(
            'depreciation_method',
            existing_type=sa.VARCHAR(length=50),
            comment=None,
            existing_comment='e.g., Straight Line, Double Declining Balance.',
            existing_nullable=False,
        )
        batch_op.alter_column(
            'depreciation_expense_account_id',
            existing_type=sa.BIGINT(),
            comment='The GL account (Expense) to Debit for depreciation.',
            existing_comment='The GL account (Expense) to Debit for depreciation (e.g., 5119 Depr. Expense).',
            existing_nullable=False,
        )
        batch_op.alter_column(
            'accumulated_depreciation_account_id',
            existing_type=sa.BIGINT(),
            comment='The GL account (Contra-Asset) to Credit for depreciation.',
            existing_comment='The GL account (Contra-Asset) to Credit for depreciation (e.g., 1230 Acc. Depr.).',
            existing_nullable=False,
        )
    # ### end Alembic commands ###
