"""init

Revision ID: d3251e3ea01e
Revises: 
Create Date: 2025-08-26 14:55:22.204798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3251e3ea01e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('headquarters_address', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='company_status_enum'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_phone')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_contact_email'), ['contact_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_companies_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_companies_updated_at'), ['updated_at'], unique=False)

    op.create_table('branches',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('is_hq', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='branch_status_enum'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('company_id', 'name', name='uq_branch_name_per_company')
    )
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branches_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_branches_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_branches_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branches_updated_at'))
        batch_op.drop_index(batch_op.f('ix_branches_created_at'))
        batch_op.drop_index(batch_op.f('ix_branches_company_id'))

    op.drop_table('branches')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_updated_at'))
        batch_op.drop_index(batch_op.f('ix_companies_name'))
        batch_op.drop_index(batch_op.f('ix_companies_created_at'))
        batch_op.drop_index(batch_op.f('ix_companies_contact_email'))

    op.drop_table('companies')
    # ### end Alembic commands ###
