"""created new model code genrteder and update

Revision ID: d431914a495f
Revises: 1f2a6d283eb3
Create Date: 2025-08-29 11:03:08.047104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd431914a495f'
down_revision = '1f2a6d283eb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cities_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cities_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_cities_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('ix_cities_updated_at'), ['updated_at'], unique=False)

    op.create_table('code_types',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('prefix', sa.String(length=50), nullable=False),
    sa.Column('pattern', sa.String(length=120), nullable=False),
    sa.Column('scope', sa.Enum('GLOBAL', 'COMPANY', 'BRANCH', name='code_scope_enum'), nullable=False),
    sa.Column('reset_policy', sa.Enum('NEVER', 'YEARLY', 'MONTHLY', name='code_reset_policy_enum'), nullable=False),
    sa.Column('padding', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('code_types', schema=None) as batch_op:
        batch_op.create_index('ix_code_type_name_prefix', ['name', 'prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_types_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_types_prefix'), ['prefix'], unique=True)
        batch_op.create_index(batch_op.f('ix_code_types_reset_policy'), ['reset_policy'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_types_scope'), ['scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_types_updated_at'), ['updated_at'], unique=False)

    op.create_table('code_counters',
    sa.Column('code_type_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('period_key', sa.String(length=20), nullable=True),
    sa.Column('last_sequence_number', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['code_type_id'], ['code_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_type_id', 'company_id', 'branch_id', 'period_key', name='uq_code_counter_partition')
    )
    with op.batch_alter_table('code_counters', schema=None) as batch_op:
        batch_op.create_index('ix_code_counter_branch', ['branch_id'], unique=False)
        batch_op.create_index('ix_code_counter_company', ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_counters_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_counters_code_type_id'), ['code_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_counters_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_counters_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_counters_period_key'), ['period_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_counters_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('prefix', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_companies_city_id'), ['city_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_prefix'), ['prefix'], unique=True)
        batch_op.create_foreign_key(None, 'cities', ['city_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_companies_prefix'))
        batch_op.drop_index(batch_op.f('ix_companies_city_id'))
        batch_op.drop_column('prefix')
        batch_op.drop_column('city_id')

    with op.batch_alter_table('code_counters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_counters_updated_at'))
        batch_op.drop_index(batch_op.f('ix_code_counters_period_key'))
        batch_op.drop_index(batch_op.f('ix_code_counters_created_at'))
        batch_op.drop_index(batch_op.f('ix_code_counters_company_id'))
        batch_op.drop_index(batch_op.f('ix_code_counters_code_type_id'))
        batch_op.drop_index(batch_op.f('ix_code_counters_branch_id'))
        batch_op.drop_index('ix_code_counter_company')
        batch_op.drop_index('ix_code_counter_branch')

    op.drop_table('code_counters')
    with op.batch_alter_table('code_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_types_updated_at'))
        batch_op.drop_index(batch_op.f('ix_code_types_scope'))
        batch_op.drop_index(batch_op.f('ix_code_types_reset_policy'))
        batch_op.drop_index(batch_op.f('ix_code_types_prefix'))
        batch_op.drop_index(batch_op.f('ix_code_types_created_at'))
        batch_op.drop_index('ix_code_type_name_prefix')

    op.drop_table('code_types')
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cities_updated_at'))
        batch_op.drop_index(batch_op.f('ix_cities_region'))
        batch_op.drop_index(batch_op.f('ix_cities_name'))
        batch_op.drop_index(batch_op.f('ix_cities_created_at'))

    op.drop_table('cities')
    # ### end Alembic commands ###
