"""update code unique on warehouse model

Revision ID: dd03ade3a566
Revises: e10a918f6a7f
Create Date: 2025-12-09 12:05:31.445727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd03ade3a566'
down_revision = 'e10a918f6a7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_index('ix_warehouses_code')
        batch_op.create_index(batch_op.f('ix_warehouses_code'), ['code'], unique=False)
        batch_op.create_unique_constraint('uq_wh_company_code', ['company_id', 'code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_constraint('uq_wh_company_code', type_='unique')
        batch_op.drop_index(batch_op.f('ix_warehouses_code'))
        batch_op.create_index('ix_warehouses_code', ['code'], unique=True)

    # ### end Alembic commands ###
