"""Added core ERP models for parties, inventory, buying, and sales.

Revision ID: ddf44f800cb3
Revises: 03d717565cf9
Create Date: 2025-09-03 22:36:24.364037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf44f800cb3'
down_revision = '03d717565cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_types',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('domain', sa.Enum('INVENTORY', 'FINANCE', 'ASSETS', 'PAYROLL', 'OTHER', name='document_domain_enum'), nullable=False),
    sa.Column('affects_stock', sa.Boolean(), nullable=False),
    sa.Column('affects_gl', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='statusenum'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_types_affects_gl'), ['affects_gl'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_types_affects_stock'), ['affects_stock'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_types_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_document_types_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_types_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_types_updated_at'), ['updated_at'], unique=False)

    op.create_table('brands',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='statusenum'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_brand_company_name')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brands_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brands_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_brands_updated_at'), ['updated_at'], unique=False)

    op.create_table('units_of_measure',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='statusenum'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_uom_company_name')
    )
    with op.batch_alter_table('units_of_measure', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_of_measure_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_units_of_measure_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_units_of_measure_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_uoms_company_id', ['company_id'], unique=False)

    op.create_table('items',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('item_type', sa.Enum('STOCK_ITEM', 'SERVICE', name='itemtypeenum'), nullable=False),
    sa.Column('brand_id', sa.BigInteger(), nullable=True),
    sa.Column('base_uom_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='statusenum'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_uom_id'], ['units_of_measure.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'sku', name='uq_item_company_sku')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_sku'), ['sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_updated_at'), ['updated_at'], unique=False)

    op.create_table('parties',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('nature', sa.Enum('ORGANIZATION', 'INDIVIDUAL', name='partynatureenum'), nullable=False),
    sa.Column('role', sa.Enum('CUSTOMER', 'SUPPLIER', name='partyroleenum'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('city_id', sa.BigInteger(), nullable=True),
    sa.Column('is_cash_party', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('img_key', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='statusenum'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_party_company_code')
    )
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parties_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parties_city_id'), ['city_id'], unique=False)
        batch_op.create_index('ix_parties_code', ['code'], unique=False)
        batch_op.create_index('ix_parties_company_id', ['company_id'], unique=False)
        batch_op.create_index('ix_parties_company_role_name', ['company_id', 'role', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_parties_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_parties_img_key'), ['img_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_parties_is_cash_party'), ['is_cash_party'], unique=False)
        batch_op.create_index(batch_op.f('ix_parties_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_parties_nature'), ['nature'], unique=False)
        batch_op.create_index(batch_op.f('ix_parties_role'), ['role'], unique=False)
        batch_op.create_index('ix_parties_role_type', ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_parties_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_parties_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_party_company_branch_role', ['company_id', 'branch_id', 'role'], unique=False)
        batch_op.create_index('ix_party_company_role_name_ci', ['company_id', 'role', sa.literal_column('lower(name)')], unique=False)
        batch_op.create_index('ix_party_company_role_phone', ['company_id', 'role', 'phone'], unique=False)

    op.create_table('stock_entries',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('doc_status', sa.Enum('DRAFT', 'SUBMITTED', 'CANCELLED', 'UNPAID', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'RETURNED', name='docstatusenum'), nullable=False),
    sa.Column('posting_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stock_entry_type', sa.Enum('MATERIAL_RECEIPT', 'MATERIAL_ISSUE', 'MATERIAL_TRANSFER', 'STOCK_ADJUSTMENT', 'STOCK_RECONCILIATION', 'MANUFACTURE', name='stockentrytype'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_stock_entry_code')
    )
    with op.batch_alter_table('stock_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_entries_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_entries_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_entries_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_entries_doc_status'), ['doc_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_entries_posting_date'), ['posting_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_entries_stock_entry_type'), ['stock_entry_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_entries_updated_at'), ['updated_at'], unique=False)

    op.create_table('stock_reconciliations',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('posting_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('doc_status', sa.Enum('DRAFT', 'SUBMITTED', 'CANCELLED', 'UNPAID', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'RETURNED', name='docstatusenum'), nullable=False),
    sa.Column('purpose', sa.Enum('OPENING_STOCK', 'STOCK_RECONCILIATION', name='stockreconciliationpurpose'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'branch_id', 'code', name='uq_reconciliation_branch_code')
    )
    with op.batch_alter_table('stock_reconciliations', schema=None) as batch_op:
        batch_op.create_index('ix_reconciliation_company_branch_status', ['company_id', 'branch_id', 'doc_status'], unique=False)
        batch_op.create_index('ix_reconciliation_company_posting_date', ['company_id', 'posting_date'], unique=False)
        batch_op.create_index('ix_reconciliation_company_purpose', ['company_id', 'purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_reconciliations_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_reconciliations_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_reconciliations_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_reconciliations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_reconciliations_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_reconciliations_doc_status'), ['doc_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_reconciliations_posting_date'), ['posting_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_reconciliations_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_reconciliations_updated_at'), ['updated_at'], unique=False)

    op.create_table('warehouses',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_warehouse_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='statusenum'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['parent_warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'name', name='uq_warehouse_branch_name')
    )
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.create_index('ix_warehouse_parent', ['parent_warehouse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouses_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouses_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_warehouses_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouses_parent_warehouse_id'), ['parent_warehouse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouses_updated_at'), ['updated_at'], unique=False)

    op.create_table('bins',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('actual_qty', sa.Numeric(precision=12, scale=3), nullable=False, comment='Total physical stock'),
    sa.Column('reserved_qty', sa.Numeric(precision=12, scale=3), nullable=False, comment='Reserved for sales orders'),
    sa.Column('ordered_qty', sa.Numeric(precision=12, scale=3), nullable=False, comment='Quantity on purchase orders'),
    sa.Column('valuation_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('projected_qty', sa.Numeric(precision=12, scale=3), sa.Computed('actual_qty - reserved_qty + ordered_qty', persisted=True), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_bin_company_code'),
    sa.UniqueConstraint('company_id', 'item_id', 'warehouse_id', name='uq_bin_location')
    )
    with op.batch_alter_table('bins', schema=None) as batch_op:
        batch_op.create_index('idx_bin_company_warehouse', ['company_id', 'warehouse_id'], unique=False)
        batch_op.create_index('idx_bin_item_warehouse', ['item_id', 'warehouse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bins_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_bins_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bins_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bins_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bins_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bins_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('branch_item_pricing',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('standard_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'item_id', 'branch_id', name='uq_branch_item_price')
    )
    with op.batch_alter_table('branch_item_pricing', schema=None) as batch_op:
        batch_op.create_index('ix_branch_item_pricing_company_id', ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_branch_item_pricing_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_branch_item_pricing_updated_at'), ['updated_at'], unique=False)

    op.create_table('party_commercial_policies',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('party_id', sa.BigInteger(), nullable=False),
    sa.Column('allow_credit', sa.Boolean(), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('allow_credit = true OR credit_limit = 0', name='ck_allow_credit_or_zero_limit'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('party_id')
    )
    with op.batch_alter_table('party_commercial_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_party_commercial_policies_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_party_commercial_policies_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_party_commercial_policies_updated_at'), ['updated_at'], unique=False)

    op.create_table('party_organization_details',
    sa.Column('party_id', sa.BigInteger(), nullable=False),
    sa.Column('org_company_name', sa.String(length=255), nullable=True),
    sa.Column('org_branch_name', sa.String(length=255), nullable=True),
    sa.Column('org_contact_name', sa.String(length=255), nullable=True),
    sa.Column('org_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('org_contact_email', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('party_organization_details', schema=None) as batch_op:
        batch_op.create_index('ix_party_org_details_contact_ci', [sa.literal_column('lower(org_contact_name)')], unique=False)
        batch_op.create_index('ix_party_org_details_orgbr_ci', [sa.literal_column('lower(org_branch_name)')], unique=False)
        batch_op.create_index('ix_party_org_details_orgco_ci', [sa.literal_column('lower(org_company_name)')], unique=False)
        batch_op.create_index('ix_party_org_details_party_id', ['party_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_party_organization_details_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_party_organization_details_org_branch_name'), ['org_branch_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_party_organization_details_org_company_name'), ['org_company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_party_organization_details_org_contact_name'), ['org_contact_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_party_organization_details_party_id'), ['party_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_party_organization_details_updated_at'), ['updated_at'], unique=False)

    op.create_table('purchase_invoices',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('posting_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('doc_status', sa.Enum('DRAFT', 'SUBMITTED', 'CANCELLED', 'UNPAID', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'RETURNED', name='docstatusenum'), nullable=False),
    sa.Column('update_stock', sa.Boolean(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('balance_due', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'branch_id', 'code', name='uq_pin_branch_code')
    )
    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.create_index('ix_pin_company_branch_status', ['company_id', 'branch_id', 'doc_status'], unique=False)
        batch_op.create_index('ix_pin_company_posting_date', ['company_id', 'posting_date'], unique=False)
        batch_op.create_index('ix_pin_company_supplier', ['company_id', 'supplier_id'], unique=False)
        batch_op.create_index('ix_pin_company_update_stock', ['company_id', 'update_stock'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_invoices_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_invoices_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_invoices_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_invoices_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_invoices_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_invoices_doc_status'), ['doc_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_invoices_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_invoices_posting_date'), ['posting_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_invoices_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_invoices_update_stock'), ['update_stock'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_invoices_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_invoices_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('purchase_quotations',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('posting_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('doc_status', sa.Enum('DRAFT', 'SUBMITTED', 'CANCELLED', 'UNPAID', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'RETURNED', name='docstatusenum'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'branch_id', 'code', name='uq_pq_branch_code')
    )
    with op.batch_alter_table('purchase_quotations', schema=None) as batch_op:
        batch_op.create_index('ix_pq_company_branch_status', ['company_id', 'branch_id', 'doc_status'], unique=False)
        batch_op.create_index('ix_pq_company_posting_date', ['company_id', 'posting_date'], unique=False)
        batch_op.create_index('ix_pq_company_supplier', ['company_id', 'supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_quotations_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_quotations_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_quotations_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_quotations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_quotations_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_quotations_doc_status'), ['doc_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_quotations_posting_date'), ['posting_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_quotations_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_quotations_updated_at'), ['updated_at'], unique=False)

    op.create_table('purchase_receipts',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('posting_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('doc_status', sa.Enum('DRAFT', 'SUBMITTED', 'CANCELLED', 'UNPAID', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'RETURNED', name='docstatusenum'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'branch_id', 'code', name='uq_pr_branch_code')
    )
    with op.batch_alter_table('purchase_receipts', schema=None) as batch_op:
        batch_op.create_index('ix_pr_company_branch_status', ['company_id', 'branch_id', 'doc_status'], unique=False)
        batch_op.create_index('ix_pr_company_posting_date', ['company_id', 'posting_date'], unique=False)
        batch_op.create_index('ix_pr_company_supplier', ['company_id', 'supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_receipts_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_receipts_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_receipts_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_receipts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_receipts_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_receipts_doc_status'), ['doc_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_receipts_posting_date'), ['posting_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_receipts_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_receipts_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_receipts_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('sales_delivery_notes',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('posting_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('doc_status', sa.Enum('DRAFT', 'SUBMITTED', 'CANCELLED', 'UNPAID', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'RETURNED', name='docstatusenum'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'branch_id', 'code', name='uq_sdn_branch_code')
    )
    with op.batch_alter_table('sales_delivery_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_delivery_notes_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_delivery_notes_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_delivery_notes_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_delivery_notes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_delivery_notes_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_delivery_notes_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_delivery_notes_doc_status'), ['doc_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_delivery_notes_posting_date'), ['posting_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_delivery_notes_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_delivery_notes_warehouse_id'), ['warehouse_id'], unique=False)
        batch_op.create_index('ix_sdn_company_branch_status', ['company_id', 'branch_id', 'doc_status'], unique=False)
        batch_op.create_index('ix_sdn_company_customer', ['company_id', 'customer_id'], unique=False)
        batch_op.create_index('ix_sdn_company_posting_date', ['company_id', 'posting_date'], unique=False)

    op.create_table('sales_invoices',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('posting_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('doc_status', sa.Enum('DRAFT', 'SUBMITTED', 'CANCELLED', 'UNPAID', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'RETURNED', name='docstatusenum'), nullable=False),
    sa.Column('update_stock', sa.Boolean(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('balance_due', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'branch_id', 'code', name='uq_sin_branch_code')
    )
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_invoices_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_doc_status'), ['doc_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_posting_date'), ['posting_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_update_stock'), ['update_stock'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_warehouse_id'), ['warehouse_id'], unique=False)
        batch_op.create_index('ix_sin_company_branch_status', ['company_id', 'branch_id', 'doc_status'], unique=False)
        batch_op.create_index('ix_sin_company_customer', ['company_id', 'customer_id'], unique=False)
        batch_op.create_index('ix_sin_company_posting_date', ['company_id', 'posting_date'], unique=False)
        batch_op.create_index('ix_sin_company_update_stock', ['company_id', 'update_stock'], unique=False)

    op.create_table('sales_quotations',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('posting_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('doc_status', sa.Enum('DRAFT', 'SUBMITTED', 'CANCELLED', 'UNPAID', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'RETURNED', name='docstatusenum'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'branch_id', 'code', name='uq_sq_branch_code')
    )
    with op.batch_alter_table('sales_quotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_quotations_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_quotations_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_quotations_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_quotations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_quotations_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_quotations_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_quotations_doc_status'), ['doc_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_quotations_posting_date'), ['posting_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_quotations_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_sq_company_branch_status', ['company_id', 'branch_id', 'doc_status'], unique=False)
        batch_op.create_index('ix_sq_company_customer', ['company_id', 'customer_id'], unique=False)
        batch_op.create_index('ix_sq_company_posting_date', ['company_id', 'posting_date'], unique=False)

    op.create_table('stock_entry_items',
    sa.Column('stock_entry_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('source_warehouse_id', sa.BigInteger(), nullable=True),
    sa.Column('target_warehouse_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('uom_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_entry_id'], ['stock_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uom_id'], ['units_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_entry_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_entry_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_entry_items_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_entry_items_source_warehouse_id'), ['source_warehouse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_entry_items_stock_entry_id'), ['stock_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_entry_items_target_warehouse_id'), ['target_warehouse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_entry_items_uom_id'), ['uom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_entry_items_updated_at'), ['updated_at'], unique=False)

    op.create_table('stock_ledger_entries',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('posting_date', sa.Date(), nullable=False),
    sa.Column('posting_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_qty', sa.Numeric(precision=10, scale=4), nullable=False, comment='Quantity in Base UOM.'),
    sa.Column('incoming_rate', sa.Numeric(precision=12, scale=2), nullable=True, comment='Cost of incoming stock. NULL if outgoing.'),
    sa.Column('valuation_rate', sa.Numeric(precision=12, scale=2), nullable=False, comment="Item's average valuation rate post-transaction."),
    sa.Column('doc_type_id', sa.BigInteger(), nullable=False),
    sa.Column('doc_id', sa.BigInteger(), nullable=False),
    sa.Column('doc_row_id', sa.BigInteger(), nullable=True, comment='Links to a specific line item on the source document.'),
    sa.Column('qty_before_transaction', sa.Numeric(precision=10, scale=4), nullable=True, comment='Quantity in the warehouse before this transaction.'),
    sa.Column('qty_after_transaction', sa.Numeric(precision=10, scale=4), nullable=True, comment='Quantity in the warehouse after this transaction.'),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['doc_type_id'], ['document_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_sle_code')
    )
    with op.batch_alter_table('stock_ledger_entries', schema=None) as batch_op:
        batch_op.create_index('ix_sle_doc_ref', ['doc_type_id', 'doc_id'], unique=False)
        batch_op.create_index('ix_sle_item_branch_wh', ['company_id', 'item_id', 'branch_id', 'warehouse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_ledger_entries_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_stock_ledger_entries_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_ledger_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_ledger_entries_doc_id'), ['doc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_ledger_entries_doc_row_id'), ['doc_row_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_ledger_entries_doc_type_id'), ['doc_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_ledger_entries_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_ledger_entries_posting_date'), ['posting_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_ledger_entries_posting_time'), ['posting_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_ledger_entries_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_ledger_entries_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('stock_reconciliation_items',
    sa.Column('reconciliation_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('valuation_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_recon_qty_nonneg'),
    sa.CheckConstraint('valuation_rate IS NULL OR valuation_rate >= 0', name='ck_recon_valrate_nonneg'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reconciliation_id'], ['stock_reconciliations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reconciliation_id', 'item_id', 'warehouse_id', name='uq_recon_item_wh')
    )
    with op.batch_alter_table('stock_reconciliation_items', schema=None) as batch_op:
        batch_op.create_index('ix_recon_item_company_wh', ['item_id', 'warehouse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_reconciliation_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_reconciliation_items_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_reconciliation_items_reconciliation_id'), ['reconciliation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_reconciliation_items_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_reconciliation_items_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('uom_conversions',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('from_uom_id', sa.BigInteger(), nullable=False),
    sa.Column('to_uom_id', sa.BigInteger(), nullable=False),
    sa.Column('conversion_factor', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['from_uom_id'], ['units_of_measure.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_uom_id'], ['units_of_measure.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'from_uom_id', 'to_uom_id', name='uq_uom_conversion')
    )
    with op.batch_alter_table('uom_conversions', schema=None) as batch_op:
        batch_op.create_index('ix_uom_conversions_company_id', ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_uom_conversions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_uom_conversions_updated_at'), ['updated_at'], unique=False)

    op.create_table('purchase_quotation_items',
    sa.Column('quotation_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('uom_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), sa.Computed('quantity * rate', persisted=True), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_pqi_qty_pos'),
    sa.CheckConstraint('rate >= 0', name='ck_pqi_rate_nonneg'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quotation_id'], ['purchase_quotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uom_id'], ['units_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_quotation_items', schema=None) as batch_op:
        batch_op.create_index('ix_pqi_item', ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_quotation_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_quotation_items_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_quotation_items_quotation_id'), ['quotation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_quotation_items_uom_id'), ['uom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_quotation_items_updated_at'), ['updated_at'], unique=False)

    op.create_table('purchase_receipt_items',
    sa.Column('receipt_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('uom_id', sa.BigInteger(), nullable=True),
    sa.Column('received_qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('accepted_qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), sa.Computed('CASE WHEN unit_price IS NULL THEN NULL ELSE accepted_qty * unit_price END', persisted=True), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('accepted_qty >= 0 AND accepted_qty <= received_qty', name='ck_pri_accepted_valid'),
    sa.CheckConstraint('received_qty > 0', name='ck_pri_received_pos'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receipt_id'], ['purchase_receipts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uom_id'], ['units_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_receipt_items', schema=None) as batch_op:
        batch_op.create_index('ix_pri_item', ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_receipt_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_receipt_items_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_receipt_items_receipt_id'), ['receipt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_receipt_items_uom_id'), ['uom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_receipt_items_updated_at'), ['updated_at'], unique=False)

    op.create_table('purchase_returns',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('receipt_id', sa.BigInteger(), nullable=True),
    sa.Column('invoice_id', sa.BigInteger(), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('posting_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('doc_status', sa.Enum('DRAFT', 'SUBMITTED', 'CANCELLED', 'UNPAID', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'RETURNED', name='docstatusenum'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['purchase_invoices.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['purchase_receipts.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'branch_id', 'code', name='uq_pret_branch_code')
    )
    with op.batch_alter_table('purchase_returns', schema=None) as batch_op:
        batch_op.create_index('ix_pret_company_branch_status', ['company_id', 'branch_id', 'doc_status'], unique=False)
        batch_op.create_index('ix_pret_company_posting_date', ['company_id', 'posting_date'], unique=False)
        batch_op.create_index('ix_pret_company_supplier', ['company_id', 'supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_returns_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_returns_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_returns_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_returns_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_returns_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_returns_doc_status'), ['doc_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_returns_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_returns_posting_date'), ['posting_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_returns_receipt_id'), ['receipt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_returns_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_returns_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_returns_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('sales_delivery_note_items',
    sa.Column('delivery_note_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('uom_id', sa.BigInteger(), nullable=True),
    sa.Column('delivered_qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), sa.Computed('CASE WHEN unit_price IS NULL THEN NULL ELSE delivered_qty * unit_price END', persisted=True), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('delivered_qty > 0', name='ck_sdni_delivered_pos'),
    sa.ForeignKeyConstraint(['delivery_note_id'], ['sales_delivery_notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uom_id'], ['units_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_delivery_note_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_delivery_note_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_delivery_note_items_delivery_note_id'), ['delivery_note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_delivery_note_items_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_delivery_note_items_uom_id'), ['uom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_delivery_note_items_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_sdni_item', ['item_id'], unique=False)

    op.create_table('sales_quotation_items',
    sa.Column('quotation_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('uom_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), sa.Computed('quantity * rate', persisted=True), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_sqi_qty_pos'),
    sa.CheckConstraint('rate >= 0', name='ck_sqi_rate_nonneg'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quotation_id'], ['sales_quotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uom_id'], ['units_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_quotation_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_quotation_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_quotation_items_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_quotation_items_quotation_id'), ['quotation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_quotation_items_uom_id'), ['uom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_quotation_items_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_sqi_item', ['item_id'], unique=False)

    op.create_table('sales_returns',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('delivery_note_id', sa.BigInteger(), nullable=True),
    sa.Column('invoice_id', sa.BigInteger(), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('posting_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('doc_status', sa.Enum('DRAFT', 'SUBMITTED', 'CANCELLED', 'UNPAID', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'RETURNED', name='docstatusenum'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['delivery_note_id'], ['sales_delivery_notes.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'branch_id', 'code', name='uq_sret_branch_code')
    )
    with op.batch_alter_table('sales_returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_returns_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_returns_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_returns_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_returns_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_returns_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_returns_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_returns_delivery_note_id'), ['delivery_note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_returns_doc_status'), ['doc_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_returns_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_returns_posting_date'), ['posting_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_returns_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_returns_warehouse_id'), ['warehouse_id'], unique=False)
        batch_op.create_index('ix_sret_company_branch_status', ['company_id', 'branch_id', 'doc_status'], unique=False)
        batch_op.create_index('ix_sret_company_customer', ['company_id', 'customer_id'], unique=False)
        batch_op.create_index('ix_sret_company_posting_date', ['company_id', 'posting_date'], unique=False)

    op.create_table('purchase_invoice_items',
    sa.Column('invoice_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('uom_id', sa.BigInteger(), nullable=True),
    sa.Column('receipt_item_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), sa.Computed('quantity * rate', persisted=True), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_pii_qty_pos'),
    sa.CheckConstraint('rate >= 0', name='ck_pii_rate_nonneg'),
    sa.ForeignKeyConstraint(['invoice_id'], ['purchase_invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receipt_item_id'], ['purchase_receipt_items.id'], ),
    sa.ForeignKeyConstraint(['uom_id'], ['units_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_invoice_items', schema=None) as batch_op:
        batch_op.create_index('ix_pii_item', ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_invoice_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_invoice_items_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_invoice_items_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_invoice_items_receipt_item_id'), ['receipt_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_invoice_items_uom_id'), ['uom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_invoice_items_updated_at'), ['updated_at'], unique=False)

    op.create_table('sales_invoice_items',
    sa.Column('invoice_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('uom_id', sa.BigInteger(), nullable=True),
    sa.Column('delivery_note_item_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), sa.Computed('quantity * rate', persisted=True), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_sii_qty_pos'),
    sa.CheckConstraint('rate >= 0', name='ck_sii_rate_nonneg'),
    sa.ForeignKeyConstraint(['delivery_note_item_id'], ['sales_delivery_note_items.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uom_id'], ['units_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_invoice_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_invoice_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoice_items_delivery_note_item_id'), ['delivery_note_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoice_items_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoice_items_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoice_items_uom_id'), ['uom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoice_items_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_sii_item', ['item_id'], unique=False)

    op.create_table('purchase_return_items',
    sa.Column('purchase_return_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('uom_id', sa.BigInteger(), nullable=False),
    sa.Column('receipt_item_id', sa.BigInteger(), nullable=True),
    sa.Column('invoice_item_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), sa.Computed('CASE WHEN rate IS NULL THEN NULL ELSE quantity * rate END', persisted=True), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_pret_qty_pos'),
    sa.CheckConstraint('rate IS NULL OR rate >= 0', name='ck_pret_rate_nonneg'),
    sa.ForeignKeyConstraint(['invoice_item_id'], ['purchase_invoice_items.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_return_id'], ['purchase_returns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receipt_item_id'], ['purchase_receipt_items.id'], ),
    sa.ForeignKeyConstraint(['uom_id'], ['units_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_return_id', 'item_id', 'batch_number', name='uq_pret_item_batch')
    )
    with op.batch_alter_table('purchase_return_items', schema=None) as batch_op:
        batch_op.create_index('ix_pret_item', ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_return_items_batch_number'), ['batch_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_return_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_return_items_invoice_item_id'), ['invoice_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_return_items_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_return_items_purchase_return_id'), ['purchase_return_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_return_items_receipt_item_id'), ['receipt_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_return_items_uom_id'), ['uom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_return_items_updated_at'), ['updated_at'], unique=False)

    op.create_table('sales_return_items',
    sa.Column('sales_return_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('uom_id', sa.BigInteger(), nullable=False),
    sa.Column('delivery_note_item_id', sa.BigInteger(), nullable=True),
    sa.Column('invoice_item_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), sa.Computed('CASE WHEN rate IS NULL THEN NULL ELSE quantity * rate END', persisted=True), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_sret_qty_pos'),
    sa.CheckConstraint('rate IS NULL OR rate >= 0', name='ck_sret_rate_nonneg'),
    sa.ForeignKeyConstraint(['delivery_note_item_id'], ['sales_delivery_note_items.id'], ),
    sa.ForeignKeyConstraint(['invoice_item_id'], ['sales_invoice_items.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_return_id'], ['sales_returns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uom_id'], ['units_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sales_return_id', 'item_id', 'batch_number', name='uq_sret_item_batch')
    )
    with op.batch_alter_table('sales_return_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_return_items_batch_number'), ['batch_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_return_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_return_items_delivery_note_item_id'), ['delivery_note_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_return_items_invoice_item_id'), ['invoice_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_return_items_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_return_items_sales_return_id'), ['sales_return_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_return_items_uom_id'), ['uom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_return_items_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_sret_item', ['item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_return_items', schema=None) as batch_op:
        batch_op.drop_index('ix_sret_item')
        batch_op.drop_index(batch_op.f('ix_sales_return_items_updated_at'))
        batch_op.drop_index(batch_op.f('ix_sales_return_items_uom_id'))
        batch_op.drop_index(batch_op.f('ix_sales_return_items_sales_return_id'))
        batch_op.drop_index(batch_op.f('ix_sales_return_items_item_id'))
        batch_op.drop_index(batch_op.f('ix_sales_return_items_invoice_item_id'))
        batch_op.drop_index(batch_op.f('ix_sales_return_items_delivery_note_item_id'))
        batch_op.drop_index(batch_op.f('ix_sales_return_items_created_at'))
        batch_op.drop_index(batch_op.f('ix_sales_return_items_batch_number'))

    op.drop_table('sales_return_items')
    with op.batch_alter_table('purchase_return_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_return_items_updated_at'))
        batch_op.drop_index(batch_op.f('ix_purchase_return_items_uom_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_return_items_receipt_item_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_return_items_purchase_return_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_return_items_item_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_return_items_invoice_item_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_return_items_created_at'))
        batch_op.drop_index(batch_op.f('ix_purchase_return_items_batch_number'))
        batch_op.drop_index('ix_pret_item')

    op.drop_table('purchase_return_items')
    with op.batch_alter_table('sales_invoice_items', schema=None) as batch_op:
        batch_op.drop_index('ix_sii_item')
        batch_op.drop_index(batch_op.f('ix_sales_invoice_items_updated_at'))
        batch_op.drop_index(batch_op.f('ix_sales_invoice_items_uom_id'))
        batch_op.drop_index(batch_op.f('ix_sales_invoice_items_item_id'))
        batch_op.drop_index(batch_op.f('ix_sales_invoice_items_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_sales_invoice_items_delivery_note_item_id'))
        batch_op.drop_index(batch_op.f('ix_sales_invoice_items_created_at'))

    op.drop_table('sales_invoice_items')
    with op.batch_alter_table('purchase_invoice_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_invoice_items_updated_at'))
        batch_op.drop_index(batch_op.f('ix_purchase_invoice_items_uom_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_invoice_items_receipt_item_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_invoice_items_item_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_invoice_items_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_invoice_items_created_at'))
        batch_op.drop_index('ix_pii_item')

    op.drop_table('purchase_invoice_items')
    with op.batch_alter_table('sales_returns', schema=None) as batch_op:
        batch_op.drop_index('ix_sret_company_posting_date')
        batch_op.drop_index('ix_sret_company_customer')
        batch_op.drop_index('ix_sret_company_branch_status')
        batch_op.drop_index(batch_op.f('ix_sales_returns_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_sales_returns_updated_at'))
        batch_op.drop_index(batch_op.f('ix_sales_returns_posting_date'))
        batch_op.drop_index(batch_op.f('ix_sales_returns_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_sales_returns_doc_status'))
        batch_op.drop_index(batch_op.f('ix_sales_returns_delivery_note_id'))
        batch_op.drop_index(batch_op.f('ix_sales_returns_customer_id'))
        batch_op.drop_index(batch_op.f('ix_sales_returns_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_sales_returns_created_at'))
        batch_op.drop_index(batch_op.f('ix_sales_returns_company_id'))
        batch_op.drop_index(batch_op.f('ix_sales_returns_code'))
        batch_op.drop_index(batch_op.f('ix_sales_returns_branch_id'))

    op.drop_table('sales_returns')
    with op.batch_alter_table('sales_quotation_items', schema=None) as batch_op:
        batch_op.drop_index('ix_sqi_item')
        batch_op.drop_index(batch_op.f('ix_sales_quotation_items_updated_at'))
        batch_op.drop_index(batch_op.f('ix_sales_quotation_items_uom_id'))
        batch_op.drop_index(batch_op.f('ix_sales_quotation_items_quotation_id'))
        batch_op.drop_index(batch_op.f('ix_sales_quotation_items_item_id'))
        batch_op.drop_index(batch_op.f('ix_sales_quotation_items_created_at'))

    op.drop_table('sales_quotation_items')
    with op.batch_alter_table('sales_delivery_note_items', schema=None) as batch_op:
        batch_op.drop_index('ix_sdni_item')
        batch_op.drop_index(batch_op.f('ix_sales_delivery_note_items_updated_at'))
        batch_op.drop_index(batch_op.f('ix_sales_delivery_note_items_uom_id'))
        batch_op.drop_index(batch_op.f('ix_sales_delivery_note_items_item_id'))
        batch_op.drop_index(batch_op.f('ix_sales_delivery_note_items_delivery_note_id'))
        batch_op.drop_index(batch_op.f('ix_sales_delivery_note_items_created_at'))

    op.drop_table('sales_delivery_note_items')
    with op.batch_alter_table('purchase_returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_returns_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_returns_updated_at'))
        batch_op.drop_index(batch_op.f('ix_purchase_returns_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_returns_receipt_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_returns_posting_date'))
        batch_op.drop_index(batch_op.f('ix_purchase_returns_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_returns_doc_status'))
        batch_op.drop_index(batch_op.f('ix_purchase_returns_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_returns_created_at'))
        batch_op.drop_index(batch_op.f('ix_purchase_returns_company_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_returns_code'))
        batch_op.drop_index(batch_op.f('ix_purchase_returns_branch_id'))
        batch_op.drop_index('ix_pret_company_supplier')
        batch_op.drop_index('ix_pret_company_posting_date')
        batch_op.drop_index('ix_pret_company_branch_status')

    op.drop_table('purchase_returns')
    with op.batch_alter_table('purchase_receipt_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_receipt_items_updated_at'))
        batch_op.drop_index(batch_op.f('ix_purchase_receipt_items_uom_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_receipt_items_receipt_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_receipt_items_item_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_receipt_items_created_at'))
        batch_op.drop_index('ix_pri_item')

    op.drop_table('purchase_receipt_items')
    with op.batch_alter_table('purchase_quotation_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_quotation_items_updated_at'))
        batch_op.drop_index(batch_op.f('ix_purchase_quotation_items_uom_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_quotation_items_quotation_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_quotation_items_item_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_quotation_items_created_at'))
        batch_op.drop_index('ix_pqi_item')

    op.drop_table('purchase_quotation_items')
    with op.batch_alter_table('uom_conversions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uom_conversions_updated_at'))
        batch_op.drop_index(batch_op.f('ix_uom_conversions_created_at'))
        batch_op.drop_index('ix_uom_conversions_company_id')

    op.drop_table('uom_conversions')
    with op.batch_alter_table('stock_reconciliation_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_reconciliation_items_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_stock_reconciliation_items_updated_at'))
        batch_op.drop_index(batch_op.f('ix_stock_reconciliation_items_reconciliation_id'))
        batch_op.drop_index(batch_op.f('ix_stock_reconciliation_items_item_id'))
        batch_op.drop_index(batch_op.f('ix_stock_reconciliation_items_created_at'))
        batch_op.drop_index('ix_recon_item_company_wh')

    op.drop_table('stock_reconciliation_items')
    with op.batch_alter_table('stock_ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_ledger_entries_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_stock_ledger_entries_updated_at'))
        batch_op.drop_index(batch_op.f('ix_stock_ledger_entries_posting_time'))
        batch_op.drop_index(batch_op.f('ix_stock_ledger_entries_posting_date'))
        batch_op.drop_index(batch_op.f('ix_stock_ledger_entries_item_id'))
        batch_op.drop_index(batch_op.f('ix_stock_ledger_entries_doc_type_id'))
        batch_op.drop_index(batch_op.f('ix_stock_ledger_entries_doc_row_id'))
        batch_op.drop_index(batch_op.f('ix_stock_ledger_entries_doc_id'))
        batch_op.drop_index(batch_op.f('ix_stock_ledger_entries_created_at'))
        batch_op.drop_index(batch_op.f('ix_stock_ledger_entries_company_id'))
        batch_op.drop_index(batch_op.f('ix_stock_ledger_entries_code'))
        batch_op.drop_index('ix_sle_item_branch_wh')
        batch_op.drop_index('ix_sle_doc_ref')

    op.drop_table('stock_ledger_entries')
    with op.batch_alter_table('stock_entry_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_entry_items_updated_at'))
        batch_op.drop_index(batch_op.f('ix_stock_entry_items_uom_id'))
        batch_op.drop_index(batch_op.f('ix_stock_entry_items_target_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_stock_entry_items_stock_entry_id'))
        batch_op.drop_index(batch_op.f('ix_stock_entry_items_source_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_stock_entry_items_item_id'))
        batch_op.drop_index(batch_op.f('ix_stock_entry_items_created_at'))

    op.drop_table('stock_entry_items')
    with op.batch_alter_table('sales_quotations', schema=None) as batch_op:
        batch_op.drop_index('ix_sq_company_posting_date')
        batch_op.drop_index('ix_sq_company_customer')
        batch_op.drop_index('ix_sq_company_branch_status')
        batch_op.drop_index(batch_op.f('ix_sales_quotations_updated_at'))
        batch_op.drop_index(batch_op.f('ix_sales_quotations_posting_date'))
        batch_op.drop_index(batch_op.f('ix_sales_quotations_doc_status'))
        batch_op.drop_index(batch_op.f('ix_sales_quotations_customer_id'))
        batch_op.drop_index(batch_op.f('ix_sales_quotations_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_sales_quotations_created_at'))
        batch_op.drop_index(batch_op.f('ix_sales_quotations_company_id'))
        batch_op.drop_index(batch_op.f('ix_sales_quotations_code'))
        batch_op.drop_index(batch_op.f('ix_sales_quotations_branch_id'))

    op.drop_table('sales_quotations')
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.drop_index('ix_sin_company_update_stock')
        batch_op.drop_index('ix_sin_company_posting_date')
        batch_op.drop_index('ix_sin_company_customer')
        batch_op.drop_index('ix_sin_company_branch_status')
        batch_op.drop_index(batch_op.f('ix_sales_invoices_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_sales_invoices_updated_at'))
        batch_op.drop_index(batch_op.f('ix_sales_invoices_update_stock'))
        batch_op.drop_index(batch_op.f('ix_sales_invoices_posting_date'))
        batch_op.drop_index(batch_op.f('ix_sales_invoices_due_date'))
        batch_op.drop_index(batch_op.f('ix_sales_invoices_doc_status'))
        batch_op.drop_index(batch_op.f('ix_sales_invoices_customer_id'))
        batch_op.drop_index(batch_op.f('ix_sales_invoices_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_sales_invoices_created_at'))
        batch_op.drop_index(batch_op.f('ix_sales_invoices_company_id'))
        batch_op.drop_index(batch_op.f('ix_sales_invoices_code'))
        batch_op.drop_index(batch_op.f('ix_sales_invoices_branch_id'))

    op.drop_table('sales_invoices')
    with op.batch_alter_table('sales_delivery_notes', schema=None) as batch_op:
        batch_op.drop_index('ix_sdn_company_posting_date')
        batch_op.drop_index('ix_sdn_company_customer')
        batch_op.drop_index('ix_sdn_company_branch_status')
        batch_op.drop_index(batch_op.f('ix_sales_delivery_notes_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_sales_delivery_notes_updated_at'))
        batch_op.drop_index(batch_op.f('ix_sales_delivery_notes_posting_date'))
        batch_op.drop_index(batch_op.f('ix_sales_delivery_notes_doc_status'))
        batch_op.drop_index(batch_op.f('ix_sales_delivery_notes_customer_id'))
        batch_op.drop_index(batch_op.f('ix_sales_delivery_notes_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_sales_delivery_notes_created_at'))
        batch_op.drop_index(batch_op.f('ix_sales_delivery_notes_company_id'))
        batch_op.drop_index(batch_op.f('ix_sales_delivery_notes_code'))
        batch_op.drop_index(batch_op.f('ix_sales_delivery_notes_branch_id'))

    op.drop_table('sales_delivery_notes')
    with op.batch_alter_table('purchase_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_receipts_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_receipts_updated_at'))
        batch_op.drop_index(batch_op.f('ix_purchase_receipts_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_receipts_posting_date'))
        batch_op.drop_index(batch_op.f('ix_purchase_receipts_doc_status'))
        batch_op.drop_index(batch_op.f('ix_purchase_receipts_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_receipts_created_at'))
        batch_op.drop_index(batch_op.f('ix_purchase_receipts_company_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_receipts_code'))
        batch_op.drop_index(batch_op.f('ix_purchase_receipts_branch_id'))
        batch_op.drop_index('ix_pr_company_supplier')
        batch_op.drop_index('ix_pr_company_posting_date')
        batch_op.drop_index('ix_pr_company_branch_status')

    op.drop_table('purchase_receipts')
    with op.batch_alter_table('purchase_quotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_quotations_updated_at'))
        batch_op.drop_index(batch_op.f('ix_purchase_quotations_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_quotations_posting_date'))
        batch_op.drop_index(batch_op.f('ix_purchase_quotations_doc_status'))
        batch_op.drop_index(batch_op.f('ix_purchase_quotations_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_quotations_created_at'))
        batch_op.drop_index(batch_op.f('ix_purchase_quotations_company_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_quotations_code'))
        batch_op.drop_index(batch_op.f('ix_purchase_quotations_branch_id'))
        batch_op.drop_index('ix_pq_company_supplier')
        batch_op.drop_index('ix_pq_company_posting_date')
        batch_op.drop_index('ix_pq_company_branch_status')

    op.drop_table('purchase_quotations')
    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_invoices_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_invoices_updated_at'))
        batch_op.drop_index(batch_op.f('ix_purchase_invoices_update_stock'))
        batch_op.drop_index(batch_op.f('ix_purchase_invoices_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_invoices_posting_date'))
        batch_op.drop_index(batch_op.f('ix_purchase_invoices_due_date'))
        batch_op.drop_index(batch_op.f('ix_purchase_invoices_doc_status'))
        batch_op.drop_index(batch_op.f('ix_purchase_invoices_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_invoices_created_at'))
        batch_op.drop_index(batch_op.f('ix_purchase_invoices_company_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_invoices_code'))
        batch_op.drop_index(batch_op.f('ix_purchase_invoices_branch_id'))
        batch_op.drop_index('ix_pin_company_update_stock')
        batch_op.drop_index('ix_pin_company_supplier')
        batch_op.drop_index('ix_pin_company_posting_date')
        batch_op.drop_index('ix_pin_company_branch_status')

    op.drop_table('purchase_invoices')
    with op.batch_alter_table('party_organization_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_party_organization_details_updated_at'))
        batch_op.drop_index(batch_op.f('ix_party_organization_details_party_id'))
        batch_op.drop_index(batch_op.f('ix_party_organization_details_org_contact_name'))
        batch_op.drop_index(batch_op.f('ix_party_organization_details_org_company_name'))
        batch_op.drop_index(batch_op.f('ix_party_organization_details_org_branch_name'))
        batch_op.drop_index(batch_op.f('ix_party_organization_details_created_at'))
        batch_op.drop_index('ix_party_org_details_party_id')
        batch_op.drop_index('ix_party_org_details_orgco_ci')
        batch_op.drop_index('ix_party_org_details_orgbr_ci')
        batch_op.drop_index('ix_party_org_details_contact_ci')

    op.drop_table('party_organization_details')
    with op.batch_alter_table('party_commercial_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_party_commercial_policies_updated_at'))
        batch_op.drop_index(batch_op.f('ix_party_commercial_policies_created_at'))
        batch_op.drop_index(batch_op.f('ix_party_commercial_policies_company_id'))

    op.drop_table('party_commercial_policies')
    with op.batch_alter_table('branch_item_pricing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branch_item_pricing_updated_at'))
        batch_op.drop_index(batch_op.f('ix_branch_item_pricing_created_at'))
        batch_op.drop_index('ix_branch_item_pricing_company_id')

    op.drop_table('branch_item_pricing')
    with op.batch_alter_table('bins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bins_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_bins_updated_at'))
        batch_op.drop_index(batch_op.f('ix_bins_item_id'))
        batch_op.drop_index(batch_op.f('ix_bins_created_at'))
        batch_op.drop_index(batch_op.f('ix_bins_company_id'))
        batch_op.drop_index(batch_op.f('ix_bins_code'))
        batch_op.drop_index('idx_bin_item_warehouse')
        batch_op.drop_index('idx_bin_company_warehouse')

    op.drop_table('bins')
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouses_updated_at'))
        batch_op.drop_index(batch_op.f('ix_warehouses_parent_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_warehouses_created_at'))
        batch_op.drop_index(batch_op.f('ix_warehouses_company_id'))
        batch_op.drop_index(batch_op.f('ix_warehouses_code'))
        batch_op.drop_index(batch_op.f('ix_warehouses_branch_id'))
        batch_op.drop_index('ix_warehouse_parent')

    op.drop_table('warehouses')
    with op.batch_alter_table('stock_reconciliations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_reconciliations_updated_at'))
        batch_op.drop_index(batch_op.f('ix_stock_reconciliations_purpose'))
        batch_op.drop_index(batch_op.f('ix_stock_reconciliations_posting_date'))
        batch_op.drop_index(batch_op.f('ix_stock_reconciliations_doc_status'))
        batch_op.drop_index(batch_op.f('ix_stock_reconciliations_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_stock_reconciliations_created_at'))
        batch_op.drop_index(batch_op.f('ix_stock_reconciliations_company_id'))
        batch_op.drop_index(batch_op.f('ix_stock_reconciliations_code'))
        batch_op.drop_index(batch_op.f('ix_stock_reconciliations_branch_id'))
        batch_op.drop_index('ix_reconciliation_company_purpose')
        batch_op.drop_index('ix_reconciliation_company_posting_date')
        batch_op.drop_index('ix_reconciliation_company_branch_status')

    op.drop_table('stock_reconciliations')
    with op.batch_alter_table('stock_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_entries_updated_at'))
        batch_op.drop_index(batch_op.f('ix_stock_entries_stock_entry_type'))
        batch_op.drop_index(batch_op.f('ix_stock_entries_posting_date'))
        batch_op.drop_index(batch_op.f('ix_stock_entries_doc_status'))
        batch_op.drop_index(batch_op.f('ix_stock_entries_created_at'))
        batch_op.drop_index(batch_op.f('ix_stock_entries_company_id'))
        batch_op.drop_index(batch_op.f('ix_stock_entries_code'))
        batch_op.drop_index(batch_op.f('ix_stock_entries_branch_id'))

    op.drop_table('stock_entries')
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.drop_index('ix_party_company_role_phone')
        batch_op.drop_index('ix_party_company_role_name_ci')
        batch_op.drop_index('ix_party_company_branch_role')
        batch_op.drop_index(batch_op.f('ix_parties_updated_at'))
        batch_op.drop_index(batch_op.f('ix_parties_status'))
        batch_op.drop_index('ix_parties_role_type')
        batch_op.drop_index(batch_op.f('ix_parties_role'))
        batch_op.drop_index(batch_op.f('ix_parties_nature'))
        batch_op.drop_index(batch_op.f('ix_parties_name'))
        batch_op.drop_index(batch_op.f('ix_parties_is_cash_party'))
        batch_op.drop_index(batch_op.f('ix_parties_img_key'))
        batch_op.drop_index(batch_op.f('ix_parties_created_at'))
        batch_op.drop_index('ix_parties_company_role_name')
        batch_op.drop_index('ix_parties_company_id')
        batch_op.drop_index('ix_parties_code')
        batch_op.drop_index(batch_op.f('ix_parties_city_id'))
        batch_op.drop_index(batch_op.f('ix_parties_branch_id'))

    op.drop_table('parties')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_updated_at'))
        batch_op.drop_index(batch_op.f('ix_items_sku'))
        batch_op.drop_index(batch_op.f('ix_items_name'))
        batch_op.drop_index(batch_op.f('ix_items_created_at'))
        batch_op.drop_index(batch_op.f('ix_items_company_id'))

    op.drop_table('items')
    with op.batch_alter_table('units_of_measure', schema=None) as batch_op:
        batch_op.drop_index('ix_uoms_company_id')
        batch_op.drop_index(batch_op.f('ix_units_of_measure_updated_at'))
        batch_op.drop_index(batch_op.f('ix_units_of_measure_created_at'))
        batch_op.drop_index(batch_op.f('ix_units_of_measure_company_id'))

    op.drop_table('units_of_measure')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_updated_at'))
        batch_op.drop_index(batch_op.f('ix_brands_created_at'))
        batch_op.drop_index(batch_op.f('ix_brands_company_id'))

    op.drop_table('brands')
    with op.batch_alter_table('document_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_types_updated_at'))
        batch_op.drop_index(batch_op.f('ix_document_types_domain'))
        batch_op.drop_index(batch_op.f('ix_document_types_created_at'))
        batch_op.drop_index(batch_op.f('ix_document_types_code'))
        batch_op.drop_index(batch_op.f('ix_document_types_affects_stock'))
        batch_op.drop_index(batch_op.f('ix_document_types_affects_gl'))

    op.drop_table('document_types')
    # ### end Alembic commands ###
