"""added new models related schareholders and print

Revision ID: e10a918f6a7f
Revises: 268f9dc8f190
Create Date: 2025-12-04 23:30:20.707625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10a918f6a7f'
down_revision = '268f9dc8f190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('print_letterheads',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('header_based_on_image', sa.Boolean(), nullable=False),
    sa.Column('header_image_key', sa.String(length=512), nullable=True),
    sa.Column('header_image_height', sa.Integer(), nullable=True),
    sa.Column('header_image_width', sa.Integer(), nullable=True),
    sa.Column('header_align', sa.Enum('LEFT', 'CENTER', 'RIGHT', name='printalign'), nullable=False),
    sa.Column('header_html', sa.Text(), nullable=True),
    sa.Column('footer_based_on_image', sa.Boolean(), nullable=False),
    sa.Column('footer_image_key', sa.String(length=512), nullable=True),
    sa.Column('footer_image_height', sa.Integer(), nullable=True),
    sa.Column('footer_image_width', sa.Integer(), nullable=True),
    sa.Column('footer_align', sa.Enum('LEFT', 'CENTER', 'RIGHT', name='printalign'), nullable=False),
    sa.Column('footer_html', sa.Text(), nullable=True),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.Column('is_default_for_company', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('print_letterheads', schema=None) as batch_op:
        batch_op.create_index('ix_print_letterheads_company_default', ['company_id', 'is_default_for_company'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_letterheads_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_letterheads_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_letterheads_is_default_for_company'), ['is_default_for_company'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_letterheads_is_disabled'), ['is_disabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_letterheads_updated_at'), ['updated_at'], unique=False)

    op.create_table('print_styles',
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('css', sa.Text(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.Column('is_default_global', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('print_styles', schema=None) as batch_op:
        batch_op.create_index('ix_print_styles_company_code', ['company_id', 'code'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_styles_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_styles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_styles_is_default_global'), ['is_default_global'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_styles_is_disabled'), ['is_disabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_styles_updated_at'), ['updated_at'], unique=False)

    op.create_table('share_types',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment="Short code (e.g. 'ORD', 'PREF-A')."),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Full name of the share class.'),
    sa.Column('nominal_value', sa.Numeric(precision=18, scale=4), nullable=False, comment='Face value per share in company base currency.'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='Marks the primary share class for the company.'),
    sa.Column('total_authorised_shares', sa.BigInteger(), nullable=True, comment='Authorised share capital (number of shares) for this class (optional).'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='share_type_status_enum'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_share_type_company_code')
    )
    with op.batch_alter_table('share_types', schema=None) as batch_op:
        batch_op.create_index('ix_share_type_company_name', ['company_id', 'name'], unique=False)
        batch_op.create_index('ix_share_type_company_status', ['company_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_types_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_types_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_types_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_types_is_default'), ['is_default'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_types_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_types_updated_at'), ['updated_at'], unique=False)

    op.create_table('shareholders',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment="Programmatic Shareholder ID (e.g. 'ACC-SH-0001')."),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment='Legal/display name of the shareholder (person or entity).'),
    sa.Column('category', sa.Enum('INDIVIDUAL', 'COMPANY', 'GOVERNMENT', 'OTHER', name='shareholdercategoryenum'), nullable=False),
    sa.Column('national_id', sa.String(length=100), nullable=True, comment='National ID / passport for individuals.'),
    sa.Column('registration_no', sa.String(length=100), nullable=True, comment='Registration number if shareholder is a company.'),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True, comment='Free-text mailing address.'),
    sa.Column('img_key', sa.String(length=512), nullable=True, comment='Object-storage key/path for profile image or document scan.'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='shareholder_status_enum'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_shareholder_company_code')
    )
    with op.batch_alter_table('shareholders', schema=None) as batch_op:
        batch_op.create_index('ix_shareholder_company_name', ['company_id', 'full_name'], unique=False)
        batch_op.create_index('ix_shareholder_company_status', ['company_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_shareholders_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_shareholders_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_shareholders_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shareholders_contact_email'), ['contact_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_shareholders_contact_phone'), ['contact_phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_shareholders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shareholders_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_shareholders_img_key'), ['img_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_shareholders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_shareholders_updated_at'), ['updated_at'], unique=False)

    op.create_table('print_formats',
    sa.Column('doctype', sa.String(length=140), nullable=False),
    sa.Column('module', sa.String(length=140), nullable=True),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('default_print_language', sa.String(length=16), nullable=True),
    sa.Column('is_standard', sa.Boolean(), nullable=False),
    sa.Column('is_default_for_doctype', sa.Boolean(), nullable=False),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.Column('print_format_type', sa.Enum('STANDARD_BUILDER', 'JINJA', 'RAW', 'EXTERNAL_URL', name='printformattype'), nullable=False),
    sa.Column('custom_format', sa.Boolean(), nullable=False),
    sa.Column('raw_printing', sa.Boolean(), nullable=False),
    sa.Column('margin_top_mm', sa.Integer(), nullable=False),
    sa.Column('margin_bottom_mm', sa.Integer(), nullable=False),
    sa.Column('margin_left_mm', sa.Integer(), nullable=False),
    sa.Column('margin_right_mm', sa.Integer(), nullable=False),
    sa.Column('font_size_pt', sa.Integer(), nullable=True),
    sa.Column('google_font', sa.String(length=100), nullable=True),
    sa.Column('align_labels_to_right', sa.Boolean(), nullable=False),
    sa.Column('show_section_headings', sa.Boolean(), nullable=False),
    sa.Column('show_line_breaks_after_sections', sa.Boolean(), nullable=False),
    sa.Column('template_html', sa.Text(), nullable=True),
    sa.Column('custom_css', sa.Text(), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('raw_payload_template', sa.Text(), nullable=True),
    sa.Column('default_letterhead_id', sa.BigInteger(), nullable=True),
    sa.Column('print_style_id', sa.BigInteger(), nullable=True),
    sa.Column('layout_options', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['default_letterhead_id'], ['print_letterheads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['print_style_id'], ['print_styles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('print_formats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_print_formats_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_formats_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_formats_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_formats_custom_format'), ['custom_format'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_formats_default_letterhead_id'), ['default_letterhead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_formats_doctype'), ['doctype'], unique=False)
        batch_op.create_index('ix_print_formats_doctype_company_default', ['doctype', 'company_id', 'is_default_for_doctype'], unique=False)
        batch_op.create_index('ix_print_formats_doctype_standard', ['doctype', 'is_standard'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_formats_is_default_for_doctype'), ['is_default_for_doctype'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_formats_is_disabled'), ['is_disabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_formats_is_standard'), ['is_standard'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_formats_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_formats_print_style_id'), ['print_style_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_formats_updated_at'), ['updated_at'], unique=False)

    op.create_table('print_settings',
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('send_print_as_pdf', sa.Boolean(), nullable=False),
    sa.Column('send_email_print_attachments_as_pdf', sa.Boolean(), nullable=False),
    sa.Column('repeat_header_footer_in_pdf', sa.Boolean(), nullable=False),
    sa.Column('pdf_page_size', sa.Enum('A3', 'A4', 'A5', 'LETTER', 'LEGAL', 'CUSTOM', name='pdfpagesize'), nullable=False),
    sa.Column('print_with_letterhead', sa.Boolean(), nullable=False),
    sa.Column('compact_item_print', sa.Boolean(), nullable=False),
    sa.Column('print_uom_after_qty', sa.Boolean(), nullable=False),
    sa.Column('allow_print_for_draft', sa.Boolean(), nullable=False),
    sa.Column('always_add_draft_heading', sa.Boolean(), nullable=False),
    sa.Column('allow_page_break_inside_tables', sa.Boolean(), nullable=False),
    sa.Column('allow_print_for_cancelled', sa.Boolean(), nullable=False),
    sa.Column('print_taxes_with_zero_amount', sa.Boolean(), nullable=False),
    sa.Column('enable_raw_printing', sa.Boolean(), nullable=False),
    sa.Column('default_print_style_id', sa.BigInteger(), nullable=True),
    sa.Column('default_font_family', sa.String(length=100), nullable=True),
    sa.Column('default_font_size_pt', sa.Integer(), nullable=True),
    sa.Column('default_language', sa.String(length=16), nullable=True),
    sa.Column('additional_options', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['default_print_style_id'], ['print_styles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', name='uq_print_settings_company')
    )
    with op.batch_alter_table('print_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_print_settings_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_settings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_settings_default_print_style_id'), ['default_print_style_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_settings_updated_at'), ['updated_at'], unique=False)

    op.create_table('shareholder_emergency_contacts',
    sa.Column('shareholder_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Name of the emergency contact person.'),
    sa.Column('phone', sa.String(length=50), nullable=False, comment='Phone number of the emergency contact.'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Email of the emergency contact.'),
    sa.Column('relationship_to_shareholder', sa.String(length=100), nullable=True, comment='Relationship (e.g., spouse, family, lawyer).'),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shareholder_id'], ['shareholders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shareholder_emergency_contacts', schema=None) as batch_op:
        batch_op.create_index('ix_sh_emergency_contact_shareholder', ['shareholder_id', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_shareholder_emergency_contacts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shareholder_emergency_contacts_shareholder_id'), ['shareholder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shareholder_emergency_contacts_updated_at'), ['updated_at'], unique=False)

    op.create_table('print_format_field_templates',
    sa.Column('print_format_id', sa.BigInteger(), nullable=False),
    sa.Column('doctype', sa.String(length=140), nullable=False),
    sa.Column('field_name', sa.String(length=140), nullable=False),
    sa.Column('field_label', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('template_html', sa.Text(), nullable=False),
    sa.Column('is_default_for_field', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['print_format_id'], ['print_formats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('print_format_id', 'field_name', 'language', name='uq_pfft_format_field_lang')
    )
    with op.batch_alter_table('print_format_field_templates', schema=None) as batch_op:
        batch_op.create_index('ix_pfft_format_field', ['print_format_id', 'field_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_format_field_templates_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_format_field_templates_doctype'), ['doctype'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_format_field_templates_field_name'), ['field_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_format_field_templates_is_default_for_field'), ['is_default_for_field'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_format_field_templates_print_format_id'), ['print_format_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_format_field_templates_updated_at'), ['updated_at'], unique=False)

    op.create_table('share_ledger_entries',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('shareholder_id', sa.BigInteger(), nullable=False),
    sa.Column('share_type_id', sa.BigInteger(), nullable=False),
    sa.Column('posting_date', sa.DateTime(timezone=True), nullable=False, comment='Effective date of this share movement.'),
    sa.Column('transaction_type', sa.Enum('ISSUE', 'TRANSFER_IN', 'TRANSFER_OUT', 'REDEMPTION', 'BONUS', 'ADJUSTMENT', name='sharetransactiontypeenum'), nullable=False, comment='Why this movement happened (Issue, Transfer, Redemption, etc.).'),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False, comment='Positive for in; negative for out.'),
    sa.Column('rate', sa.Numeric(precision=18, scale=6), nullable=False, comment='Price per share in company base currency.'),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False, comment='Total value = quantity * rate. Capital added/removed for this movement.'),
    sa.Column('journal_entry_id', sa.BigInteger(), nullable=True, comment='Related Journal Entry for capital injection, redemption, etc.'),
    sa.Column('source_doctype_id', sa.BigInteger(), nullable=True),
    sa.Column('source_doc_id', sa.BigInteger(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity <> 0', name='ck_sle_quantity_non_zero'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['share_type_id'], ['share_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shareholder_id'], ['shareholders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_doctype_id'], ['document_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('share_ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_ledger_entries_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_ledger_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_ledger_entries_journal_entry_id'), ['journal_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_ledger_entries_posting_date'), ['posting_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_ledger_entries_share_type_id'), ['share_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_ledger_entries_shareholder_id'), ['shareholder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_ledger_entries_source_doc_id'), ['source_doc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_ledger_entries_source_doctype_id'), ['source_doctype_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_ledger_entries_transaction_type'), ['transaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_ledger_entries_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_sle_company_date', ['company_id', 'posting_date'], unique=False)
        batch_op.create_index('ix_sle_company_shareholder', ['company_id', 'shareholder_id'], unique=False)
        batch_op.create_index('ix_sle_company_sharetype', ['company_id', 'share_type_id'], unique=False)

    with op.batch_alter_table('period_closing_vouchers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_pcv_fiscal_year_company', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('period_closing_vouchers', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_pcv_fiscal_year_company', ['closing_fiscal_year_id', 'company_id'])

    with op.batch_alter_table('share_ledger_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_sle_company_sharetype')
        batch_op.drop_index('ix_sle_company_shareholder')
        batch_op.drop_index('ix_sle_company_date')
        batch_op.drop_index(batch_op.f('ix_share_ledger_entries_updated_at'))
        batch_op.drop_index(batch_op.f('ix_share_ledger_entries_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_share_ledger_entries_source_doctype_id'))
        batch_op.drop_index(batch_op.f('ix_share_ledger_entries_source_doc_id'))
        batch_op.drop_index(batch_op.f('ix_share_ledger_entries_shareholder_id'))
        batch_op.drop_index(batch_op.f('ix_share_ledger_entries_share_type_id'))
        batch_op.drop_index(batch_op.f('ix_share_ledger_entries_posting_date'))
        batch_op.drop_index(batch_op.f('ix_share_ledger_entries_journal_entry_id'))
        batch_op.drop_index(batch_op.f('ix_share_ledger_entries_created_at'))
        batch_op.drop_index(batch_op.f('ix_share_ledger_entries_company_id'))

    op.drop_table('share_ledger_entries')
    with op.batch_alter_table('print_format_field_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_print_format_field_templates_updated_at'))
        batch_op.drop_index(batch_op.f('ix_print_format_field_templates_print_format_id'))
        batch_op.drop_index(batch_op.f('ix_print_format_field_templates_is_default_for_field'))
        batch_op.drop_index(batch_op.f('ix_print_format_field_templates_field_name'))
        batch_op.drop_index(batch_op.f('ix_print_format_field_templates_doctype'))
        batch_op.drop_index(batch_op.f('ix_print_format_field_templates_created_at'))
        batch_op.drop_index('ix_pfft_format_field')

    op.drop_table('print_format_field_templates')
    with op.batch_alter_table('shareholder_emergency_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shareholder_emergency_contacts_updated_at'))
        batch_op.drop_index(batch_op.f('ix_shareholder_emergency_contacts_shareholder_id'))
        batch_op.drop_index(batch_op.f('ix_shareholder_emergency_contacts_created_at'))
        batch_op.drop_index('ix_sh_emergency_contact_shareholder')

    op.drop_table('shareholder_emergency_contacts')
    with op.batch_alter_table('print_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_print_settings_updated_at'))
        batch_op.drop_index(batch_op.f('ix_print_settings_default_print_style_id'))
        batch_op.drop_index(batch_op.f('ix_print_settings_created_at'))
        batch_op.drop_index(batch_op.f('ix_print_settings_company_id'))

    op.drop_table('print_settings')
    with op.batch_alter_table('print_formats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_print_formats_updated_at'))
        batch_op.drop_index(batch_op.f('ix_print_formats_print_style_id'))
        batch_op.drop_index(batch_op.f('ix_print_formats_module'))
        batch_op.drop_index(batch_op.f('ix_print_formats_is_standard'))
        batch_op.drop_index(batch_op.f('ix_print_formats_is_disabled'))
        batch_op.drop_index(batch_op.f('ix_print_formats_is_default_for_doctype'))
        batch_op.drop_index('ix_print_formats_doctype_standard')
        batch_op.drop_index('ix_print_formats_doctype_company_default')
        batch_op.drop_index(batch_op.f('ix_print_formats_doctype'))
        batch_op.drop_index(batch_op.f('ix_print_formats_default_letterhead_id'))
        batch_op.drop_index(batch_op.f('ix_print_formats_custom_format'))
        batch_op.drop_index(batch_op.f('ix_print_formats_created_at'))
        batch_op.drop_index(batch_op.f('ix_print_formats_company_id'))
        batch_op.drop_index(batch_op.f('ix_print_formats_code'))

    op.drop_table('print_formats')
    with op.batch_alter_table('shareholders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shareholders_updated_at'))
        batch_op.drop_index(batch_op.f('ix_shareholders_status'))
        batch_op.drop_index(batch_op.f('ix_shareholders_img_key'))
        batch_op.drop_index(batch_op.f('ix_shareholders_full_name'))
        batch_op.drop_index(batch_op.f('ix_shareholders_created_at'))
        batch_op.drop_index(batch_op.f('ix_shareholders_contact_phone'))
        batch_op.drop_index(batch_op.f('ix_shareholders_contact_email'))
        batch_op.drop_index(batch_op.f('ix_shareholders_company_id'))
        batch_op.drop_index(batch_op.f('ix_shareholders_code'))
        batch_op.drop_index(batch_op.f('ix_shareholders_category'))
        batch_op.drop_index('ix_shareholder_company_status')
        batch_op.drop_index('ix_shareholder_company_name')

    op.drop_table('shareholders')
    with op.batch_alter_table('share_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_types_updated_at'))
        batch_op.drop_index(batch_op.f('ix_share_types_status'))
        batch_op.drop_index(batch_op.f('ix_share_types_is_default'))
        batch_op.drop_index(batch_op.f('ix_share_types_created_at'))
        batch_op.drop_index(batch_op.f('ix_share_types_company_id'))
        batch_op.drop_index(batch_op.f('ix_share_types_code'))
        batch_op.drop_index('ix_share_type_company_status')
        batch_op.drop_index('ix_share_type_company_name')

    op.drop_table('share_types')
    with op.batch_alter_table('print_styles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_print_styles_updated_at'))
        batch_op.drop_index(batch_op.f('ix_print_styles_is_disabled'))
        batch_op.drop_index(batch_op.f('ix_print_styles_is_default_global'))
        batch_op.drop_index(batch_op.f('ix_print_styles_created_at'))
        batch_op.drop_index(batch_op.f('ix_print_styles_company_id'))
        batch_op.drop_index('ix_print_styles_company_code')

    op.drop_table('print_styles')
    with op.batch_alter_table('print_letterheads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_print_letterheads_updated_at'))
        batch_op.drop_index(batch_op.f('ix_print_letterheads_is_disabled'))
        batch_op.drop_index(batch_op.f('ix_print_letterheads_is_default_for_company'))
        batch_op.drop_index(batch_op.f('ix_print_letterheads_created_at'))
        batch_op.drop_index(batch_op.f('ix_print_letterheads_company_id'))
        batch_op.drop_index('ix_print_letterheads_company_default')

    op.drop_table('print_letterheads')
    # ### end Alembic commands ###
