"""Add assessment / exams  models

Revision ID: e22c666e3f00
Revises: ea987e721bf1
Create Date: 2025-12-16 18:56:37.536709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e22c666e3f00'
down_revision = 'ea987e721bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edu_assessment_criteria',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_criterion_name_per_company')
    )
    with op.batch_alter_table('edu_assessment_criteria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edu_assessment_criteria_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_criteria_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_criteria_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_criteria_updated_at'), ['updated_at'], unique=False)

    op.create_table('edu_grading_scales',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='Default grading scale for company when no other scale is specified.'),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_grading_scale_name_per_company')
    )
    with op.batch_alter_table('edu_grading_scales', schema=None) as batch_op:
        batch_op.create_index('ix_edu_grading_scales_company_id', ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_grading_scales_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_grading_scales_is_default'), ['is_default'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_grading_scales_updated_at'), ['updated_at'], unique=False)

    op.create_table('edu_grading_scale_breakpoints',
    sa.Column('grading_scale_id', sa.BigInteger(), nullable=False),
    sa.Column('grade_code', sa.String(length=10), nullable=False, comment="Label like 'A+', 'A', 'B', etc."),
    sa.Column('min_percentage', sa.Float(), nullable=False, comment='Inclusive lower bound, e.g. 80.0'),
    sa.Column('max_percentage', sa.Float(), nullable=True, comment='Optional upper bound; NULL means up to 100.'),
    sa.Column('grade_point', sa.Float(), nullable=True, comment='Optional GPA / grade points, e.g. 4.0.'),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('sequence_no', sa.Integer(), nullable=True, comment='Sort order in UI.'),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('(max_percentage IS NULL) OR (min_percentage <= max_percentage)', name='ck_grade_bp_min_le_max'),
    sa.CheckConstraint('min_percentage >= 0 AND (max_percentage IS NULL OR max_percentage <= 100)', name='ck_grade_bp_percentage_range'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grading_scale_id'], ['edu_grading_scales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grading_scale_id', 'grade_code', name='uq_grade_code_per_scale')
    )
    with op.batch_alter_table('edu_grading_scale_breakpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edu_grading_scale_breakpoints_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_grading_scale_breakpoints_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_grading_scale_breakpoints_grading_scale_id'), ['grading_scale_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_grading_scale_breakpoints_updated_at'), ['updated_at'], unique=False)

    op.create_table('edu_assessment_schemes',
    sa.Column('name', sa.String(length=120), nullable=False, comment="Friendly name e.g. 'Grade 1 - Term 1 - 2025 Scheme'."),
    sa.Column('program_id', sa.BigInteger(), nullable=False),
    sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
    sa.Column('academic_term_id', sa.BigInteger(), nullable=False),
    sa.Column('grading_scale_id', sa.BigInteger(), nullable=True, comment='Default grading scale for this scheme; if NULL use company default.'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='If True, this scheme is the default for this program/year/term.'),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True, comment='User who created this scheme template.'),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['academic_term_id'], ['edu_academic_terms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['edu_academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grading_scale_id'], ['edu_grading_scales.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_id'], ['edu_programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'program_id', 'academic_year_id', 'academic_term_id', 'name', name='uq_scheme_program_year_term_name')
    )
    with op.batch_alter_table('edu_assessment_schemes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edu_assessment_schemes_academic_term_id'), ['academic_term_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_schemes_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_schemes_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_edu_assessment_schemes_company_program_year_term', ['company_id', 'program_id', 'academic_year_id', 'academic_term_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_schemes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_schemes_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_schemes_grading_scale_id'), ['grading_scale_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_schemes_is_default'), ['is_default'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_schemes_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_schemes_updated_at'), ['updated_at'], unique=False)

    op.create_table('edu_student_annual_results',
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('program_id', sa.BigInteger(), nullable=False),
    sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('average_percent', sa.Float(), nullable=True, comment='Average across subjects (0..100).'),
    sa.Column('position_in_section', sa.Integer(), nullable=True),
    sa.Column('position_overall', sa.Integer(), nullable=True),
    sa.Column('is_passed', sa.Boolean(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['edu_academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['edu_programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'student_id', 'academic_year_id', name='uq_sar_student_year')
    )
    with op.batch_alter_table('edu_student_annual_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edu_student_annual_results_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_student_annual_results_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index('ix_edu_student_annual_results_company_branch', ['company_id', 'branch_id'], unique=False)
        batch_op.create_index('ix_edu_student_annual_results_company_id', ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_student_annual_results_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_student_annual_results_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_student_annual_results_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_student_annual_results_updated_at'), ['updated_at'], unique=False)

    op.create_table('edu_student_course_grades',
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('program_id', sa.BigInteger(), nullable=False),
    sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
    sa.Column('academic_term_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('final_percent', sa.Float(), nullable=True, comment='Final weighted % (0..100).'),
    sa.Column('final_grade_code', sa.String(length=10), nullable=True),
    sa.Column('final_grade_point', sa.Float(), nullable=True),
    sa.Column('is_passed', sa.Boolean(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('(final_percent IS NULL) OR (final_percent >= 0 AND final_percent <= 100)', name='ck_scg_final_percent_range'),
    sa.ForeignKeyConstraint(['academic_term_id'], ['edu_academic_terms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['edu_academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['edu_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['edu_programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'student_id', 'course_id', 'academic_year_id', 'academic_term_id', name='uq_scg_student_course_year_term')
    )
    with op.batch_alter_table('edu_student_course_grades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edu_student_course_grades_academic_term_id'), ['academic_term_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_student_course_grades_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_student_course_grades_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index('ix_edu_student_course_grades_company_branch', ['company_id', 'branch_id'], unique=False)
        batch_op.create_index('ix_edu_student_course_grades_company_id', ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_student_course_grades_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_student_course_grades_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_student_course_grades_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_student_course_grades_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_student_course_grades_updated_at'), ['updated_at'], unique=False)

    op.create_table('edu_student_result_holds',
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
    sa.Column('hold_type', sa.Enum('FEES', 'DISCIPLINE', 'OTHER', name='edu_result_hold_type_enum'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['edu_academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'student_id', 'academic_year_id', 'hold_type', name='uq_srh_student_year_type')
    )
    with op.batch_alter_table('edu_student_result_holds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edu_student_result_holds_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_student_result_holds_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_student_result_holds_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_student_result_holds_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_student_result_holds_updated_at'), ['updated_at'], unique=False)

    op.create_table('edu_assessment_components',
    sa.Column('scheme_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False, comment="Short code e.g. 'M1', 'MID', 'FIN'. Must be unique per scheme."),
    sa.Column('sequence_no', sa.Integer(), nullable=True, comment='Sort order in UI.'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('is_group', sa.Boolean(), nullable=False, comment='True if grouping node only (not a real exam).'),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['edu_assessment_components.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scheme_id'], ['edu_assessment_schemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_id', 'code', name='uq_component_code_per_scheme'),
    sa.UniqueConstraint('scheme_id', 'name', name='uq_component_name_per_scheme')
    )
    with op.batch_alter_table('edu_assessment_components', schema=None) as batch_op:
        batch_op.create_index('ix_edu_assessment_components_company_id', ['company_id'], unique=False)
        batch_op.create_index('ix_edu_assessment_components_company_scheme', ['company_id', 'scheme_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_components_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_components_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_components_scheme_id'), ['scheme_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_components_updated_at'), ['updated_at'], unique=False)

    op.create_table('edu_assessment_component_rules',
    sa.Column('scheme_id', sa.BigInteger(), nullable=False),
    sa.Column('component_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('max_points', sa.Float(), nullable=False, comment='Max raw points for this course in this component.'),
    sa.Column('weight_percent', sa.Float(), nullable=False, comment='Contribution (%) of this component to final course grade.'),
    sa.Column('passing_percent', sa.Float(), nullable=True, comment='Optional pass threshold for this component (0..100).'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='Disable rule without deleting it.'),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('(passing_percent IS NULL) OR (passing_percent >= 0 AND passing_percent <= 100)', name='ck_rule_pass_percent_range'),
    sa.CheckConstraint('(weight_percent > 0) AND (weight_percent <= 100)', name='ck_rule_weight_range'),
    sa.CheckConstraint('max_points > 0', name='ck_rule_max_points_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['component_id'], ['edu_assessment_components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['edu_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheme_id'], ['edu_assessment_schemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_id', 'component_id', 'course_id', name='uq_rule_scheme_component_course')
    )
    with op.batch_alter_table('edu_assessment_component_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edu_assessment_component_rules_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_edu_assessment_component_rules_company_scheme_course', ['company_id', 'scheme_id', 'course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_component_rules_component_id'), ['component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_component_rules_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_component_rules_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_component_rules_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_component_rules_scheme_id'), ['scheme_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_component_rules_updated_at'), ['updated_at'], unique=False)

    op.create_table('edu_assessment_events',
    sa.Column('scheme_id', sa.BigInteger(), nullable=True, comment='Scheme used when creating this event (optional but recommended).'),
    sa.Column('component_id', sa.BigInteger(), nullable=False),
    sa.Column('program_id', sa.BigInteger(), nullable=False),
    sa.Column('student_group_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
    sa.Column('academic_term_id', sa.BigInteger(), nullable=False, comment='NOT NULL ERP standard. Use ANNUAL term for yearly-only schools.'),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('schedule_date', sa.Date(), nullable=True),
    sa.Column('from_time', sa.Time(), nullable=True),
    sa.Column('to_time', sa.Time(), nullable=True),
    sa.Column('max_points', sa.Float(), nullable=False, comment='Snapshot from rule.'),
    sa.Column('weight_percent', sa.Float(), nullable=False, comment='Snapshot from rule.'),
    sa.Column('grading_scale_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='edu_assessment_event_status_enum'), nullable=False),
    sa.Column('is_entry_open', sa.Boolean(), nullable=False),
    sa.Column('is_result_published', sa.Boolean(), nullable=False),
    sa.Column('allow_student_view', sa.Boolean(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False, comment='Retakes support. 1 = first attempt.'),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('attempt_no >= 1', name='ck_event_attempt_min_1'),
    sa.CheckConstraint('max_points > 0', name='ck_event_max_points_positive'),
    sa.CheckConstraint('weight_percent > 0 AND weight_percent <= 100', name='ck_event_weight_range'),
    sa.ForeignKeyConstraint(['academic_term_id'], ['edu_academic_terms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['edu_academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['component_id'], ['edu_assessment_components.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['course_id'], ['edu_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grading_scale_id'], ['edu_grading_scales.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_id'], ['edu_programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheme_id'], ['edu_assessment_schemes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_group_id'], ['edu_student_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'student_group_id', 'course_id', 'component_id', 'academic_year_id', 'academic_term_id', 'attempt_no', name='uq_event_group_course_component_year_term_attempt')
    )
    with op.batch_alter_table('edu_assessment_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edu_assessment_events_academic_term_id'), ['academic_term_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_events_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_events_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index('ix_edu_assessment_events_company_branch', ['company_id', 'branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_events_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_edu_assessment_events_company_program', ['company_id', 'program_id'], unique=False)
        batch_op.create_index('ix_edu_assessment_events_company_year_term', ['company_id', 'academic_year_id', 'academic_term_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_events_component_id'), ['component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_events_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_events_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_events_grading_scale_id'), ['grading_scale_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_events_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_events_scheme_id'), ['scheme_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_events_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_events_student_group_id'), ['student_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_events_updated_at'), ['updated_at'], unique=False)

    op.create_table('edu_grade_recalc_jobs',
    sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
    sa.Column('program_id', sa.BigInteger(), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('triggered_by_employee_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='edu_grade_recalc_status_enum'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['edu_academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['edu_programs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['triggered_by_employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('edu_grade_recalc_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edu_grade_recalc_jobs_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_grade_recalc_jobs_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index('ix_edu_grade_recalc_jobs_company_branch', ['company_id', 'branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_grade_recalc_jobs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_grade_recalc_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_grade_recalc_jobs_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_grade_recalc_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_grade_recalc_jobs_triggered_by_employee_id'), ['triggered_by_employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_grade_recalc_jobs_updated_at'), ['updated_at'], unique=False)

    op.create_table('edu_assessment_marks',
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=True, comment='Copied from event for reporting.'),
    sa.Column('attendance_status', sa.Enum('PRESENT', 'ABSENT', 'EXCUSED', 'NOT_EVALUATED', name='edu_assessment_attendance_enum'), nullable=False),
    sa.Column('score_points', sa.Float(), nullable=True, comment='Raw points obtained (0..event.max_points). NULL if not entered yet.'),
    sa.Column('entered_by_employee_id', sa.BigInteger(), nullable=True),
    sa.Column('last_updated_by_employee_id', sa.BigInteger(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('component_percent', sa.Float(), nullable=True, comment='(score_points / event.max_points) * 100'),
    sa.Column('weighted_percent', sa.Float(), nullable=True, comment='component_percent * (event.weight_percent / 100)'),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('(component_percent IS NULL) OR (component_percent >= 0 AND component_percent <= 100)', name='ck_mark_component_percent_range'),
    sa.CheckConstraint('(score_points IS NULL) OR (score_points >= 0)', name='ck_mark_score_nonneg'),
    sa.CheckConstraint('(weighted_percent IS NULL) OR (weighted_percent >= 0 AND weighted_percent <= 100)', name='ck_mark_weighted_percent_range'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entered_by_employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['edu_assessment_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_updated_by_employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'student_id', name='uq_mark_event_student')
    )
    with op.batch_alter_table('edu_assessment_marks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edu_assessment_marks_attendance_status'), ['attendance_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_marks_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index('ix_edu_assessment_marks_company_branch', ['company_id', 'branch_id'], unique=False)
        batch_op.create_index('ix_edu_assessment_marks_company_id', ['company_id'], unique=False)
        batch_op.create_index('ix_edu_assessment_marks_company_student', ['company_id', 'student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_marks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_marks_entered_by_employee_id'), ['entered_by_employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_marks_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_marks_last_updated_by_employee_id'), ['last_updated_by_employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_marks_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_marks_updated_at'), ['updated_at'], unique=False)

    op.create_table('edu_assessment_mark_items',
    sa.Column('mark_id', sa.BigInteger(), nullable=False),
    sa.Column('criterion_id', sa.BigInteger(), nullable=False),
    sa.Column('max_points', sa.Float(), nullable=True),
    sa.Column('score_points', sa.Float(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('(score_points IS NULL) OR (score_points >= 0)', name='ck_markitem_score_nonneg'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['criterion_id'], ['edu_assessment_criteria.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mark_id'], ['edu_assessment_marks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mark_id', 'criterion_id', name='uq_markitem_mark_criterion')
    )
    with op.batch_alter_table('edu_assessment_mark_items', schema=None) as batch_op:
        batch_op.create_index('ix_edu_assessment_mark_items_company_id', ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_mark_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_mark_items_criterion_id'), ['criterion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_mark_items_mark_id'), ['mark_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_assessment_mark_items_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edu_assessment_mark_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edu_assessment_mark_items_updated_at'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_mark_items_mark_id'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_mark_items_criterion_id'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_mark_items_created_at'))
        batch_op.drop_index('ix_edu_assessment_mark_items_company_id')

    op.drop_table('edu_assessment_mark_items')
    with op.batch_alter_table('edu_assessment_marks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edu_assessment_marks_updated_at'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_marks_student_id'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_marks_last_updated_by_employee_id'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_marks_event_id'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_marks_entered_by_employee_id'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_marks_created_at'))
        batch_op.drop_index('ix_edu_assessment_marks_company_student')
        batch_op.drop_index('ix_edu_assessment_marks_company_id')
        batch_op.drop_index('ix_edu_assessment_marks_company_branch')
        batch_op.drop_index(batch_op.f('ix_edu_assessment_marks_branch_id'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_marks_attendance_status'))

    op.drop_table('edu_assessment_marks')
    with op.batch_alter_table('edu_grade_recalc_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edu_grade_recalc_jobs_updated_at'))
        batch_op.drop_index(batch_op.f('ix_edu_grade_recalc_jobs_triggered_by_employee_id'))
        batch_op.drop_index(batch_op.f('ix_edu_grade_recalc_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_edu_grade_recalc_jobs_program_id'))
        batch_op.drop_index(batch_op.f('ix_edu_grade_recalc_jobs_created_at'))
        batch_op.drop_index(batch_op.f('ix_edu_grade_recalc_jobs_company_id'))
        batch_op.drop_index('ix_edu_grade_recalc_jobs_company_branch')
        batch_op.drop_index(batch_op.f('ix_edu_grade_recalc_jobs_branch_id'))
        batch_op.drop_index(batch_op.f('ix_edu_grade_recalc_jobs_academic_year_id'))

    op.drop_table('edu_grade_recalc_jobs')
    with op.batch_alter_table('edu_assessment_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edu_assessment_events_updated_at'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_events_student_group_id'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_events_status'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_events_scheme_id'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_events_program_id'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_events_grading_scale_id'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_events_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_events_course_id'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_events_component_id'))
        batch_op.drop_index('ix_edu_assessment_events_company_year_term')
        batch_op.drop_index('ix_edu_assessment_events_company_program')
        batch_op.drop_index(batch_op.f('ix_edu_assessment_events_company_id'))
        batch_op.drop_index('ix_edu_assessment_events_company_branch')
        batch_op.drop_index(batch_op.f('ix_edu_assessment_events_branch_id'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_events_academic_year_id'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_events_academic_term_id'))

    op.drop_table('edu_assessment_events')
    with op.batch_alter_table('edu_assessment_component_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edu_assessment_component_rules_updated_at'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_component_rules_scheme_id'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_component_rules_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_component_rules_created_at'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_component_rules_course_id'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_component_rules_component_id'))
        batch_op.drop_index('ix_edu_assessment_component_rules_company_scheme_course')
        batch_op.drop_index(batch_op.f('ix_edu_assessment_component_rules_company_id'))

    op.drop_table('edu_assessment_component_rules')
    with op.batch_alter_table('edu_assessment_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edu_assessment_components_updated_at'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_components_scheme_id'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_components_parent_id'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_components_created_at'))
        batch_op.drop_index('ix_edu_assessment_components_company_scheme')
        batch_op.drop_index('ix_edu_assessment_components_company_id')

    op.drop_table('edu_assessment_components')
    with op.batch_alter_table('edu_student_result_holds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edu_student_result_holds_updated_at'))
        batch_op.drop_index(batch_op.f('ix_edu_student_result_holds_student_id'))
        batch_op.drop_index(batch_op.f('ix_edu_student_result_holds_created_at'))
        batch_op.drop_index(batch_op.f('ix_edu_student_result_holds_company_id'))
        batch_op.drop_index(batch_op.f('ix_edu_student_result_holds_academic_year_id'))

    op.drop_table('edu_student_result_holds')
    with op.batch_alter_table('edu_student_course_grades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edu_student_course_grades_updated_at'))
        batch_op.drop_index(batch_op.f('ix_edu_student_course_grades_student_id'))
        batch_op.drop_index(batch_op.f('ix_edu_student_course_grades_program_id'))
        batch_op.drop_index(batch_op.f('ix_edu_student_course_grades_created_at'))
        batch_op.drop_index(batch_op.f('ix_edu_student_course_grades_course_id'))
        batch_op.drop_index('ix_edu_student_course_grades_company_id')
        batch_op.drop_index('ix_edu_student_course_grades_company_branch')
        batch_op.drop_index(batch_op.f('ix_edu_student_course_grades_branch_id'))
        batch_op.drop_index(batch_op.f('ix_edu_student_course_grades_academic_year_id'))
        batch_op.drop_index(batch_op.f('ix_edu_student_course_grades_academic_term_id'))

    op.drop_table('edu_student_course_grades')
    with op.batch_alter_table('edu_student_annual_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edu_student_annual_results_updated_at'))
        batch_op.drop_index(batch_op.f('ix_edu_student_annual_results_student_id'))
        batch_op.drop_index(batch_op.f('ix_edu_student_annual_results_program_id'))
        batch_op.drop_index(batch_op.f('ix_edu_student_annual_results_created_at'))
        batch_op.drop_index('ix_edu_student_annual_results_company_id')
        batch_op.drop_index('ix_edu_student_annual_results_company_branch')
        batch_op.drop_index(batch_op.f('ix_edu_student_annual_results_branch_id'))
        batch_op.drop_index(batch_op.f('ix_edu_student_annual_results_academic_year_id'))

    op.drop_table('edu_student_annual_results')
    with op.batch_alter_table('edu_assessment_schemes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edu_assessment_schemes_updated_at'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_schemes_program_id'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_schemes_is_default'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_schemes_grading_scale_id'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_schemes_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_schemes_created_at'))
        batch_op.drop_index('ix_edu_assessment_schemes_company_program_year_term')
        batch_op.drop_index(batch_op.f('ix_edu_assessment_schemes_company_id'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_schemes_academic_year_id'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_schemes_academic_term_id'))

    op.drop_table('edu_assessment_schemes')
    with op.batch_alter_table('edu_grading_scale_breakpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edu_grading_scale_breakpoints_updated_at'))
        batch_op.drop_index(batch_op.f('ix_edu_grading_scale_breakpoints_grading_scale_id'))
        batch_op.drop_index(batch_op.f('ix_edu_grading_scale_breakpoints_created_at'))
        batch_op.drop_index(batch_op.f('ix_edu_grading_scale_breakpoints_company_id'))

    op.drop_table('edu_grading_scale_breakpoints')
    with op.batch_alter_table('edu_grading_scales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edu_grading_scales_updated_at'))
        batch_op.drop_index(batch_op.f('ix_edu_grading_scales_is_default'))
        batch_op.drop_index(batch_op.f('ix_edu_grading_scales_created_at'))
        batch_op.drop_index('ix_edu_grading_scales_company_id')

    op.drop_table('edu_grading_scales')
    with op.batch_alter_table('edu_assessment_criteria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edu_assessment_criteria_updated_at'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_criteria_enabled'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_criteria_created_at'))
        batch_op.drop_index(batch_op.f('ix_edu_assessment_criteria_company_id'))

    op.drop_table('edu_assessment_criteria')
    # ### end Alembic commands ###
