"""Add timetable + student attendance

Revision ID: ea987e721bf1
Revises: 780e6d8ea698
Create Date: 2025-12-16 10:59:29.301994

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql  # ✅ ADDED


# revision identifiers, used by Alembic.
revision = 'ea987e721bf1'
down_revision = '780e6d8ea698'
branch_labels = None
depends_on = None


# ✅ ADDED: Use existing PostgreSQL enum type (do NOT recreate it on every new table)
docstatusenum = postgresql.ENUM(
    'DRAFT', 'SUBMITTED', 'CANCELLED', 'UNPAID', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'RETURNED',
    name='docstatusenum',
    create_type=False,
)


def upgrade():
    # ✅ ADDED: Ensure enum exists (safe on fresh DB + safe if already exists)
    bind = op.get_bind()
    docstatusenum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_sessions',
    sa.Column('name', sa.String(length=50), nullable=False, comment="Name: 'Morning', 'Afternoon', 'Evening', 'Quran Morning', etc."),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_session_name_per_company')
    )
    with op.batch_alter_table('school_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_sessions_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_sessions_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_sessions_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_sessions_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_sessions_company_id', ['company_id'], unique=False)

    op.create_table('classrooms',
    sa.Column('branch_id', sa.BigInteger(), nullable=False, comment='Branch/campus where this room exists.'),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('capacity IS NULL OR capacity >= 0', name='ck_classroom_capacity_nonneg'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'branch_id', 'name', name='uq_classroom_name_per_branch')
    )
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classrooms_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index('ix_classrooms_company_branch', ['company_id', 'branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classrooms_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classrooms_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_classrooms_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classrooms_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_classrooms_updated_at'), ['updated_at'], unique=False)

    op.create_table('time_slots',
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False, comment='1, 2, 3... order of period within the session.'),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('start_time < end_time', name='ck_timeslot_time_range'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['school_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'session_id', 'period_number', name='uq_timeslot_per_session_period')
    )
    with op.batch_alter_table('time_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_slots_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_slots_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_slots_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_slots_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_slots_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_slots_updated_at'), ['updated_at'], unique=False)

    op.create_table('course_assignments',
    sa.Column('student_group_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('teacher_id', sa.BigInteger(), nullable=False, comment='Teacher = Employee record.'),
    sa.Column('academic_year_id', sa.BigInteger(), nullable=True),
    sa.Column('academic_term_id', sa.BigInteger(), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('expected_periods_per_week', sa.Integer(), nullable=True, comment='For workload planning, e.g. 5 periods/week.'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True, comment='Optional: teacher starts mid-year.'),
    sa.Column('valid_to', sa.Date(), nullable=True, comment='Optional: teacher stops mid-year.'),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('(expected_periods_per_week IS NULL) OR (expected_periods_per_week >= 0)', name='ck_ca_expected_periods_nonneg'),
    sa.CheckConstraint('(valid_from IS NULL) OR (valid_to IS NULL) OR (valid_from <= valid_to)', name='ck_ca_valid_dates_ok'),
    sa.ForeignKeyConstraint(['academic_term_id'], ['edu_academic_terms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['edu_academic_years.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['edu_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_group_id'], ['edu_student_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'student_group_id', 'course_id', 'academic_year_id', 'academic_term_id', 'teacher_id', name='uq_ca_group_course_year_term_teacher')
    )
    with op.batch_alter_table('course_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_assignments_academic_term_id'), ['academic_term_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_assignments_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_assignments_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index('ix_course_assignments_company_branch', ['company_id', 'branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_assignments_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_assignments_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_assignments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_assignments_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_assignments_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_assignments_student_group_id'), ['student_group_id'], unique=False)
        batch_op.create_index('ix_course_assignments_teacher', ['teacher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_assignments_teacher_id'), ['teacher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_assignments_updated_at'), ['updated_at'], unique=False)

    op.create_table('course_schedule_slots',
    sa.Column('course_assignment_id', sa.BigInteger(), nullable=False),
    sa.Column('student_group_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('teacher_id', sa.BigInteger(), nullable=False),
    sa.Column('academic_year_id', sa.BigInteger(), nullable=True),
    sa.Column('academic_term_id', sa.BigInteger(), nullable=True),
    sa.Column('weekday', sa.Enum('SUN', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', name='schedule_weekday_enum'), nullable=False),
    sa.Column('time_slot_id', sa.BigInteger(), nullable=False),
    sa.Column('classroom_id', sa.BigInteger(), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('schedule_color', sa.String(length=50), nullable=True, comment="UI color tag, e.g. 'blue', '#00AEEF'."),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['academic_term_id'], ['edu_academic_terms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['edu_academic_years.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_assignment_id'], ['course_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['edu_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_group_id'], ['edu_student_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'classroom_id', 'weekday', 'time_slot_id', 'academic_year_id', 'academic_term_id', name='uq_css_classroom_timeslot_per_year_term'),
    sa.UniqueConstraint('company_id', 'student_group_id', 'weekday', 'time_slot_id', 'academic_year_id', 'academic_term_id', name='uq_css_group_timeslot_per_year_term'),
    sa.UniqueConstraint('company_id', 'teacher_id', 'weekday', 'time_slot_id', 'academic_year_id', 'academic_term_id', name='uq_css_teacher_timeslot_per_year_term')
    )
    with op.batch_alter_table('course_schedule_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_schedule_slots_academic_term_id'), ['academic_term_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_schedule_slots_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_schedule_slots_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_schedule_slots_classroom_id'), ['classroom_id'], unique=False)
        batch_op.create_index('ix_course_schedule_slots_company_id', ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_schedule_slots_course_assignment_id'), ['course_assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_schedule_slots_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_schedule_slots_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_schedule_slots_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_schedule_slots_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_schedule_slots_student_group_id'), ['student_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_schedule_slots_teacher_id'), ['teacher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_schedule_slots_time_slot_id'), ['time_slot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_schedule_slots_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_schedule_slots_weekday'), ['weekday'], unique=False)
        batch_op.create_index('ix_css_company_branch', ['company_id', 'branch_id'], unique=False)
        batch_op.create_index('ix_css_group_weekday', ['student_group_id', 'weekday', 'time_slot_id'], unique=False)
        batch_op.create_index('ix_css_teacher_weekday', ['teacher_id', 'weekday', 'time_slot_id'], unique=False)

    op.create_table('student_attendance',
    sa.Column('attendance_code', sa.String(length=100), nullable=False, comment="Human-readable attendance reference like 'EDU-ATT-2025-00001'."),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('source', sa.Enum('COURSE_SCHEDULE', 'STUDENT_GROUP', 'QURAN_SESSION', 'OTHER', name='attendance_source_enum'), nullable=False),
    sa.Column('academic_year_id', sa.BigInteger(), nullable=True),
    sa.Column('academic_term_id', sa.BigInteger(), nullable=True),
    sa.Column('program_id', sa.BigInteger(), nullable=True),
    sa.Column('student_group_id', sa.BigInteger(), nullable=True),
    sa.Column('course_id', sa.BigInteger(), nullable=True),
    sa.Column('course_assignment_id', sa.BigInteger(), nullable=True),
    sa.Column('schedule_slot_id', sa.BigInteger(), nullable=True),
    sa.Column('session_id', sa.BigInteger(), nullable=True, comment='Useful for Quran or simple session-based attendance.'),
    sa.Column('time_slot_id', sa.BigInteger(), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('taken_by_user_id', sa.BigInteger(), nullable=True, comment='User who submitted this attendance sheet.'),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),

    # ✅ ONLY FIX HERE: use existing enum type; do NOT recreate "docstatusenum"
    sa.Column('doc_status', docstatusenum, nullable=False, comment='Use SUBMITTED when attendance is final/locked.'),

    sa.Column('is_locked', sa.Boolean(), nullable=False, comment='If true, prevent further edits.'),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['academic_term_id'], ['edu_academic_terms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['edu_academic_years.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_assignment_id'], ['course_assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['edu_courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_id'], ['edu_programs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_slot_id'], ['course_schedule_slots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['school_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_group_id'], ['edu_student_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['taken_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'attendance_code', name='uq_attendance_code_per_company'),
    sa.UniqueConstraint('company_id', 'attendance_date', 'source', 'student_group_id', 'course_id', 'time_slot_id', 'schedule_slot_id', name='uq_attendance_sheet_context')
    )
    with op.batch_alter_table('student_attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_attendance_academic_term_id'), ['academic_term_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_attendance_code'), ['attendance_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_attendance_date'), ['attendance_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index('ix_student_attendance_company_branch', ['company_id', 'branch_id'], unique=False)
        batch_op.create_index('ix_student_attendance_company_date', ['company_id', 'attendance_date'], unique=False)
        batch_op.create_index('ix_student_attendance_company_group_date', ['company_id', 'student_group_id', 'attendance_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_course_assignment_id'), ['course_assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_doc_status'), ['doc_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_is_locked'), ['is_locked'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_schedule_slot_id'), ['schedule_slot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_student_group_id'), ['student_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_taken_at'), ['taken_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_taken_by_user_id'), ['taken_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_time_slot_id'), ['time_slot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_updated_at'), ['updated_at'], unique=False)

    op.create_table('student_attendance_rows',
    sa.Column('attendance_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('program_enrollment_id', sa.BigInteger(), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', 'EXCUSED', 'HALF_DAY', name='student_attendance_status_enum'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['attendance_id'], ['student_attendance.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_enrollment_id'], ['edu_program_enrollments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attendance_id', 'student_id', name='uq_attendance_student_once')
    )
    with op.batch_alter_table('student_attendance_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_attendance_rows_attendance_id'), ['attendance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_rows_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_rows_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_student_attendance_rows_company_student', ['company_id', 'student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_rows_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_rows_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_rows_program_enrollment_id'), ['program_enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_rows_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_rows_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_rows_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_attendance_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_attendance_rows_updated_at'))
        batch_op.drop_index(batch_op.f('ix_student_attendance_rows_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_attendance_rows_status'))
        batch_op.drop_index(batch_op.f('ix_student_attendance_rows_program_enrollment_id'))
        batch_op.drop_index(batch_op.f('ix_student_attendance_rows_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_student_attendance_rows_created_at'))
        batch_op.drop_index('ix_student_attendance_rows_company_student')
        batch_op.drop_index(batch_op.f('ix_student_attendance_rows_company_id'))
        batch_op.drop_index(batch_op.f('ix_student_attendance_rows_branch_id'))
        batch_op.drop_index(batch_op.f('ix_student_attendance_rows_attendance_id'))

    op.drop_table('student_attendance_rows')
    with op.batch_alter_table('student_attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_attendance_updated_at'))
        batch_op.drop_index(batch_op.f('ix_student_attendance_time_slot_id'))
        batch_op.drop_index(batch_op.f('ix_student_attendance_taken_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_student_attendance_taken_at'))
        batch_op.drop_index(batch_op.f('ix_student_attendance_student_group_id'))
        batch_op.drop_index(batch_op.f('ix_student_attendance_source'))
        batch_op.drop_index(batch_op.f('ix_student_attendance_session_id'))
        batch_op.drop_index(batch_op.f('ix_student_attendance_schedule_slot_id'))
        batch_op.drop_index(batch_op.f('ix_student_attendance_program_id'))
        batch_op.drop_index(batch_op.f('ix_student_attendance_is_locked'))
        batch_op.drop_index(batch_op.f('ix_student_attendance_doc_status'))
        batch_op.drop_index(batch_op.f('ix_student_attendance_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_student_attendance_created_at'))
        batch_op.drop_index(batch_op.f('ix_student_attendance_course_id'))
        batch_op.drop_index(batch_op.f('ix_student_attendance_course_assignment_id'))
        batch_op.drop_index(batch_op.f('ix_student_attendance_company_id'))
        batch_op.drop_index('ix_student_attendance_company_group_date')
        batch_op.drop_index('ix_student_attendance_company_date')
        batch_op.drop_index('ix_student_attendance_company_branch')
        batch_op.drop_index(batch_op.f('ix_student_attendance_branch_id'))
        batch_op.drop_index(batch_op.f('ix_student_attendance_attendance_date'))
        batch_op.drop_index(batch_op.f('ix_student_attendance_attendance_code'))
        batch_op.drop_index(batch_op.f('ix_student_attendance_academic_year_id'))
        batch_op.drop_index(batch_op.f('ix_student_attendance_academic_term_id'))

    op.drop_table('student_attendance')
    with op.batch_alter_table('course_schedule_slots', schema=None) as batch_op:
        batch_op.drop_index('ix_css_teacher_weekday')
        batch_op.drop_index('ix_css_group_weekday')
        batch_op.drop_index('ix_css_company_branch')
        batch_op.drop_index(batch_op.f('ix_course_schedule_slots_weekday'))
        batch_op.drop_index(batch_op.f('ix_course_schedule_slots_updated_at'))
        batch_op.drop_index(batch_op.f('ix_course_schedule_slots_time_slot_id'))
        batch_op.drop_index(batch_op.f('ix_course_schedule_slots_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_course_schedule_slots_student_group_id'))
        batch_op.drop_index(batch_op.f('ix_course_schedule_slots_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_course_schedule_slots_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_course_schedule_slots_created_at'))
        batch_op.drop_index(batch_op.f('ix_course_schedule_slots_course_id'))
        batch_op.drop_index(batch_op.f('ix_course_schedule_slots_course_assignment_id'))
        batch_op.drop_index('ix_course_schedule_slots_company_id')
        batch_op.drop_index(batch_op.f('ix_course_schedule_slots_classroom_id'))
        batch_op.drop_index(batch_op.f('ix_course_schedule_slots_branch_id'))
        batch_op.drop_index(batch_op.f('ix_course_schedule_slots_academic_year_id'))
        batch_op.drop_index(batch_op.f('ix_course_schedule_slots_academic_term_id'))

    op.drop_table('course_schedule_slots')
    with op.batch_alter_table('course_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_assignments_updated_at'))
        batch_op.drop_index(batch_op.f('ix_course_assignments_teacher_id'))
        batch_op.drop_index('ix_course_assignments_teacher')
        batch_op.drop_index(batch_op.f('ix_course_assignments_student_group_id'))
        batch_op.drop_index(batch_op.f('ix_course_assignments_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_course_assignments_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_course_assignments_created_at'))
        batch_op.drop_index(batch_op.f('ix_course_assignments_course_id'))
        batch_op.drop_index(batch_op.f('ix_course_assignments_company_id'))
        batch_op.drop_index('ix_course_assignments_company_branch')
        batch_op.drop_index(batch_op.f('ix_course_assignments_branch_id'))
        batch_op.drop_index(batch_op.f('ix_course_assignments_academic_year_id'))
        batch_op.drop_index(batch_op.f('ix_course_assignments_academic_term_id'))

    op.drop_table('course_assignments')
    with op.batch_alter_table('time_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_slots_updated_at'))
        batch_op.drop_index(batch_op.f('ix_time_slots_session_id'))
        batch_op.drop_index(batch_op.f('ix_time_slots_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_time_slots_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_time_slots_created_at'))
        batch_op.drop_index(batch_op.f('ix_time_slots_company_id'))

    op.drop_table('time_slots')
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classrooms_updated_at'))
        batch_op.drop_index(batch_op.f('ix_classrooms_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_classrooms_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_classrooms_created_at'))
        batch_op.drop_index(batch_op.f('ix_classrooms_company_id'))
        batch_op.drop_index('ix_classrooms_company_branch')
        batch_op.drop_index(batch_op.f('ix_classrooms_branch_id'))

    op.drop_table('classrooms')
    with op.batch_alter_table('school_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_company_id')
        batch_op.drop_index(batch_op.f('ix_school_sessions_updated_at'))
        batch_op.drop_index(batch_op.f('ix_school_sessions_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_school_sessions_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_school_sessions_created_at'))
        batch_op.drop_index(batch_op.f('ix_school_sessions_company_id'))

    op.drop_table('school_sessions')
    # ### end Alembic commands ###
