"""Add RBAC models

Revision ID: f88ace11ae86
Revises: b18b2791b1ba
Create Date: 2025-08-28 09:57:06.582013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f88ace11ae86'
down_revision = 'b18b2791b1ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_defined', sa.Boolean(), nullable=False),
    sa.Column('is_deprecated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_actions_name')
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actions_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_actions_is_deprecated', ['is_deprecated'], unique=False)
        batch_op.create_index('ix_actions_is_system_defined', ['is_system_defined'], unique=False)
        batch_op.create_index('ix_actions_name', ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_updated_at'), ['updated_at'], unique=False)

    op.create_table('doc_types',
    sa.Column('module', postgresql.CITEXT(), nullable=False),
    sa.Column('name', postgresql.CITEXT(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_doctype_id', sa.BigInteger(), nullable=True),
    sa.Column('is_group', sa.Boolean(), nullable=False),
    sa.Column('tree_depth', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='doctype_status_enum'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id <> COALESCE(parent_doctype_id, -1)', name='ck_doctype_no_self_parent'),
    sa.ForeignKeyConstraint(['parent_doctype_id'], ['doc_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module', 'name', name='uq_doctype_module_name')
    )
    with op.batch_alter_table('doc_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doc_types_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_doc_types_parent_doctype_id'), ['parent_doctype_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doc_types_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_doctypes_parent', ['parent_doctype_id'], unique=False)

    op.create_table('permissions',
    sa.Column('doctype_id', sa.BigInteger(), nullable=False),
    sa.Column('action_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_defined', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctype_id'], ['doc_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctype_id', 'action_id', 'company_id', name='uq_permission_doctype_action_company')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index('ix_permissions_action_id', ['action_id'], unique=False)
        batch_op.create_index('ix_permissions_company_id', ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_permissions_doctype_id', ['doctype_id'], unique=False)
        batch_op.create_index('ix_permissions_is_system_defined', ['is_system_defined'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_updated_at'), ['updated_at'], unique=False)

    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.Enum('SYSTEM', 'COMPANY', 'BRANCH', name='role_scope_enum'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('is_system_defined', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='role_status_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'scope', 'company_id', name='uq_role_name_scope_company')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index('ix_roles_company_id', ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_roles_is_system_defined', ['is_system_defined'], unique=False)
        batch_op.create_index('ix_roles_name', ['name'], unique=False)
        batch_op.create_index('ix_roles_scope', ['scope'], unique=False)
        batch_op.create_index('ix_roles_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_updated_at'), ['updated_at'], unique=False)

    op.create_table('user_constraints',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('doctype_id', sa.BigInteger(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('ref_doctype_id', sa.BigInteger(), nullable=False),
    sa.Column('ref_id', sa.BigInteger(), nullable=False),
    sa.Column('allow_children', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctype_id'], ['doc_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ref_doctype_id'], ['doc_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'doctype_id', 'field_name', 'ref_doctype_id', 'ref_id', name='uq_user_constraint')
    )
    with op.batch_alter_table('user_constraints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_constraints_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_user_constraints_doctype_id', ['doctype_id'], unique=False)
        batch_op.create_index('ix_user_constraints_field_name', ['field_name'], unique=False)
        batch_op.create_index('ix_user_constraints_ref_doctype_id', ['ref_doctype_id'], unique=False)
        batch_op.create_index('ix_user_constraints_ref_id', ['ref_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_constraints_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_user_constraints_user_id', ['user_id'], unique=False)

    op.create_table('permission_overrides',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('is_allowed', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('granted_by', sa.BigInteger(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'permission_id', 'company_id', 'branch_id', name='uq_user_permission_override_scope')
    )
    with op.batch_alter_table('permission_overrides', schema=None) as batch_op:
        batch_op.create_index('ix_perm_overrides_branch_id', ['branch_id'], unique=False)
        batch_op.create_index('ix_perm_overrides_company_id', ['company_id'], unique=False)
        batch_op.create_index('ix_perm_overrides_granted_by', ['granted_by'], unique=False)
        batch_op.create_index('ix_perm_overrides_permission_id', ['permission_id'], unique=False)
        batch_op.create_index('ix_perm_overrides_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permission_overrides_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_permission_overrides_updated_at'), ['updated_at'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_permissions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permissions_permission_id'), ['permission_id'], unique=False)
        batch_op.create_index('ix_role_permissions_role_id', ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permissions_updated_at'), ['updated_at'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('user_affiliation_id', sa.BigInteger(), nullable=True),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('assigned_by', sa.BigInteger(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_affiliation_id'], ['user_affiliations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', 'company_id', 'branch_id', name='uq_user_role_scope')
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index('ix_user_roles_branch_id', ['branch_id'], unique=False)
        batch_op.create_index('ix_user_roles_company_id', ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_user_roles_is_active', ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_user_roles_user_affiliation_id', ['user_affiliation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roles_user_id'))
        batch_op.drop_index('ix_user_roles_user_affiliation_id')
        batch_op.drop_index(batch_op.f('ix_user_roles_updated_at'))
        batch_op.drop_index(batch_op.f('ix_user_roles_role_id'))
        batch_op.drop_index('ix_user_roles_is_active')
        batch_op.drop_index(batch_op.f('ix_user_roles_created_at'))
        batch_op.drop_index('ix_user_roles_company_id')
        batch_op.drop_index('ix_user_roles_branch_id')

    op.drop_table('user_roles')
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_permissions_updated_at'))
        batch_op.drop_index('ix_role_permissions_role_id')
        batch_op.drop_index(batch_op.f('ix_role_permissions_permission_id'))
        batch_op.drop_index(batch_op.f('ix_role_permissions_created_at'))

    op.drop_table('role_permissions')
    with op.batch_alter_table('permission_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permission_overrides_updated_at'))
        batch_op.drop_index(batch_op.f('ix_permission_overrides_created_at'))
        batch_op.drop_index('ix_perm_overrides_user_id')
        batch_op.drop_index('ix_perm_overrides_permission_id')
        batch_op.drop_index('ix_perm_overrides_granted_by')
        batch_op.drop_index('ix_perm_overrides_company_id')
        batch_op.drop_index('ix_perm_overrides_branch_id')

    op.drop_table('permission_overrides')
    with op.batch_alter_table('user_constraints', schema=None) as batch_op:
        batch_op.drop_index('ix_user_constraints_user_id')
        batch_op.drop_index(batch_op.f('ix_user_constraints_updated_at'))
        batch_op.drop_index('ix_user_constraints_ref_id')
        batch_op.drop_index('ix_user_constraints_ref_doctype_id')
        batch_op.drop_index('ix_user_constraints_field_name')
        batch_op.drop_index('ix_user_constraints_doctype_id')
        batch_op.drop_index(batch_op.f('ix_user_constraints_created_at'))

    op.drop_table('user_constraints')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_updated_at'))
        batch_op.drop_index('ix_roles_status')
        batch_op.drop_index('ix_roles_scope')
        batch_op.drop_index('ix_roles_name')
        batch_op.drop_index('ix_roles_is_system_defined')
        batch_op.drop_index(batch_op.f('ix_roles_created_at'))
        batch_op.drop_index('ix_roles_company_id')

    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_updated_at'))
        batch_op.drop_index('ix_permissions_is_system_defined')
        batch_op.drop_index('ix_permissions_doctype_id')
        batch_op.drop_index(batch_op.f('ix_permissions_created_at'))
        batch_op.drop_index('ix_permissions_company_id')
        batch_op.drop_index('ix_permissions_action_id')

    op.drop_table('permissions')
    with op.batch_alter_table('doc_types', schema=None) as batch_op:
        batch_op.drop_index('ix_doctypes_parent')
        batch_op.drop_index(batch_op.f('ix_doc_types_updated_at'))
        batch_op.drop_index(batch_op.f('ix_doc_types_parent_doctype_id'))
        batch_op.drop_index(batch_op.f('ix_doc_types_created_at'))

    op.drop_table('doc_types')
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actions_updated_at'))
        batch_op.drop_index('ix_actions_name')
        batch_op.drop_index('ix_actions_is_system_defined')
        batch_op.drop_index('ix_actions_is_deprecated')
        batch_op.drop_index(batch_op.f('ix_actions_created_at'))

    op.drop_table('actions')
    # ### end Alembic commands ###
