# -*- coding: utf-8 -*-
"""
Update education system models and permissions

Revision ID: fb06d3fc466b
Revises: f13810aca274
Create Date: 2026-01-08 23:33:54.660843
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb06d3fc466b'
down_revision = 'f13810aca274'
branch_labels = None
depends_on = None


DOCSTATUSENUM_NAME = "docstatusenum"
DOCSTATUSENUM_VALUES = (
    "DRAFT",
    "SUBMITTED",
    "CANCELLED",
    "UNPAID",
    "PARTIALLY_PAID",
    "PAID",
    "OVERDUE",
    "RETURNED",
)


def _ensure_pg_enum(type_name: str, values: tuple[str, ...]) -> None:
    """
    Ensure a PostgreSQL ENUM type exists and contains all required values.

    - If the type doesn't exist: create it.
    - If it exists: add any missing enum labels (appended at the end).
    """
    bind = op.get_bind()

    exists = bind.execute(
        sa.text("SELECT 1 FROM pg_type WHERE typname = :t LIMIT 1"),
        {"t": type_name},
    ).scalar()

    enum_type = postgresql.ENUM(*values, name=type_name)

    if not exists:
        # Safe creation (will only create if missing)
        enum_type.create(bind, checkfirst=True)
        return

    # Type exists: ensure all labels are present
    existing_labels = {
        row[0]
        for row in bind.execute(
            sa.text(
                """
                SELECT e.enumlabel
                FROM pg_enum e
                JOIN pg_type t ON t.oid = e.enumtypid
                WHERE t.typname = :t
                ORDER BY e.enumsortorder
                """
            ),
            {"t": type_name},
        ).fetchall()
    }

    missing = [v for v in values if v not in existing_labels]
    for v in missing:
        # Append missing values (safe because we checked in Python)
        bind.execute(sa.text(f"ALTER TYPE {type_name} ADD VALUE :val"), {"val": v})


def _drop_pg_enum_if_unused(type_name: str) -> None:
    """
    Drop a PostgreSQL ENUM type only if it exists and no columns use it.
    Safe for shared/prod DBs.
    """
    bind = op.get_bind()

    # Does the type exist?
    exists = bind.execute(
        sa.text("SELECT 1 FROM pg_type WHERE typname = :t LIMIT 1"),
        {"t": type_name},
    ).scalar()
    if not exists:
        return

    # Count columns that still use this type
    in_use = bind.execute(
        sa.text(
            """
            SELECT COUNT(*)
            FROM pg_attribute a
            JOIN pg_class c ON c.oid = a.attrelid
            JOIN pg_type t ON t.oid = a.atttypid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE t.typname = :t
              AND a.attnum > 0
              AND NOT a.attisdropped
              AND c.relkind IN ('r', 'p') -- tables / partitioned tables
            """
        ),
        {"t": type_name},
    ).scalar()

    if not in_use:
        bind.execute(sa.text(f"DROP TYPE IF EXISTS {type_name}"))


def upgrade():
    # Ensure enum exists (and has all required values) BEFORE creating tables that use it
    _ensure_pg_enum(DOCSTATUSENUM_NAME, DOCSTATUSENUM_VALUES)

    # Use create_type=False so table creation never attempts CREATE TYPE again
    docstatus_enum = postgresql.ENUM(
        *DOCSTATUSENUM_VALUES,
        name=DOCSTATUSENUM_NAME,
        create_type=False,
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'workspace_roles',
        sa.Column('workspace_id', sa.BigInteger(), nullable=False),
        sa.Column('role_name', sa.String(length=100), nullable=False),
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('workspace_id', 'role_name', name='uq_workspace_role')
    )
    with op.batch_alter_table('workspace_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_roles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_roles_role_name'), ['role_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_roles_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_roles_workspace_id'), ['workspace_id'], unique=False)

    op.create_table(
        'sales_delivery_notes',
        sa.Column('company_id', sa.BigInteger(), nullable=False),
        sa.Column('branch_id', sa.BigInteger(), nullable=False),
        sa.Column('created_by_id', sa.BigInteger(), nullable=False),
        sa.Column('customer_id', sa.BigInteger(), nullable=False),
        sa.Column('return_against_id', sa.BigInteger(), nullable=True),
        sa.Column('code', sa.String(length=100), nullable=False),
        sa.Column('posting_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('doc_status', docstatus_enum, nullable=False),
        sa.Column('is_return', sa.Boolean(), nullable=False),
        sa.Column('remarks', sa.Text(), nullable=True),
        sa.Column('total_amount', sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint(
            """
            (
              is_return = true AND return_against_id IS NOT NULL
            )
            OR
            (
              is_return = false AND return_against_id IS NULL
            )
            """,
            name='ck_sdn_return_link_consistency'
        ),
        sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
        sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ),
        sa.ForeignKeyConstraint(['return_against_id'], ['sales_delivery_notes.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('company_id', 'branch_id', 'code', name='uq_sdn_branch_code')
    )
    with op.batch_alter_table('sales_delivery_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_delivery_notes_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_delivery_notes_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_delivery_notes_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_delivery_notes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_delivery_notes_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_delivery_notes_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_delivery_notes_doc_status'), ['doc_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_delivery_notes_is_return'), ['is_return'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_delivery_notes_posting_date'), ['posting_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_delivery_notes_return_against_id'), ['return_against_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_delivery_notes_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_sdn_company_branch_status', ['company_id', 'branch_id', 'doc_status'], unique=False)
        batch_op.create_index('ix_sdn_company_customer', ['company_id', 'customer_id'], unique=False)
        batch_op.create_index('ix_sdn_company_posting_date', ['company_id', 'posting_date'], unique=False)
        batch_op.create_index('ix_sdn_is_return', ['is_return'], unique=False)

    op.create_table(
        'sales_delivery_note_items',
        sa.Column('delivery_note_id', sa.BigInteger(), nullable=False),
        sa.Column('item_id', sa.BigInteger(), nullable=False),
        sa.Column('uom_id', sa.BigInteger(), nullable=True),
        sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
        sa.Column('return_against_item_id', sa.BigInteger(), nullable=True),
        sa.Column('delivered_qty', sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column('amount', sa.Numeric(precision=14, scale=4),
                  sa.Computed('CASE WHEN unit_price IS NULL THEN NULL ELSE delivered_qty * unit_price END', persisted=True),
                  nullable=True),
        sa.Column('remarks', sa.String(length=255), nullable=True),
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('delivered_qty <> 0', name='ck_sdni_qty_non_zero'),
        sa.CheckConstraint('unit_price IS NULL OR unit_price >= 0', name='ck_sdni_rate_non_negative'),
        sa.ForeignKeyConstraint(['delivery_note_id'], ['sales_delivery_notes.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['return_against_item_id'], ['sales_delivery_note_items.id'], ),
        sa.ForeignKeyConstraint(['uom_id'], ['units_of_measure.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_delivery_note_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_delivery_note_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_delivery_note_items_delivery_note_id'), ['delivery_note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_delivery_note_items_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_delivery_note_items_return_against_item_id'), ['return_against_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_delivery_note_items_uom_id'), ['uom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_delivery_note_items_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_delivery_note_items_warehouse_id'), ['warehouse_id'], unique=False)
        batch_op.create_index('ix_sdni_item', ['item_id'], unique=False)
        batch_op.create_index('ix_sdni_return_against', ['return_against_item_id'], unique=False)
        batch_op.create_index('ix_sdni_warehouse', ['warehouse_id'], unique=False)

    with op.batch_alter_table('item_prices', schema=None) as batch_op:
        batch_op.alter_column(
            'code',
            existing_type=sa.VARCHAR(length=100),
            comment=None,
            existing_comment='An optional external or human-readable code for this specific item price rule.',
            existing_nullable=False
        )
        batch_op.drop_index('ix_item_price_company_code_lookup')
        batch_op.drop_index('ix_item_price_lookup_full', postgresql_include=['rate'])
        batch_op.drop_index('ix_item_price_uom')
        batch_op.drop_index('ix_item_price_validity')
        batch_op.drop_constraint('uq_item_price_branch_unique', type_='unique')
        batch_op.drop_index('ix_item_price_branch_null', postgresql_where='(branch_id IS NULL)')
        batch_op.create_index(
            'ix_item_price_branch_null',
            ['company_id', 'price_list_id', 'item_id', 'uom_id', 'valid_from', 'valid_upto'],
            unique=False,
            postgresql_where=sa.text('branch_id IS NULL')
        )
        batch_op.drop_index('ix_item_price_branch_some', postgresql_where='(branch_id IS NOT NULL)')
        batch_op.create_index(
            'ix_item_price_branch_some',
            ['company_id', 'price_list_id', 'item_id', 'branch_id', 'uom_id', 'valid_from', 'valid_upto'],
            unique=False,
            postgresql_where=sa.text('branch_id IS NOT NULL')
        )
        batch_op.drop_index('ix_item_price_lookup')
        batch_op.create_index(
            'ix_item_price_lookup',
            ['company_id', 'price_list_id', 'item_id', 'branch_id', 'uom_id', 'valid_from', 'valid_upto'],
            unique=False
        )
        batch_op.create_index(batch_op.f('ix_item_prices_valid_from'), ['valid_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_prices_valid_upto'), ['valid_upto'], unique=False)

    with op.batch_alter_table('price_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=False))
        batch_op.alter_column(
            'name',
            existing_type=sa.VARCHAR(length=255),
            comment=None,
            existing_comment="e.g., 'Standard Selling Price', 'Wholesale Purchase Price'",
            existing_nullable=False
        )
        batch_op.alter_column(
            'list_type',
            existing_type=postgresql.ENUM('BUYING', 'SELLING', 'BOTH', name='pricelisttype'),
            comment=None,
            existing_comment='Determines if this price list is used for Sales, Purchases, or both.',
            existing_nullable=False
        )
        batch_op.alter_column(
            'price_not_uom_dependent',
            existing_type=sa.BOOLEAN(),
            comment=None,
            existing_comment='ERP-style: if true, use same price irrespective of txn UOM; convert for display.',
            existing_nullable=False
        )
        batch_op.alter_column(
            'is_active',
            existing_type=sa.BOOLEAN(),
            comment=None,
            existing_comment='A disabled price list cannot be used in new transactions.',
            existing_nullable=False
        )
        batch_op.drop_index('ix_price_list_type_active')
        batch_op.create_index(
            'ix_price_list_company_type_active_default',
            ['company_id', 'list_type', 'is_active', 'is_default'],
            unique=False
        )
        batch_op.create_index(batch_op.f('ix_price_lists_is_default'), ['is_default'], unique=False)
        batch_op.create_index(
            'uq_price_list_default_buying',
            ['company_id'],
            unique=True,
            postgresql_where=sa.text("is_default IS true AND list_type IN ('BUYING', 'BOTH')")
        )
        batch_op.create_index(
            'uq_price_list_default_selling',
            ['company_id'],
            unique=True,
            postgresql_where=sa.text("is_default IS true AND list_type IN ('SELLING', 'BOTH')")
        )

    with op.batch_alter_table('stock_ledger_entries', schema=None) as batch_op:
        batch_op.drop_constraint('uq_sle_code', type_='unique')
        batch_op.drop_index('ix_stock_ledger_entries_code')
        batch_op.create_index(batch_op.f('ix_stock_ledger_entries_code'), ['code'], unique=False)
        batch_op.create_unique_constraint('uq_sle_company_code', ['company_id', 'code'])

    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_constraint('uq_wh_company_branch_name', type_='unique')
        batch_op.drop_constraint('uq_wh_company_code', type_='unique')
        batch_op.create_index(
            'uq_wh_company_branch_name_when_branch_not_null',
            ['company_id', 'branch_id', sa.text('lower(name)')],
            unique=True,
            postgresql_where=sa.text('branch_id IS NOT NULL')
        )
        batch_op.create_index(
            'uq_wh_company_code_lower',
            ['company_id', sa.text('lower(code)')],
            unique=True
        )
        batch_op.create_index(
            'uq_wh_company_name_when_branch_null',
            ['company_id', sa.text('lower(name)')],
            unique=True,
            postgresql_where=sa.text('branch_id IS NULL')
        )
        batch_op.create_index(
            'uq_wh_one_root_per_company',
            ['company_id'],
            unique=True,
            postgresql_where=sa.text('parent_warehouse_id IS NULL AND branch_id IS NULL AND is_group = TRUE')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_index('uq_wh_one_root_per_company',
                            postgresql_where=sa.text('parent_warehouse_id IS NULL AND branch_id IS NULL AND is_group = TRUE'))
        batch_op.drop_index('uq_wh_company_name_when_branch_null', postgresql_where=sa.text('branch_id IS NULL'))
        batch_op.drop_index('uq_wh_company_code_lower')
        batch_op.drop_index('uq_wh_company_branch_name_when_branch_not_null',
                            postgresql_where=sa.text('branch_id IS NOT NULL'))
        batch_op.create_unique_constraint('uq_wh_company_code', ['company_id', 'code'])
        batch_op.create_unique_constraint('uq_wh_company_branch_name', ['company_id', 'branch_id', 'name'])

    with op.batch_alter_table('stock_ledger_entries', schema=None) as batch_op:
        batch_op.drop_constraint('uq_sle_company_code', type_='unique')
        batch_op.drop_index(batch_op.f('ix_stock_ledger_entries_code'))
        batch_op.create_index('ix_stock_ledger_entries_code', ['code'], unique=True)
        batch_op.create_unique_constraint('uq_sle_code', ['code'])

    with op.batch_alter_table('price_lists', schema=None) as batch_op:
        batch_op.drop_index('uq_price_list_default_selling',
                            postgresql_where=sa.text("is_default IS true AND list_type IN ('SELLING', 'BOTH')"))
        batch_op.drop_index('uq_price_list_default_buying',
                            postgresql_where=sa.text("is_default IS true AND list_type IN ('BUYING', 'BOTH')"))
        batch_op.drop_index(batch_op.f('ix_price_lists_is_default'))
        batch_op.drop_index('ix_price_list_company_type_active_default')
        batch_op.create_index('ix_price_list_type_active', ['list_type', 'is_active'], unique=False)
        batch_op.alter_column('is_active',
                              existing_type=sa.BOOLEAN(),
                              comment='A disabled price list cannot be used in new transactions.',
                              existing_nullable=False)
        batch_op.alter_column('price_not_uom_dependent',
                              existing_type=sa.BOOLEAN(),
                              comment='ERP-style: if true, use same price irrespective of txn UOM; convert for display.',
                              existing_nullable=False)
        batch_op.alter_column('list_type',
                              existing_type=postgresql.ENUM('BUYING', 'SELLING', 'BOTH', name='pricelisttype'),
                              comment='Determines if this price list is used for Sales, Purchases, or both.',
                              existing_nullable=False)
        batch_op.alter_column('name',
                              existing_type=sa.VARCHAR(length=255),
                              comment="e.g., 'Standard Selling Price', 'Wholesale Purchase Price'",
                              existing_nullable=False)
        batch_op.drop_column('is_default')

    with op.batch_alter_table('item_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_prices_valid_upto'))
        batch_op.drop_index(batch_op.f('ix_item_prices_valid_from'))
        batch_op.drop_index('ix_item_price_lookup')
        batch_op.create_index('ix_item_price_lookup', ['item_id', 'price_list_id', 'branch_id'], unique=False)
        batch_op.drop_index('ix_item_price_branch_some', postgresql_where=sa.text('branch_id IS NOT NULL'))
        batch_op.create_index('ix_item_price_branch_some',
                              ['price_list_id', 'item_id', 'uom_id', 'branch_id', 'valid_from', 'valid_upto'],
                              unique=False, postgresql_where='(branch_id IS NOT NULL)')
        batch_op.drop_index('ix_item_price_branch_null', postgresql_where=sa.text('branch_id IS NULL'))
        batch_op.create_index('ix_item_price_branch_null',
                              ['price_list_id', 'item_id', 'uom_id', 'valid_from', 'valid_upto'],
                              unique=False, postgresql_where='(branch_id IS NULL)')
        batch_op.create_unique_constraint('uq_item_price_branch_unique', ['price_list_id', 'item_id', 'uom_id', 'branch_id'])
        batch_op.create_index('ix_item_price_validity', ['valid_from', 'valid_upto'], unique=False)
        batch_op.create_index('ix_item_price_uom', ['item_id', 'uom_id', 'price_list_id'], unique=False)
        batch_op.create_index('ix_item_price_lookup_full',
                              ['price_list_id', 'item_id', 'uom_id', 'branch_id', 'valid_from', 'valid_upto'],
                              unique=False, postgresql_include=['rate'])
        batch_op.create_index('ix_item_price_company_code_lookup', ['company_id', 'code'], unique=False)
        batch_op.alter_column('code',
                              existing_type=sa.VARCHAR(length=100),
                              comment='An optional external or human-readable code for this specific item price rule.',
                              existing_nullable=False)

    with op.batch_alter_table('sales_delivery_note_items', schema=None) as batch_op:
        batch_op.drop_index('ix_sdni_warehouse')
        batch_op.drop_index('ix_sdni_return_against')
        batch_op.drop_index('ix_sdni_item')
        batch_op.drop_index(batch_op.f('ix_sales_delivery_note_items_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_sales_delivery_note_items_updated_at'))
        batch_op.drop_index(batch_op.f('ix_sales_delivery_note_items_uom_id'))
        batch_op.drop_index(batch_op.f('ix_sales_delivery_note_items_return_against_item_id'))
        batch_op.drop_index(batch_op.f('ix_sales_delivery_note_items_item_id'))
        batch_op.drop_index(batch_op.f('ix_sales_delivery_note_items_delivery_note_id'))
        batch_op.drop_index(batch_op.f('ix_sales_delivery_note_items_created_at'))

    op.drop_table('sales_delivery_note_items')

    with op.batch_alter_table('sales_delivery_notes', schema=None) as batch_op:
        batch_op.drop_index('ix_sdn_is_return')
        batch_op.drop_index('ix_sdn_company_posting_date')
        batch_op.drop_index('ix_sdn_company_customer')
        batch_op.drop_index('ix_sdn_company_branch_status')
        batch_op.drop_index(batch_op.f('ix_sales_delivery_notes_updated_at'))
        batch_op.drop_index(batch_op.f('ix_sales_delivery_notes_return_against_id'))
        batch_op.drop_index(batch_op.f('ix_sales_delivery_notes_posting_date'))
        batch_op.drop_index(batch_op.f('ix_sales_delivery_notes_is_return'))
        batch_op.drop_index(batch_op.f('ix_sales_delivery_notes_doc_status'))
        batch_op.drop_index(batch_op.f('ix_sales_delivery_notes_customer_id'))
        batch_op.drop_index(batch_op.f('ix_sales_delivery_notes_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_sales_delivery_notes_created_at'))
        batch_op.drop_index(batch_op.f('ix_sales_delivery_notes_company_id'))
        batch_op.drop_index(batch_op.f('ix_sales_delivery_notes_code'))
        batch_op.drop_index(batch_op.f('ix_sales_delivery_notes_branch_id'))

    op.drop_table('sales_delivery_notes')

    with op.batch_alter_table('workspace_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_roles_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_roles_updated_at'))
        batch_op.drop_index(batch_op.f('ix_workspace_roles_role_name'))
        batch_op.drop_index(batch_op.f('ix_workspace_roles_created_at'))

    op.drop_table('workspace_roles')

    # Only drop the enum if nothing else uses it (safe for shared DBs)
    _drop_pg_enum_if_unused(DOCSTATUSENUM_NAME)
    # ### end Alembic commands ###
